// SPDX-License-Identifier: Apache-2.0
package demo;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;

/** Prints line-count.txt generated by project build logic under .jk-build/. */
public final class App {
    public static void main(String[] args) throws Exception {
        try (InputStream in = App.class.getResourceAsStream("/line-count.txt")) {
            if (in == null) {
                System.out.println("line-count.txt missing (build logic did not run)");
                return;
            }
            System.out.println("Line Count: " + new String(in.readAllBytes(), StandardCharsets.UTF_8).trim());
        }
    }
}
