group = "cc.jumpkick"
name = "jk"
version = "0.12.0"
description = "JumpKick: The best damn build system for the JVM"
java = 25
graal = 25

[workspace]
modules = [
  # Shared Libraries
  "shared/jsonl",
  "shared/plugin-sdk",
  "shared/jk-api",
  "shared/core",
  "shared/client-io",
  "shared/dynamic-surface",
  # Server/Engine
  "server/io",
  "server/resolver",
  "shared/toolchain-jdk",
  "server/toolchain",
  "shared/wire",
  "server/engine",
  # Clients
  "clients/cli",
  "clients/web",
  # Plugins/Workers
  "plugins/test-runner",
  "plugins/java-compiler",
  "plugins/kotlin-compiler",
  "plugins/groovy-compiler",
  "plugins/auditor",
  "plugins/publisher",
  "plugins/image-builder",
  "plugins/compat-bridge",
  "plugins/minified",
  "plugins/formatter",
  "plugins/spring-boot",
  "plugins/quarkus",
  "plugins/grails",
  "plugins/protobuf",
  "plugins/android",
]
