// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.command.toolchain;

import cc.jumpkick.model.command.CliCommand;
import cc.jumpkick.util.JkDirs;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Writes shell completion scripts under {@code <store>/completions/&lt;shell&gt;/}. Top-level
 * command names come from the dispatcher's table, which the caller passes in.
 */
public final class ShellCompletions {

    private ShellCompletions() {}

    /** Write completions for all supported shells; returns the completions root. */
    public static Path writeAll(List<CliCommand> commands) throws IOException {
        Path root = JkDirs.store().resolve("completions");
        writeBash(root.resolve("bash"), commands);
        writeZsh(root.resolve("zsh"), commands);
        writeFish(root.resolve("fish"), commands);
        writePwsh(root.resolve("pwsh"), commands);
        return root;
    }

    static List<String> topLevelNames(List<CliCommand> commands) {
        Set<String> names = new LinkedHashSet<>();
        for (CliCommand c : commands) {
            if (c.hidden()) continue;
            names.add(c.name());
            for (String a : c.aliases()) names.add(a);
        }
        return new ArrayList<>(names);
    }

    private static void writeBash(Path dir, List<CliCommand> commands) throws IOException {
        Files.createDirectories(dir);
        StringBuilder sb = new StringBuilder();
        sb.append("# jk bash completion — generated by JumpKick\n");
        sb.append("_jk() {\n");
        sb.append("  local cur cmds\n");
        sb.append("  COMPREPLY=()\n");
        sb.append("  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n");
        sb.append("  cmds=\"");
        sb.append(String.join(" ", topLevelNames(commands)));
        sb.append("\"\n");
        sb.append("  if [[ ${COMP_CWORD} -eq 1 ]]; then\n");
        sb.append("    COMPREPLY=( $(compgen -W \"${cmds}\" -- \"${cur}\") )\n");
        sb.append("  fi\n");
        sb.append("}\n");
        sb.append("complete -F _jk jk\n");
        sb.append("complete -F _jk jkx\n");
        Files.writeString(dir.resolve("jk"), sb.toString(), StandardCharsets.UTF_8);
    }

    private static void writeZsh(Path dir, List<CliCommand> commands) throws IOException {
        Files.createDirectories(dir);
        StringBuilder sb = new StringBuilder();
        sb.append("#compdef jk jkx\n");
        sb.append("# jk zsh completion — generated by JumpKick\n");
        sb.append("_jk() {\n");
        sb.append("  local -a cmds\n");
        sb.append("  cmds=(\n");
        for (String n : topLevelNames(commands)) {
            sb.append("    '").append(n.replace("'", "'\\''")).append("'\n");
        }
        sb.append("  )\n");
        sb.append("  _arguments '1:command:($cmds)' '*::arg:->args'\n");
        sb.append("}\n");
        sb.append("compdef _jk jk jkx\n");
        Files.writeString(dir.resolve("_jk"), sb.toString(), StandardCharsets.UTF_8);
    }

    private static void writeFish(Path dir, List<CliCommand> commands) throws IOException {
        Files.createDirectories(dir);
        StringBuilder sb = new StringBuilder();
        sb.append("# jk fish completion — generated by JumpKick\n");
        sb.append("complete -c jk -f\n");
        sb.append("complete -c jkx -f\n");
        for (String n : topLevelNames(commands)) {
            sb.append("complete -c jk -n '__fish_use_subcommand' -a ")
                    .append(PosixQuote.quote(n))
                    .append("\n");
            sb.append("complete -c jkx -n '__fish_use_subcommand' -a ")
                    .append(PosixQuote.quote(n))
                    .append("\n");
        }
        Files.writeString(dir.resolve("jk.fish"), sb.toString(), StandardCharsets.UTF_8);
    }

    private static void writePwsh(Path dir, List<CliCommand> commands) throws IOException {
        Files.createDirectories(dir);
        StringBuilder sb = new StringBuilder();
        sb.append("# jk PowerShell completion — generated by JumpKick\n");
        sb.append("$script:__jkCommands = @(\n");
        for (String n : topLevelNames(commands)) {
            sb.append("  '").append(n.replace("'", "''")).append("'\n");
        }
        sb.append(")\n");
        sb.append("Register-ArgumentCompleter -Native -CommandName jk,jkx -ScriptBlock {\n");
        sb.append("  param($wordToComplete, $commandAst, $cursorPosition)\n");
        sb.append("  $script:__jkCommands | Where-Object { $_ -like \"$wordToComplete*\" } |\n");
        sb.append(
                "    ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }\n");
        sb.append("}\n");
        Files.writeString(dir.resolve("jk.ps1"), sb.toString(), StandardCharsets.UTF_8);
    }
}
