// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.lock;

import cc.jumpkick.model.JkBuild;
import cc.jumpkick.model.PackageId;
import cc.jumpkick.model.Scope;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.EnumSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

/**
 * Renders a Maven BOM ({@code packaging=pom} + {@code dependencyManagement}) from a resolved
 * {@link Lockfile} filtered by scope (JK-1207). Default freezes the main/export/runtime graph —
 * the set actually resolved and typically tested.
 */
public final class BomExporter {

    private BomExporter() {}

    /** Scopes included when {@code scope=main} (default). */
    public static final Set<Scope> MAIN_SCOPES =
            EnumSet.of(Scope.EXPORT, Scope.MAIN, Scope.RUNTIME, Scope.PROVIDED, Scope.DEV);

    /** Scopes included when {@code scope=test}. */
    public static final Set<Scope> TEST_SCOPES = EnumSet.of(Scope.TEST, Scope.TEST_DEV);

    public static Set<Scope> scopesFor(String scopeName) {
        if (scopeName == null || scopeName.isBlank() || "main".equalsIgnoreCase(scopeName)) {
            return MAIN_SCOPES;
        }
        if ("test".equalsIgnoreCase(scopeName)) {
            return TEST_SCOPES;
        }
        if ("all".equalsIgnoreCase(scopeName)) {
            return EnumSet.allOf(Scope.class);
        }
        throw new IllegalArgumentException("unknown BOM scope `" + scopeName + "` (want main, test, or all)");
    }

    /**
     * @param project coordinates for the BOM GAV ({@code name}-bom)
     * @param lock resolved lock
     * @param scopes which artifact scopes to include
     */
    public static String render(JkBuild project, Lockfile lock, Set<Scope> scopes) {
        Objects.requireNonNull(project, "project");
        Objects.requireNonNull(lock, "lock");
        Objects.requireNonNull(scopes, "scopes");
        String group = project.project().group();
        String name = project.project().name() + "-bom";
        String version = project.project().version() != null ? project.project().version() : "0.1.0";

        List<Lockfile.Artifact> selected = new ArrayList<>();
        for (Lockfile.Artifact a : lock.artifacts()) {
            if (a.inAnyScope(scopes)) selected.add(a);
        }
        selected.sort(Comparator.comparing(Lockfile.Artifact::name).thenComparing(Lockfile.Artifact::version));
        // One dependencyManagement entry per module (JK-1239): the lock can carry main/test
        // duals of the same G:A at different versions, and Maven consumers warn on duplicate
        // managed entries then keep one arbitrarily. MAIN-scoped rows outrank test duals;
        // same-priority collisions keep the higher version (the later row after the sort).
        java.util.Map<String, Lockfile.Artifact> byModule = new java.util.LinkedHashMap<>();
        for (Lockfile.Artifact a : selected) {
            Lockfile.Artifact prev = byModule.get(a.name());
            if (prev == null) {
                byModule.put(a.name(), a);
                continue;
            }
            boolean prevMain = prev.scopes().contains(cc.jumpkick.model.Scope.MAIN);
            boolean curMain = a.scopes().contains(cc.jumpkick.model.Scope.MAIN);
            if (curMain && !prevMain) byModule.put(a.name(), a);
            else if (curMain == prevMain) byModule.put(a.name(), a); // sorted ascending — keep higher
        }
        selected = new ArrayList<>(byModule.values());

        StringBuilder sb = new StringBuilder(512);
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<!-- Generated by jk export bom from jk.lock — exact versions, freeze of the lock. -->\n");
        sb.append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n");
        sb.append("         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n");
        sb.append("         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 ");
        sb.append("https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n");
        sb.append("  <modelVersion>4.0.0</modelVersion>\n");
        sb.append("  <groupId>").append(xml(group)).append("</groupId>\n");
        sb.append("  <artifactId>").append(xml(name)).append("</artifactId>\n");
        sb.append("  <version>").append(xml(version)).append("</version>\n");
        sb.append("  <packaging>pom</packaging>\n");
        sb.append("  <name>").append(xml(project.project().name())).append(" BOM</name>\n");
        sb.append("  <description>BOM exported from jk.lock (scope-filtered)</description>\n");
        sb.append("  <dependencyManagement>\n");
        sb.append("    <dependencies>\n");
        for (Lockfile.Artifact a : selected) {
            writeDep(sb, a);
        }
        sb.append("    </dependencies>\n");
        sb.append("  </dependencyManagement>\n");
        sb.append("</project>\n");
        return sb.toString();
    }

    private static void writeDep(StringBuilder sb, Lockfile.Artifact a) {
        PackageId id;
        try {
            id = PackageId.isMavenPackageKey(a.name())
                    ? PackageId.parse(a.name())
                    : PackageId.ofGa(a.name());
        } catch (RuntimeException e) {
            return; // skip non-maven keys
        }
        sb.append("      <dependency>\n");
        sb.append("        <groupId>").append(xml(id.group())).append("</groupId>\n");
        sb.append("        <artifactId>").append(xml(id.artifact())).append("</artifactId>\n");
        sb.append("        <version>").append(xml(a.version())).append("</version>\n");
        if (id.type() != null && !id.type().isBlank() && !"jar".equals(id.type())) {
            sb.append("        <type>").append(xml(id.type())).append("</type>\n");
        }
        if (id.classifier() != null && !id.classifier().isBlank()) {
            sb.append("        <classifier>").append(xml(id.classifier())).append("</classifier>\n");
        }
        sb.append("      </dependency>\n");
    }

    private static String xml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }
}
