// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.android;

import cc.jumpkick.plugin.build.StepExec;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * The {@code android-buildconfig} step ({@code [android] build-config = true} — an explicit
 * toggle, deliberately not AGP's default-on grab-bag): a generated {@code BuildConfig.java}
 * under the module's namespace, contributed to the compiler's source set. {@code DEBUG} reflects
 * the selected build type ({@code jk build --release} → false); {@code APPLICATION_ID} carries
 * the variant's {@code application-id-suffix} when one applies.
 */
final class BuildConfigStep {

    private BuildConfigStep() {}

    static void run(StepExec exec) throws Exception {
        String namespace = exec.config().string("namespace");
        boolean debug = !"release".equals(exec.config().stringOpt("build-type").orElse("debug"));
        String applicationId =
                namespace + exec.config().stringOpt("application-id-suffix").orElse("");
        Path gen = exec.outputDir("gen");
        Path file = gen.resolve(namespace.replace('.', '/')).resolve("BuildConfig.java");
        Files.createDirectories(file.getParent());
        exec.label("BuildConfig");
        StringBuilder src = new StringBuilder()
                .append("/* Generated by jk — do not edit. */\n")
                .append("package ")
                .append(namespace)
                .append(";\n\n")
                .append("public final class BuildConfig {\n")
                .append("    private BuildConfig() {}\n\n")
                .append("    public static final boolean DEBUG = ")
                .append(debug)
                .append(";\n")
                .append("    public static final String APPLICATION_ID = \"")
                .append(applicationId)
                .append("\";\n")
                .append("    public static final String VERSION_NAME = \"")
                .append(exec.project().version())
                .append("\";\n")
                .append("    public static final int VERSION_CODE = 1;\n");
        // Custom constants ([android] build-config-fields): each entry is a verbatim
        // `TYPE NAME = VALUE` declaration — AGP's buildConfigField, declaratively.
        for (String field : exec.config().stringList("build-config-fields")) {
            src.append("    public static final ").append(field.trim()).append(";\n");
        }
        src.append("}\n");
        Files.writeString(file, src);
    }
}
