@echo off
rem jk bootstrap wrapper - generated by `jk wrapper`; do not edit (regenerate instead).
rem Bootstraps CURRENT jk, never a historical one: installed jk satisfying the lock's
rem optional jk-min floor, else the latest published release - its signed latest/LATEST
rem pointer, then the signed SHA256SUMS, both checked by the one :verify_signature subroutine.
rem The lock pins inputs, not the operator.
rem
rem Nothing read from the network or from the repository is ever spliced into command text.
rem The VERSION the release host answers, the jk-min floor in jk-lock.toml and the installed
rem VERSION file must each be a version token (letters, digits, . _ -) before they are used,
rem and they reach PowerShell only through environment variables - a hostile value cannot end
rem a quoted string or a command. Flow control is goto/call, not ( ) blocks: cmd expands
rem %VAR% inside a block when it parses the block, so a variable set inside one is stale there.
setlocal enabledelayedexpansion

rem Bin dir resolution mirrors install.ps1 / JkDirs, which is now one answer rather than a
rem cascade - the wrapper must not invent its own layout.
if not "%JK_HOME%"=="" (
  set "JK_HOME_CHECK=%JK_HOME%"
  if not "!JK_HOME_CHECK:~1,1!"==":" if not "!JK_HOME_CHECK:~0,2!"=="\\" (
    echo jk wrapper: JK_HOME must be an absolute path: %JK_HOME% 1>&2
    exit /b 1
  )
)
set "JK_HOME_DIR=%JK_HOME%"
if "%JK_HOME_DIR%"=="" set "JK_HOME_DIR=%USERPROFILE%\.jk"
set "BIN_DIR=%JK_HOME_DIR%\bin"
if "%JK_RELEASES_URL%"=="" set "JK_RELEASES_URL=https://jumpkick.build/releases"
set "RELEASE_RSA_MODULUS=2t27ZGJXSS9btuDOBzZN04fq8qcp9Ej/tNbmCpCo10Y6wjcQQY8sJfva4zqvhdZNZz/OEYvwePuZIkTVwmrCOU5jKHeHpP/9m9gYTx7DKr7o5koU/26UOi8kII2LfgU7J5iaYkVR3jUX54lGfXJbNJo2VY7aFRPojW+aCBAI7O0GbQ2h60HK12ltdIk3yomWbBpEYs7XTCScU+jAz2RKpznX966Ue9Obhw5r1/hDITBLbCSEChjsVXwx1343k17xXVgreO8X+gwrwBDw9MwSIpGg5LwJ7enLpW6ua8sfLRnjhyyeBJ+RMrc30KVHfPsgYuSvlF1iCcokM8JJBOK7XGKQSszUn2D/fPC5xjOmDT/4K6c0GnSmybSfzL6zUa5ShIkuiq4eix+WfJ7PGl77vqxQUT4/nURMsFVQJ+Qe9+7pegXbW9/oLZ01/+6AKuZaf7qyMN89p3nGJiOTgACOygY8YEc/Xl3Ue4zxgbu/dR+S3P8dATD2iBhGs6AHR8OP"
set "RELEASE_RSA_EXPONENT=AQAB"
set "DIR=%~dp0"

rem The lock's optional floor: minimum jk able to run this checkout.
set "FLOOR="
set "LINE="
if exist "%DIR%jk-lock.toml" (
  for /f "usebackq delims=" %%L in (`findstr /b "jk-min = " "%DIR%jk-lock.toml"`) do set "LINE=%%L"
  if defined LINE for /f tokens^=2^ delims^=^" %%V in ("!LINE!") do set "FLOOR=%%V"
)
if defined FLOOR call :require_version_token FLOOR "the jk-min floor in jk-lock.toml" || exit /b 1

set "BIN=%BIN_DIR%\jk.exe"
if not exist "%BIN%" goto bootstrap
set "INSTALLED="
if exist "%BIN_DIR%\VERSION" (
  for /f "usebackq delims=" %%V in (`type "%BIN_DIR%\VERSION"`) do set "INSTALLED=%%V"
)
rem No floor, or no record of what is installed: the installed binary enforces the lock itself.
if not defined FLOOR goto run
if not defined INSTALLED goto run
call :require_version_token INSTALLED "the installed VERSION file" || exit /b 1
call :version_ge INSTALLED FLOOR && goto run

:bootstrap
rem Bootstrap the latest published release. The pointer is one signed object - LATEST is
rem `version <v>`, `issued <unix-seconds>`, and `signature` over those two lines - verified
rem against the release key and read literally; the jk-min floor below refuses one rolled back.
rem Scratch directories live in JK_WRAPPER_* variables only. TMP and TEMP are Windows' own: every
rem powershell child inherits them and writes its temp files wherever they point, and this script
rem deletes its scratch directory while a child may still hold a file there. They are read, never set.
set "JK_WRAPPER_PTMP=%TEMP%\jk-wrapper-latest-%RANDOM%"
mkdir "!JK_WRAPPER_PTMP!"
powershell -NoProfile -Command "$d=$env:JK_WRAPPER_PTMP; $b=$env:JK_RELEASES_URL + '/latest/'; Invoke-WebRequest -UseBasicParsing ($b + 'LATEST') -OutFile (Join-Path $d 'LATEST')" || (
  echo jk wrapper: could not read !JK_RELEASES_URL!/latest/LATEST - offline, or JK_RELEASES_URL is wrong. 1>&2
  exit /b 1
)
set "VERSION="
powershell -NoProfile -Command "$b=[IO.File]::ReadAllBytes((Join-Path $env:JK_WRAPPER_PTMP 'LATEST')); foreach($x in $b){if($x -gt 127){exit 1}}; $t=[Text.Encoding]::ASCII.GetString($b); if(-not ($t -match '^version ([0-9]+\.[0-9]+\.[0-9]+(?:[-.][A-Za-z0-9]+)*)\nissued ([0-9]{1,18})\nsignature ([A-Za-z0-9+/]+={0,2})\n$')){exit 1}; $s=('version '+$Matches[1]+\"`n\"+'issued '+$Matches[2]+\"`n\"); [IO.File]::WriteAllBytes((Join-Path $env:JK_WRAPPER_PTMP 'LATEST.body'),[Text.Encoding]::ASCII.GetBytes($s)); [IO.File]::WriteAllText((Join-Path $env:JK_WRAPPER_PTMP 'LATEST.body.sig'),($Matches[3]+\"`n\"),[Text.Encoding]::ASCII)" || goto pointer_checked
call :verify_signature JK_WRAPPER_PTMP LATEST.body || goto pointer_checked
for /f "usebackq delims=" %%V in (`powershell -NoProfile -Command "$m=[IO.File]::ReadAllBytes((Join-Path $env:JK_WRAPPER_PTMP 'LATEST.body')); foreach($x in $m){if($x -gt 127){exit 1}}; $t=[Text.Encoding]::ASCII.GetString($m); if($t -notmatch '^version ([0-9]+\.[0-9]+\.[0-9]+(?:[-.][A-Za-z0-9]+)*)\nissued [0-9]{1,18}\n$'){exit 1}; Write-Output $Matches[1]"`) do set "VERSION=%%V"
:pointer_checked
rmdir /s /q "!JK_WRAPPER_PTMP!"
if not defined VERSION (
  echo jk wrapper: !JK_RELEASES_URL!/latest/LATEST did not verify as a signed release pointer - refusing. 1>&2
  exit /b 1
)
call :require_version_token VERSION "the latest release VERSION" || exit /b 1
if not defined FLOOR goto fetch
call :version_ge VERSION FLOOR && goto fetch
echo jk wrapper: this lock requires jk ^>= !FLOOR! but the latest release is !VERSION! - check JK_RELEASES_URL. 1>&2
exit /b 1

:fetch
echo jk wrapper: fetching jk !VERSION! ... 1>&2
set "FILE=jk-windows-x86_64-!VERSION!.zip"
set "JK_WRAPPER_TMP=%TEMP%\jk-wrapper-%RANDOM%"
mkdir "!JK_WRAPPER_TMP!"
set "JK_WRAPPER_FILE=!FILE!"
set "JK_WRAPPER_VERSION=!VERSION!"
powershell -NoProfile -Command "$b=$env:JK_RELEASES_URL + '/' + $env:JK_WRAPPER_VERSION + '/'; $d=$env:JK_WRAPPER_TMP; $f=$env:JK_WRAPPER_FILE; Invoke-WebRequest -UseBasicParsing ($b + $f) -OutFile (Join-Path $d $f); Invoke-WebRequest -UseBasicParsing ($b + 'SHA256SUMS') -OutFile (Join-Path $d 'SHA256SUMS'); Invoke-WebRequest -UseBasicParsing ($b + 'SHA256SUMS.sig') -OutFile (Join-Path $d 'SHA256SUMS.sig')" || exit /b 1
call :verify_signature JK_WRAPPER_TMP SHA256SUMS || goto release_refused
powershell -NoProfile -Command "$d=$env:JK_WRAPPER_TMP; $f=$env:JK_WRAPPER_FILE; $m=[IO.File]::ReadAllBytes((Join-Path $d 'SHA256SUMS')); try{$text=(New-Object -TypeName Text.UTF8Encoding -ArgumentList @($false,$true)).GetString($m)}catch{exit 1}; $seen=@{}; $want=$null; $count=0; $lines=$text.Split([char]10); for($i=0;$i -lt $lines.Length;$i++){$line=$lines[$i]; if($line.Length -eq 0 -and $i -eq $lines.Length-1){continue}; if($line -notmatch '^([0-9A-Fa-f]{64})  ([A-Za-z0-9][A-Za-z0-9._-]*)$'){exit 1}; $n=$Matches[2]; if($seen.ContainsKey($n)){exit 1}; $seen[$n]=$true; if($n -ceq $f){$count++;$want=$Matches[1].ToLowerInvariant()}}; if($count -ne 1){exit 1}; $got=(Get-FileHash -Algorithm SHA256 (Join-Path $d $f)).Hash.ToLowerInvariant(); if($got -cne $want){exit 1}" || goto release_refused
powershell -NoProfile -Command "Expand-Archive (Join-Path $env:JK_WRAPPER_TMP $env:JK_WRAPPER_FILE) $env:JK_WRAPPER_TMP" || exit /b 1
for /f "delims=" %%F in ('dir /b /s "!JK_WRAPPER_TMP!\*.exe"') do set "CLIENT=%%F"
mkdir "%BIN_DIR%" 2>nul
if exist "%BIN%" move /y "%BIN%" "%BIN%.old" >nul 2>&1
copy /y "!CLIENT!" "%BIN%" >nul
rem Redirect-first: `echo 0.13.1> file` would read the trailing digit as a handle number.
>"%BIN_DIR%\VERSION" echo(!VERSION!
del /f /q "%BIN%.old" >nul 2>&1
rmdir /s /q "!JK_WRAPPER_TMP!"

:run
"%BIN%" %*
exit /b %ERRORLEVEL%

rem A release whose SHA256SUMS signature or artifact entry does not verify installs nothing.
:release_refused
echo jk wrapper: signed release verification failed for !FILE! - refusing. 1>&2
exit /b 1

rem Exit 0 when the release key's RSA/SHA-256 signature in <dir>\%2.sig covers the exact bytes
rem of <dir>\%2, where %1 names the variable holding <dir>. Every remote input that steers the
rem bootstrap - the latest-release pointer and the version directory's SHA256SUMS - passes
rem through here before anything it names is trusted; the paths reach PowerShell as environment
rem variables like every other value.
:verify_signature
set "JK_WRAPPER_SIGNED=!%~1!\%~2"
set "JK_WRAPPER_SIG=!%~1!\%~2.sig"
powershell -NoProfile -Command "$m=[IO.File]::ReadAllBytes($env:JK_WRAPPER_SIGNED); $st=[Text.Encoding]::ASCII.GetString([IO.File]::ReadAllBytes($env:JK_WRAPPER_SIG)); if($st -notmatch '^[A-Za-z0-9+/]+={0,2}\r?\n?$'){exit 1}; try{$sig=[Convert]::FromBase64String($st.TrimEnd([char[]]\"`r`n\"))}catch{exit 1}; if($sig.Length -ne 384){exit 1}; $p=New-Object Security.Cryptography.RSAParameters; $p.Modulus=[Convert]::FromBase64String($env:RELEASE_RSA_MODULUS); $p.Exponent=[Convert]::FromBase64String($env:RELEASE_RSA_EXPONENT); $r=[Security.Cryptography.RSA]::Create(); $r.ImportParameters($p); if(-not $r.VerifyData($m,$sig,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)){exit 1}"
exit /b %ERRORLEVEL%

rem Refuse anything but a version token in the variable named by %1 (%2 says what it is).
rem The value is checked through a file, not a pipe: the halves of a pipe run in child shells
rem where delayed expansion is off, and !VAR! is the only expansion that leaves & | < > " inert.
:require_version_token
set "TOKEN_FILE=%TEMP%\jk-wrapper-token-%RANDOM%.txt"
>"!TOKEN_FILE!" echo(!%~1!
findstr /r /c:"^[0-9A-Za-z._-][0-9A-Za-z._-]*$" "!TOKEN_FILE!" >nul
set "TOKEN_OK=!ERRORLEVEL!"
del /f /q "!TOKEN_FILE!" >nul 2>&1
if "!TOKEN_OK!"=="0" exit /b 0
echo jk wrapper: %~2 is not a version: !%~1! - refusing. 1>&2
exit /b 1

rem Exit 0 when the version in the variable named by %1 is >= the one named by %2; pre-release
rem suffixes compare by their numeric core. Both reach PowerShell as environment variables.
:version_ge
set "JK_WRAPPER_A=!%~1!"
set "JK_WRAPPER_B=!%~2!"
powershell -NoProfile -Command "if ([version]($env:JK_WRAPPER_A -replace '-.*','') -ge [version]($env:JK_WRAPPER_B -replace '-.*','')) { exit 0 } else { exit 1 }"
exit /b %ERRORLEVEL%
