@echo off
rem JumpKick bootstrap wrapper - generated by `jk wrapper`; do not edit (regenerate instead).
rem Bootstraps CURRENT jk, never a historical one: installed jk satisfying the lock's
rem optional jk-min floor, else a jk on PATH, else the latest published release - its signed
rem latest/LATEST pointer, then the signed SHA256SUMS, both checked by the one :verify_signature
rem subroutine. The native jk.exe when those sums list one for this architecture, else (or with
rem JK_CLIENT=jvm) the JVM client on a JDK 25+ the user provides. One wrapper downloads at a
rem time per JK_HOME; the others wait on its lock and then run what it installed.
rem The lock pins inputs, not the operator.
rem
rem Nothing read from the network or from the repository is ever spliced into command text.
rem The VERSION the release host answers, the jk-min floor in jk-lock.toml and the installed
rem VERSION file must each be a version token (letters, digits, . _ -) before they are used,
rem and they reach PowerShell only through environment variables - a hostile value cannot end
rem a quoted string or a command. Flow control is goto/call, not ( ) blocks: cmd expands
rem %VAR% inside a block when it parses the block, so a variable set inside one is stale there.
setlocal enabledelayedexpansion

rem Bin dir resolution mirrors install.ps1 / JkDirs, which is now one answer rather than a
rem cascade - the wrapper must not invent its own layout.
if not "%JK_HOME%"=="" (
  set "JK_HOME_CHECK=%JK_HOME%"
  if not "!JK_HOME_CHECK:~1,1!"==":" if not "!JK_HOME_CHECK:~0,2!"=="\\" (
    echo jk wrapper: JK_HOME must be an absolute path: %JK_HOME% 1>&2
    exit /b 1
  )
)
set "JK_WRAPPER_HOME=%JK_HOME%"
if "%JK_WRAPPER_HOME%"=="" set "JK_WRAPPER_HOME=%USERPROFILE%\.jk"
set "BIN_DIR=%JK_WRAPPER_HOME%\bin"
if "%JK_RELEASES_URL%"=="" set "JK_RELEASES_URL=https://jumpkick.build/releases"
set "RELEASE_RSA_MODULUS=2t27ZGJXSS9btuDOBzZN04fq8qcp9Ej/tNbmCpCo10Y6wjcQQY8sJfva4zqvhdZNZz/OEYvwePuZIkTVwmrCOU5jKHeHpP/9m9gYTx7DKr7o5koU/26UOi8kII2LfgU7J5iaYkVR3jUX54lGfXJbNJo2VY7aFRPojW+aCBAI7O0GbQ2h60HK12ltdIk3yomWbBpEYs7XTCScU+jAz2RKpznX966Ue9Obhw5r1/hDITBLbCSEChjsVXwx1343k17xXVgreO8X+gwrwBDw9MwSIpGg5LwJ7enLpW6ua8sfLRnjhyyeBJ+RMrc30KVHfPsgYuSvlF1iCcokM8JJBOK7XGKQSszUn2D/fPC5xjOmDT/4K6c0GnSmybSfzL6zUa5ShIkuiq4eix+WfJ7PGl77vqxQUT4/nURMsFVQJ+Qe9+7pegXbW9/oLZ01/+6AKuZaf7qyMN89p3nGJiOTgACOygY8YEc/Xl3Ue4zxgbu/dR+S3P8dATD2iBhGs6AHR8OP"
set "RELEASE_RSA_EXPONENT=AQAB"
set "SELF=%~f0"
set "BIN=%BIN_DIR%\jk.exe"

rem The lock's optional floor: minimum jk able to run this checkout. The nearest jk-lock.toml at
rem or above this script wins, as for ./jk: a wrapper in a module directory reads the workspace lock.
set "FLOOR="
set "LOCK_DIR=%~dp0"
set /a LOCK_DEPTH=0
:find_lock
if exist "!LOCK_DIR!jk-lock.toml" goto read_floor
for %%P in ("!LOCK_DIR!.") do set "LOCK_PARENT=%%~dpP"
if /i "!LOCK_PARENT!"=="!LOCK_DIR!" goto floor_read
set "LOCK_DIR=!LOCK_PARENT!"
set /a LOCK_DEPTH+=1
if !LOCK_DEPTH! lss 24 goto find_lock
goto floor_read
:read_floor
set "LINE="
for /f "usebackq delims=" %%L in (`findstr /b /c:"jk-min = " "!LOCK_DIR!jk-lock.toml"`) do if not defined LINE set "LINE=%%L"
if defined LINE for /f tokens^=2^ delims^=^" %%V in ("!LINE!") do set "FLOOR=%%V"
:floor_read
if defined FLOOR call :require_version_token FLOOR "the jk-min floor in jk-lock.toml" || exit /b 1

call :installed_client && goto run

rem A jk already on PATH (a JVM client, or a home this JK_HOME did not name) beats a download; a
rem current jk enforces the lock floor itself. Never the install the floor check just rejected, and
rem never this wrapper again: cmd and `where` search the current directory first, so `jk` there
rem answers with this wrapper, and a copy of it may sit in a PATH directory.
for %%D in ("%BIN_DIR%") do set "BIN_DIR_FULL=%%~fD\"
set "PATH_JK="
for /f "delims=" %%P in ('where jk 2^>nul') do if not defined PATH_JK (
  set "CANDIDATE=%%~fP"
  call :path_candidate
)
if not defined PATH_JK goto bootstrap
set "RUN=!PATH_JK!"
goto run

:bootstrap
rem Which client: JK_CLIENT as install.ps1 reads it; unset, the native client when the release
rem lists one for this host, else the JVM client.
set "CLIENT_KIND=%JK_CLIENT%"
if not defined CLIENT_KIND goto take_lock
if /i "!CLIENT_KIND!"=="native" goto take_lock
if /i "!CLIENT_KIND!"=="jvm" goto take_lock
echo jk wrapper: JK_CLIENT must be native or jvm, not !CLIENT_KIND! - refusing. 1>&2
exit /b 1

rem One download per JK_HOME: mkdir is atomic, so the wrapper that creates the lock directory
rem installs and every other one waits. A lock whose owner is gone, or older than ten minutes,
rem is broken; losing that race costs a second download, never a broken install. The scratch
rem directories live inside the lock, so only its holder writes them and releasing it clears them.
:take_lock
mkdir "%BIN_DIR%" 2>nul
set "JK_WRAPPER_LOCK=%BIN_DIR%\.jk-wrapper.lock"
set /a LOCK_WAITED=0
:acquire_lock
mkdir "!JK_WRAPPER_LOCK!" 2>nul && goto lock_acquired
if !LOCK_WAITED! equ 0 echo jk wrapper: another jk wrapper is installing jk; waiting for it ... 1>&2
set /a LOCK_CHECK=LOCK_WAITED %% 5
if !LOCK_CHECK! equ 0 call :break_stale_lock
ping -n 2 127.0.0.1 >nul
set /a LOCK_WAITED+=1
goto acquire_lock
:lock_acquired
set "JK_WRAPPER_LOCK_HELD=1"
powershell -NoProfile -Command "$p=(Get-CimInstance Win32_Process -Filter ('ProcessId=' + $PID)).ParentProcessId; $c=Get-Process -Id $p; [IO.File]::WriteAllText((Join-Path $env:JK_WRAPPER_LOCK 'owner'), ([string]$p + ' ' + $c.StartTime.ToUniversalTime().Ticks))" >nul 2>&1
rem The wrapper this one waited on may have installed a client that now satisfies the floor.
call :installed_client && goto unlock_and_run

rem Bootstrap the latest published release. The pointer is one signed object - LATEST is
rem `version <v>`, `issued <unix-seconds>`, and `signature` over those two lines - verified
rem against the release key and read literally; the jk-min floor below refuses one rolled back.
rem TMP and TEMP are Windows' own: every powershell child inherits them, so they are never set.
set "JK_WRAPPER_PTMP=!JK_WRAPPER_LOCK!\latest"
mkdir "!JK_WRAPPER_PTMP!"
powershell -NoProfile -Command "$d=$env:JK_WRAPPER_PTMP; $b=$env:JK_RELEASES_URL + '/latest/'; Invoke-WebRequest -UseBasicParsing ($b + 'LATEST') -OutFile (Join-Path $d 'LATEST')" || goto latest_unreadable
set "VERSION="
powershell -NoProfile -Command "$b=[IO.File]::ReadAllBytes((Join-Path $env:JK_WRAPPER_PTMP 'LATEST')); foreach($x in $b){if($x -gt 127){exit 1}}; $t=[Text.Encoding]::ASCII.GetString($b); if(-not ($t -match '^version ([0-9]+\.[0-9]+\.[0-9]+(?:[-.][A-Za-z0-9]+)*)\nissued ([0-9]{1,18})\nsignature ([A-Za-z0-9+/]+={0,2})\n$')){exit 1}; $s=('version '+$Matches[1]+\"`n\"+'issued '+$Matches[2]+\"`n\"); [IO.File]::WriteAllBytes((Join-Path $env:JK_WRAPPER_PTMP 'LATEST.body'),[Text.Encoding]::ASCII.GetBytes($s)); [IO.File]::WriteAllText((Join-Path $env:JK_WRAPPER_PTMP 'LATEST.body.sig'),($Matches[3]+\"`n\"),[Text.Encoding]::ASCII)" || goto pointer_checked
call :verify_signature JK_WRAPPER_PTMP LATEST.body || goto pointer_checked
for /f "usebackq delims=" %%V in (`powershell -NoProfile -Command "$m=[IO.File]::ReadAllBytes((Join-Path $env:JK_WRAPPER_PTMP 'LATEST.body')); foreach($x in $m){if($x -gt 127){exit 1}}; $t=[Text.Encoding]::ASCII.GetString($m); if($t -notmatch '^version ([0-9]+\.[0-9]+\.[0-9]+(?:[-.][A-Za-z0-9]+)*)\nissued [0-9]{1,18}\n$'){exit 1}; Write-Output $Matches[1]"`) do set "VERSION=%%V"
:pointer_checked
if not defined VERSION goto pointer_refused
call :require_version_token VERSION "the latest release VERSION" || goto fail
if not defined FLOOR goto fetch
call :version_ge VERSION FLOOR && goto fetch
echo jk wrapper: this lock requires jk ^>= !FLOOR! but the latest release is !VERSION! - check JK_RELEASES_URL. 1>&2
goto fail

:fetch
set "JK_WRAPPER_TMP=!JK_WRAPPER_LOCK!\fetch"
mkdir "!JK_WRAPPER_TMP!"
set "JK_WRAPPER_VERSION=!VERSION!"
echo jk wrapper: fetching jk !VERSION! ... 1>&2
powershell -NoProfile -Command "$ProgressPreference='SilentlyContinue'; $b=$env:JK_RELEASES_URL + '/' + $env:JK_WRAPPER_VERSION + '/'; $d=$env:JK_WRAPPER_TMP; Invoke-WebRequest -UseBasicParsing ($b + 'SHA256SUMS') -OutFile (Join-Path $d 'SHA256SUMS'); Invoke-WebRequest -UseBasicParsing ($b + 'SHA256SUMS.sig') -OutFile (Join-Path $d 'SHA256SUMS.sig')" || goto sums_unreadable
call :verify_signature JK_WRAPPER_TMP SHA256SUMS || goto sums_refused
rem This host as a release names its native client, jk-windows-<arch>-<version>.zip; the signed
rem sums say whether this release has one. The full sums check runs on the file downloaded below.
set "HOST_ARCH="
set "LISTED=0"
for /f "usebackq tokens=1,2" %%A in (`powershell -NoProfile -Command "$a=$env:PROCESSOR_ARCHITEW6432; if(-not $a){$a=$env:PROCESSOR_ARCHITECTURE}; if($a -eq 'AMD64'){$a='x86_64'}elseif($a -eq 'ARM64'){$a='aarch64'}else{$a=([string]$a).ToLowerInvariant() -replace '[^a-z0-9_]','_'}; if(-not $a){$a='unknown'}; $n='jk-windows-'+$a+'-'+$env:JK_WRAPPER_VERSION+'.zip'; $hit=0; foreach($l in [IO.File]::ReadAllText((Join-Path $env:JK_WRAPPER_TMP 'SHA256SUMS')).Split([char]10)){if($l.Length -gt 66 -and $l.Substring(64,2) -eq '  ' -and $l.Substring(66) -ceq $n){$hit=1}}; Write-Output ($a+' '+$hit)"`) do (
  set "HOST_ARCH=%%A"
  set "LISTED=%%B"
)
if not defined HOST_ARCH goto sums_refused
if /i "!CLIENT_KIND!"=="jvm" goto fetch_jvm
if "!LISTED!"=="1" goto fetch_native
if /i "!CLIENT_KIND!"=="native" goto no_native
echo jk wrapper: jk !VERSION! publishes no native windows-!HOST_ARCH! client; installing the JVM client. 1>&2
set "CLIENT_KIND=jvm"
goto fetch_jvm
:fetch_native
set "CLIENT_KIND=native"
set "FILE=jk-windows-!HOST_ARCH!-!VERSION!.zip"
goto download
:fetch_jvm
set "FILE=jk-!VERSION!.jar"
rem The JVM client runs on a JDK 25 or newer (with javac: the engine compiles on it) that the user
rem provides: JK_JAVA_HOME, else JAVA_HOME, else java on PATH - the order install.ps1 reads.
powershell -NoProfile -Command "$j=$null; if($env:JK_JAVA_HOME){$j=Join-Path $env:JK_JAVA_HOME 'bin\java.exe'} elseif($env:JAVA_HOME){$j=Join-Path $env:JAVA_HOME 'bin\java.exe'} else {$c=@(Get-Command java.exe -CommandType Application -ErrorAction SilentlyContinue); if($c.Count -gt 0){$j=$c[0].Source}}; if(-not $j -or -not (Test-Path -LiteralPath $j -PathType Leaf)){exit 1}; $o=@(& $j -XshowSettings:properties -version 2>&1 | ForEach-Object {[string]$_}); $v=@($o -match '^\S+ version .(\d+)'); if($v.Count -eq 0 -or -not ($v[0] -match 'version .(\d+)')){exit 1}; if([int]$Matches[1] -lt 25){exit 1}; $h=@($o -match '^\s*java\.home = '); if($h.Count -gt 0 -and -not (Test-Path -LiteralPath (Join-Path ($h[0] -replace '^\s*java\.home = ','').Trim() 'bin\javac.exe'))){exit 1}; [IO.File]::WriteAllText((Join-Path $env:JK_WRAPPER_TMP 'java.txt'),$j)" || goto no_jdk
for /f "usebackq delims=" %%J in ("!JK_WRAPPER_TMP!\java.txt") do set "JK_WRAPPER_JAVA=%%J"

:download
set "JK_WRAPPER_FILE=!FILE!"
powershell -NoProfile -Command "$ProgressPreference='SilentlyContinue'; $b=$env:JK_RELEASES_URL + '/' + $env:JK_WRAPPER_VERSION + '/'; $f=$env:JK_WRAPPER_FILE; Invoke-WebRequest -UseBasicParsing ($b + $f) -OutFile (Join-Path $env:JK_WRAPPER_TMP $f)" || goto release_unreadable
powershell -NoProfile -Command "$d=$env:JK_WRAPPER_TMP; $f=$env:JK_WRAPPER_FILE; $m=[IO.File]::ReadAllBytes((Join-Path $d 'SHA256SUMS')); try{$text=(New-Object -TypeName Text.UTF8Encoding -ArgumentList @($false,$true)).GetString($m)}catch{exit 1}; $seen=@{}; $want=$null; $count=0; $lines=$text.Split([char]10); for($i=0;$i -lt $lines.Length;$i++){$line=$lines[$i]; if($line.Length -eq 0 -and $i -eq $lines.Length-1){continue}; if($line -notmatch '^([0-9A-Fa-f]{64})  ([A-Za-z0-9][A-Za-z0-9._-]*)$'){exit 1}; $n=$Matches[2]; if($seen.ContainsKey($n)){exit 1}; $seen[$n]=$true; if($n -ceq $f){$count++;$want=$Matches[1].ToLowerInvariant()}}; if($count -ne 1){exit 1}; $got=(Get-FileHash -Algorithm SHA256 (Join-Path $d $f)).Hash.ToLowerInvariant(); if($got -cne $want){exit 1}" || goto release_refused
if /i "!CLIENT_KIND!"=="jvm" goto install_jvm

powershell -NoProfile -Command "Expand-Archive (Join-Path $env:JK_WRAPPER_TMP $env:JK_WRAPPER_FILE) $env:JK_WRAPPER_TMP" || goto fail
for /f "delims=" %%F in ('dir /b /s "!JK_WRAPPER_TMP!\*.exe"') do set "CLIENT=%%F"
if exist "%BIN%" move /y "%BIN%" "%BIN%.old" >nul 2>&1
copy /y "!CLIENT!" "%BIN%" >nul
del /f /q "%BIN%.old" >nul 2>&1
set "RUN=%BIN%"
goto installed_new

rem The jar goes under <home>\lib\jk, as JvmClientInstall lays it out; the client itself then
rem writes bin\jk.bat over the JDK checked above and parks a leftover jk.exe. It fetches its own
rem engine on first use, as a downloaded native client does.
:install_jvm
powershell -NoProfile -Command "$lib=Join-Path $env:JK_WRAPPER_HOME 'lib\jk'; $f=$env:JK_WRAPPER_FILE; $src=Join-Path $env:JK_WRAPPER_TMP $f; $dest=Join-Path $lib $f; [void](New-Item -ItemType Directory -Force -Path $lib); try{[IO.File]::Copy($src,$dest,$true)}catch{if((Get-FileHash -LiteralPath $dest).Hash -ne (Get-FileHash -LiteralPath $src).Hash){exit 1}}; Get-ChildItem -LiteralPath $lib -Filter 'jk-*.jar' -File -ErrorAction SilentlyContinue | Where-Object {$_.FullName -ne $dest} | ForEach-Object {try{Remove-Item -LiteralPath $_.FullName -Force}catch{}}" || goto fail
"!JK_WRAPPER_JAVA!" --enable-native-access=ALL-UNNAMED -jar "!JK_WRAPPER_HOME!\lib\jk\!FILE!" self write-launcher >nul || goto launcher_failed
set "RUN=%BIN_DIR%\jk.bat"

:installed_new
rem Redirect-first: `echo 0.13.1> file` would read the trailing digit as a handle number.
>"%BIN_DIR%\VERSION" echo(!VERSION!
:unlock_and_run
if defined JK_WRAPPER_LOCK_HELD rmdir /s /q "!JK_WRAPPER_LOCK!" 2>nul

rem A .bat client runs in place of this script, as exec does in ./jk.
:run
"%RUN%" %*
exit /b %ERRORLEVEL%

:latest_unreadable
echo jk wrapper: could not read !JK_RELEASES_URL!/latest/LATEST - offline, or JK_RELEASES_URL is wrong. 1>&2
goto fail

:pointer_refused
echo jk wrapper: !JK_RELEASES_URL!/latest/LATEST did not verify as a signed release pointer - refusing. 1>&2
goto fail

:sums_unreadable
echo jk wrapper: could not read SHA256SUMS from !JK_RELEASES_URL!/!VERSION! - the release host does not serve jk !VERSION!, or JK_RELEASES_URL is wrong. 1>&2
goto fail

:sums_refused
echo jk wrapper: the jk !VERSION! SHA256SUMS did not verify against the release key - refusing. 1>&2
goto fail

:no_native
echo jk wrapper: jk !VERSION! publishes no native windows-!HOST_ARCH! client; unset JK_CLIENT to use the JVM client. 1>&2
goto fail

:release_unreadable
echo jk wrapper: could not read !FILE! from !JK_RELEASES_URL!/!VERSION! - the release host does not serve it, or JK_RELEASES_URL is wrong. 1>&2
goto fail

rem A release whose SHA256SUMS signature or artifact entry does not verify installs nothing.
:release_refused
echo jk wrapper: signed release verification failed for !FILE! - refusing. 1>&2
goto fail

:no_jdk
echo jk wrapper: the jk JVM client needs a JDK 25 or newer - set JAVA_HOME or JK_JAVA_HOME to one and re-run. 1>&2
goto fail

:launcher_failed
echo jk wrapper: !JK_WRAPPER_JAVA! could not write the JVM client's launcher into %BIN_DIR%. 1>&2
goto fail

:fail
if defined JK_WRAPPER_LOCK_HELD rmdir /s /q "!JK_WRAPPER_LOCK!" 2>nul
exit /b 1

rem Exit 0 with RUN set when the installed client may run: it exists, and there is no floor, no
rem VERSION record to compare (the client enforces the lock itself), or a VERSION that meets it.
rem The installed client is the native jk.exe or the JVM client's jk.bat launcher.
:installed_client
set "RUN=%BIN%"
if exist "!RUN!" goto installed_version
set "RUN=%BIN_DIR%\jk.bat"
if not exist "!RUN!" exit /b 1
call :is_wrapper RUN && exit /b 1
:installed_version
set "INSTALLED="
if exist "%BIN_DIR%\VERSION" (
  for /f "usebackq delims=" %%V in (`type "%BIN_DIR%\VERSION"`) do set "INSTALLED=%%V"
)
if not defined FLOOR exit /b 0
if not defined INSTALLED exit /b 0
rem A VERSION file that is not a version proves nothing about the floor; a download replaces it.
call :is_version_token INSTALLED || exit /b 1
call :version_ge INSTALLED FLOOR
exit /b %ERRORLEVEL%

rem Remove the lock when its owner process (pid and start time, written by its holder) is gone,
rem or it is older than ten minutes. A lock with no owner record yet is being taken.
:break_stale_lock
powershell -NoProfile -Command "try{$l=$env:JK_WRAPPER_LOCK; if(-not (Test-Path -LiteralPath $l)){exit 0}; $stale=((Get-Date) - (Get-Item -LiteralPath $l).CreationTime).TotalMinutes -gt 10; $f=Join-Path $l 'owner'; if(-not $stale -and (Test-Path -LiteralPath $f)){$t=([IO.File]::ReadAllText($f)).Trim().Split(' '); if($t.Length -eq 2){$p=Get-Process -Id ([int]$t[0]) -ErrorAction SilentlyContinue; $stale=($null -eq $p) -or ($p.StartTime.ToUniversalTime().Ticks -ne [long]$t[1])}}; if($stale){$s=$l + '.stale-' + [guid]::NewGuid().ToString('N'); [IO.Directory]::Move($l,$s); Remove-Item -LiteralPath $s -Recurse -Force}}catch{}; exit 0" >nul 2>&1
exit /b 0

rem Exit 0 when the release key's RSA/SHA-256 signature in <dir>\%2.sig covers the exact bytes
rem of <dir>\%2, where %1 names the variable holding <dir>. Every remote input that steers the
rem bootstrap - the latest-release pointer and the version directory's SHA256SUMS - passes
rem through here before anything it names is trusted; the paths reach PowerShell as environment
rem variables like every other value.
:verify_signature
set "JK_WRAPPER_SIGNED=!%~1!\%~2"
set "JK_WRAPPER_SIG=!%~1!\%~2.sig"
powershell -NoProfile -Command "$m=[IO.File]::ReadAllBytes($env:JK_WRAPPER_SIGNED); $st=[Text.Encoding]::ASCII.GetString([IO.File]::ReadAllBytes($env:JK_WRAPPER_SIG)); if($st -notmatch '^[A-Za-z0-9+/]+={0,2}\r?\n?$'){exit 1}; try{$sig=[Convert]::FromBase64String($st.TrimEnd([char[]]\"`r`n\"))}catch{exit 1}; if($sig.Length -ne 384){exit 1}; $p=New-Object Security.Cryptography.RSAParameters; $p.Modulus=[Convert]::FromBase64String($env:RELEASE_RSA_MODULUS); $p.Exponent=[Convert]::FromBase64String($env:RELEASE_RSA_EXPONENT); $r=[Security.Cryptography.RSA]::Create(); $r.ImportParameters($p); if(-not $r.VerifyData($m,$sig,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)){exit 1}"
exit /b %ERRORLEVEL%

rem Take CANDIDATE, one `where jk` answer, as PATH_JK unless it is in the rejected install's
rem directory, is this script, or is a copy of this wrapper.
:path_candidate
for %%C in ("!CANDIDATE!") do (
  if /i "%%~dpC"=="!BIN_DIR_FULL!" exit /b 0
  if /i "%%~fC"=="!SELF!" exit /b 0
  if /i not "%%~xC"==".exe" call :is_wrapper CANDIDATE && exit /b 0
)
set "PATH_JK=!CANDIDATE!"
exit /b 0

rem Exit 0 when the file named by the variable %1 is a copy of this wrapper (any generation): its
rem banner opens a line. Only scripts are checked - jk.exe embeds this template as a resource.
:is_wrapper
findstr /b /c:"rem JumpKick bootstrap wrapper" "!%~1!" >nul 2>&1
exit /b %ERRORLEVEL%

rem Refuse anything but a version token in the variable named by %1 (%2 says what it is).
:require_version_token
call :is_version_token %1 && exit /b 0
echo jk wrapper: %~2 is not a version: !%~1! - refusing. 1>&2
exit /b 1

rem Exit 0 when the variable named by %1 holds a version token (letters, digits, . _ -). `set`
rem prints the value raw into the pipe, so no expansion ever parses it; a redirect on that `set`
rem would leave a trailing space on the name it looks up.
:is_version_token
set "JK_WRAPPER_TOKEN=!%~1!"
if not defined JK_WRAPPER_TOKEN exit /b 1
set JK_WRAPPER_TOKEN | findstr /r /x /c:"JK_WRAPPER_TOKEN=[0-9A-Za-z._-][0-9A-Za-z._-]*" >nul
exit /b %ERRORLEVEL%

rem Exit 0 when the version in the variable named by %1 is >= the one named by %2; pre-release
rem suffixes compare by their numeric core. Both reach PowerShell as environment variables.
:version_ge
set "JK_WRAPPER_A=!%~1!"
set "JK_WRAPPER_B=!%~2!"
powershell -NoProfile -Command "if ([version]($env:JK_WRAPPER_A -replace '-.*','') -ge [version]($env:JK_WRAPPER_B -replace '-.*','')) { exit 0 } else { exit 1 }"
exit /b %ERRORLEVEL%
