#!/bin/sh
# JumpKick bootstrap wrapper — generated by `jk wrapper`. Regenerate rather than editing.
#
# Bootstraps CURRENT jk, never a historical one: uses the locally installed jk that
# satisfies the lock's optional `jk-min` floor, else fetches the latest published release
# (its signed latest/LATEST pointer, then the signed release SHA256SUMS) and execs it. The lock
# pins inputs, not the operator — there is no version pin here and none in jk-lock.toml.
set -eu

# Where jk lives / gets installed — the SAME answer as install.sh and JkDirs, which is now
# one expression rather than a cascade. The wrapper must never invent its own layout: an
# earlier one cached into a directory the resolver did not name, shadowing the real install
# forever, so `jk self update` (which replaces the bin-dir binary) never reached its users.
case "${JK_HOME:-/}" in
  /*) ;;
  *) echo "jk wrapper: JK_HOME must be an absolute path: $JK_HOME" >&2; exit 1 ;;
esac
BIN_DIR="${JK_HOME:-$HOME/.jk}/bin"
RELEASES="${JK_RELEASES_URL:-https://jumpkick.build/releases}"
RELEASE_RSA_SPKI="MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA2t27ZGJXSS9btuDOBzZN04fq8qcp9Ej/tNbmCpCo10Y6wjcQQY8sJfva4zqvhdZNZz/OEYvwePuZIkTVwmrCOU5jKHeHpP/9m9gYTx7DKr7o5koU/26UOi8kII2LfgU7J5iaYkVR3jUX54lGfXJbNJo2VY7aFRPojW+aCBAI7O0GbQ2h60HK12ltdIk3yomWbBpEYs7XTCScU+jAz2RKpznX966Ue9Obhw5r1/hDITBLbCSEChjsVXwx1343k17xXVgreO8X+gwrwBDw9MwSIpGg5LwJ7enLpW6ua8sfLRnjhyyeBJ+RMrc30KVHfPsgYuSvlF1iCcokM8JJBOK7XGKQSszUn2D/fPC5xjOmDT/4K6c0GnSmybSfzL6zUa5ShIkuiq4eix+WfJ7PGl77vqxQUT4/nURMsFVQJ+Qe9+7pegXbW9/oLZ01/+6AKuZaf7qyMN89p3nGJiOTgACOygY8YEc/Xl3Ue4zxgbu/dR+S3P8dATD2iBhGs6AHR8OPAgMBAAE="
case "$0" in */*) DIR="${0%/*}" ;; *) DIR="." ;; esac

# The lock's optional floor: minimum jk able to run this checkout.
FLOOR=""
SEARCH="$DIR"
I=0
while [ "$I" -lt 24 ]; do
  if [ -f "$SEARCH/jk-lock.toml" ]; then
    while IFS= read -r LINE || [ -n "$LINE" ]; do
      case "$LINE" in
        "jk-min = "*)
          FLOOR="${LINE#*\"}"; FLOOR="${FLOOR%%\"*}"
          break
          ;;
      esac
    done < "$SEARCH/jk-lock.toml"
    break
  fi
  case "$SEARCH" in /) break ;; esac
  SEARCH="$SEARCH/.."
  I=$((I+1))
done

# True when $1 >= $2 as dotted versions (pre-release suffixes compare by their numeric core).
ver_ge() {
  A="${1%%-*}"; B="${2%%-*}"
  HI="$(printf '%s\n%s\n' "$A" "$B" | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)"
  [ "$HI" = "$A" ]
}

BIN="$BIN_DIR/jk"
if [ -x "$BIN" ]; then
  INSTALLED=""
  if [ -f "$BIN_DIR/VERSION" ]; then
    INSTALLED="$(tr -d '[:space:]' < "$BIN_DIR/VERSION")"
  fi
  if [ -z "$FLOOR" ] || [ -z "$INSTALLED" ] || ver_ge "$INSTALLED" "$FLOOR"; then
    exec "$BIN" "$@"
  fi
fi
# Canonical path of $1: symlinks resolved, relative made absolute. realpath and readlink -f
# are not on every host (older macOS has neither), so the fallback resolves the directory
# with pwd -P and keeps the leaf.
real_path() {
  if command -v realpath >/dev/null 2>&1 && realpath "$1" 2>/dev/null; then
    return 0
  fi
  if readlink -f "$1" >/dev/null 2>&1; then
    readlink -f "$1"
    return 0
  fi
  case "$1" in */*) RP_DIR="${1%/*}"; RP_LEAF="${1##*/}" ;; *) RP_DIR="."; RP_LEAF="$1" ;; esac
  if RP_DIR="$(cd "$RP_DIR" 2>/dev/null && pwd -P)"; then
    printf '%s/%s\n' "$RP_DIR" "$RP_LEAF"
  else
    printf '%s\n' "$1"
  fi
}

# True when $1 is a copy of this wrapper (any generation): the first lines carry its banner.
is_wrapper() {
  head -n 3 "$1" 2>/dev/null | grep -q "JumpKick bootstrap wrapper"
}

# A jk already on PATH (a distro package, or a home this JK_HOME did not name) beats a
# bootstrap download; a current jk enforces the lock floor itself. Never re-exec the very
# binary the floor check above just rejected, and never exec this wrapper again: with `.`
# on PATH, or the committed wrapper symlinked or copied into a PATH directory, `command -v jk`
# answers with the wrapper itself, and exec-ing it is a loop that never reaches the download.
if command -v jk >/dev/null 2>&1; then
  PATH_JK="$(command -v jk)"
  case "$PATH_JK" in
    /*|./*|../*) ;;
    *) PATH_JK="" ;;
  esac
  if [ -n "$PATH_JK" ] && [ "$PATH_JK" != "$BIN" ] &&
    [ "$(real_path "$PATH_JK")" != "$(real_path "$0")" ] && ! is_wrapper "$PATH_JK"; then
    exec "$PATH_JK" "$@"
  fi
fi

# Verify the release key's RSA/SHA-256 signature in $2 over the exact bytes of $1, or exit
# naming $3. Every remote input that steers the bootstrap — the latest-release pointer and the
# version directory's SHA256SUMS — passes through here before anything it names is trusted.
verify_release_signature() {
  if ! command -v openssl >/dev/null 2>&1; then
    echo "jk wrapper: OpenSSL is required to authenticate the release." >&2
    exit 1
  fi
  [ -f "$TMP/release-public.pem" ] || {
    printf '%s\n' "-----BEGIN PUBLIC KEY-----"
    printf '%s' "$RELEASE_RSA_SPKI" | fold -w 64
    printf '\n'
    printf '%s\n' "-----END PUBLIC KEY-----"
  } >"$TMP/release-public.pem"
  VS_TEXT="$(tr -d '\r' <"$2")"
  VS_LINES="$(wc -l <"$2" | tr -d '[:space:]')"
  if { [ "$VS_LINES" != "0" ] && [ "$VS_LINES" != "1" ]; } ||
    [ "${#VS_TEXT}" -ne 512 ] ||
    ! printf '%s' "$VS_TEXT" | LC_ALL=C grep -Eq '^[A-Za-z0-9+/]+={0,2}$'; then
    echo "jk wrapper: $3 signature is malformed — refusing." >&2
    exit 1
  fi
  printf '%s' "$VS_TEXT" | openssl base64 -d -A >"$2.bin" 2>/dev/null || {
    echo "jk wrapper: $3 signature is not valid base64 — refusing." >&2
    exit 1
  }
  [ "$(wc -c <"$2.bin" | tr -d '[:space:]')" = "384" ] || {
    echo "jk wrapper: $3 signature has the wrong RSA-3072 length — refusing." >&2
    exit 1
  }
  openssl dgst -sha256 -verify "$TMP/release-public.pem" -signature "$2.bin" "$1" >/dev/null 2>&1 || {
    echo "jk wrapper: $3 signature verification failed — refusing." >&2
    exit 1
  }
}

# Split one LATEST object into the signed two lines ($2) and the signature file ($3)
# verify_release_signature already checks. Exactly three LF-terminated lines; the signature
# covers the first two and nothing else.
split_latest_pointer() {
  _sp_status=0
  _sp_l1=
  _sp_l2=
  _sp_l3=
  _sp_extra=
  {
    IFS= read -r _sp_l1 || _sp_status=1
    IFS= read -r _sp_l2 || _sp_status=1
    IFS= read -r _sp_l3 || _sp_status=1
    if IFS= read -r _sp_extra; then _sp_status=1; fi
  } < "$1" || return 1
  # A fourth line, empty or not, is not the three-line object.
  [ -z "$_sp_extra" ] || _sp_status=1
  [ "$_sp_status" -eq 0 ] || return 1
  printf '%s\n' "$_sp_l1" | grep -Eq '^version [0-9]+\.[0-9]+\.[0-9]+([-.][A-Za-z0-9]+)*$' || return 1
  printf '%s\n' "$_sp_l2" | grep -Eq '^issued [0-9]{1,18}$' || return 1
  printf '%s\n' "$_sp_l3" | grep -Eq '^signature [A-Za-z0-9+/]+={0,2}$' || return 1
  printf '%s\n%s\n' "$_sp_l1" "$_sp_l2" > "$2"
  printf '%s\n' "${_sp_l3#signature }" > "$3"
}

# Nothing suitable installed — bootstrap the latest published release. The pointer is one
# signed object — `version <v>`, `issued <unix-seconds>`, and `signature` over those two
# lines — and is read literally once the signature verifies; the lock's jk-min floor below is
# what refuses a pointer rolled back to a release too old for this checkout.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
if ! curl -fsSL -o "$TMP/LATEST" "$RELEASES/latest/LATEST"; then
  echo "jk wrapper: could not read $RELEASES/latest/LATEST — offline, or JK_RELEASES_URL is wrong." >&2
  exit 1
fi
if ! split_latest_pointer "$TMP/LATEST" "$TMP/LATEST.body" "$TMP/LATEST.sig"; then
  echo "jk wrapper: $RELEASES/latest/LATEST is not a release pointer — refusing." >&2
  exit 1
fi
verify_release_signature "$TMP/LATEST.body" "$TMP/LATEST.sig" "latest-release pointer"
VERSION="$(awk '
  NR == 1 && $0 ~ /^version [0-9]+\.[0-9]+\.[0-9]+([-.][A-Za-z0-9]+)*$/ { v = substr($0, 9); next }
  NR == 2 && $0 ~ /^issued [0-9]+$/ { next }
  { bad = 1 }
  END { if (bad || NR != 2 || v == "") exit 1; print v }
' "$TMP/LATEST.body")" || {
  echo "jk wrapper: $RELEASES/latest/LATEST is not a release pointer — refusing." >&2
  exit 1
}
if [ -n "$FLOOR" ] && ! ver_ge "$VERSION" "$FLOOR"; then
  echo "jk wrapper: this lock requires jk >= $FLOOR but the latest release is $VERSION — check JK_RELEASES_URL." >&2
  exit 1
fi

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$OS" in darwin) OS=macos ;; esac
ARCH="$(uname -m)"
case "$ARCH" in amd64) ARCH=x86_64 ;; arm64) ARCH=aarch64 ;; esac
FILE="jk-$OS-$ARCH-$VERSION.xz"
echo "jk wrapper: fetching jk $VERSION ..." >&2
for NAME in "$FILE" SHA256SUMS SHA256SUMS.sig; do
  curl -fsSL -o "$TMP/$NAME" "$RELEASES/$VERSION/$NAME" || {
    echo "jk wrapper: could not read $RELEASES/$VERSION/$NAME — the release host does not serve jk $VERSION, or JK_RELEASES_URL is wrong." >&2
    exit 1
  }
done
verify_release_signature "$TMP/SHA256SUMS" "$TMP/SHA256SUMS.sig" "release"
WANT="$(awk -v wanted="$FILE" '
  {
    hash = substr($0, 1, 64)
    sep = substr($0, 65, 2)
    name = substr($0, 67)
    if (length(hash) != 64 || hash !~ /^[0-9A-Fa-f]+$/ || sep != "  " ||
        name !~ /^[A-Za-z0-9][A-Za-z0-9._-]*$/ || seen[name]++) bad = 1
    if (name == wanted) { matches++; found = tolower(hash) }
  }
  END { if (bad || matches != 1) exit 1; print found }
' "$TMP/SHA256SUMS")" || {
  echo "jk wrapper: release SHA256SUMS is malformed or lacks one exact $FILE entry — refusing." >&2
  exit 1
}
GOT="$(openssl dgst -sha256 "$TMP/$FILE" | awk '{print tolower($NF)}')"
if [ "$GOT" != "$WANT" ]; then
  echo "jk wrapper: sha256 mismatch for $FILE — refusing (expected $WANT, got $GOT)." >&2
  exit 1
fi
# Stock macOS has no xz binary; /usr/bin/compression_tool decodes the xz container.
if command -v xz >/dev/null 2>&1; then
  xz -dc "$TMP/$FILE" > "$TMP/jk"
elif [ "$(uname -s)" = "Darwin" ] && [ -x /usr/bin/compression_tool ]; then
  /usr/bin/compression_tool -decode -A lzma -i "$TMP/$FILE" -o "$TMP/jk"
else
  echo "jk wrapper: cannot decompress .xz; install xz and re-run (Linux: xz-utils; macOS: brew install xz)." >&2
  exit 1
fi
mkdir -p "$BIN_DIR"
if [ -e "$BIN" ] || [ -L "$BIN" ]; then
  mv -f "$BIN" "$BIN.old" 2>/dev/null || rm -f "$BIN"
fi
cp "$TMP/jk" "$BIN.part" && chmod +x "$BIN.part" && mv "$BIN.part" "$BIN"
printf '%s\n' "$VERSION" > "$BIN_DIR/VERSION"
rm -f "$BIN.old" 2>/dev/null || true

# exec replaces this shell, so the EXIT trap never runs: the scratch directory goes first.
rm -rf "$TMP"
exec "$BIN" "$@"
