#!/bin/sh
# JumpKick bootstrap wrapper — generated by `jk wrapper`. Regenerate rather than editing.
#
# Bootstraps CURRENT jk, never a historical one: uses the locally installed jk that
# satisfies the lock's optional `jk-min` floor, else fetches the latest published release
# (its signed latest/LATEST pointer, then the signed release SHA256SUMS) and execs it: the native
# client when those sums list one for this OS and architecture, else the JVM client on the user's
# JDK 25+. The lock pins inputs, not the operator — there is no version pin here and none in
# jk-lock.toml.
set -eu

# Where jk lives / gets installed — the SAME answer as install.sh and JkDirs, which is now
# one expression rather than a cascade. The wrapper must never invent its own layout: an
# earlier one cached into a directory the resolver did not name, shadowing the real install
# forever, so `jk self update` (which replaces the bin-dir binary) never reached its users.
case "${JK_HOME:-/}" in
  /*) ;;
  *) echo "jk wrapper: JK_HOME must be an absolute path: $JK_HOME" >&2; exit 1 ;;
esac
HOME_DIR="${JK_HOME:-$HOME/.jk}"
BIN_DIR="$HOME_DIR/bin"
RELEASES="${JK_RELEASES_URL:-https://jumpkick.build/releases}"
RELEASE_RSA_SPKI="MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA2t27ZGJXSS9btuDOBzZN04fq8qcp9Ej/tNbmCpCo10Y6wjcQQY8sJfva4zqvhdZNZz/OEYvwePuZIkTVwmrCOU5jKHeHpP/9m9gYTx7DKr7o5koU/26UOi8kII2LfgU7J5iaYkVR3jUX54lGfXJbNJo2VY7aFRPojW+aCBAI7O0GbQ2h60HK12ltdIk3yomWbBpEYs7XTCScU+jAz2RKpznX966Ue9Obhw5r1/hDITBLbCSEChjsVXwx1343k17xXVgreO8X+gwrwBDw9MwSIpGg5LwJ7enLpW6ua8sfLRnjhyyeBJ+RMrc30KVHfPsgYuSvlF1iCcokM8JJBOK7XGKQSszUn2D/fPC5xjOmDT/4K6c0GnSmybSfzL6zUa5ShIkuiq4eix+WfJ7PGl77vqxQUT4/nURMsFVQJ+Qe9+7pegXbW9/oLZ01/+6AKuZaf7qyMN89p3nGJiOTgACOygY8YEc/Xl3Ue4zxgbu/dR+S3P8dATD2iBhGs6AHR8OPAgMBAAE="
case "$0" in */*) DIR="${0%/*}" ;; *) DIR="." ;; esac

# The lock's optional floor: minimum jk able to run this checkout.
FLOOR=""
SEARCH="$DIR"
I=0
while [ "$I" -lt 24 ]; do
  if [ -f "$SEARCH/jk-lock.toml" ]; then
    while IFS= read -r LINE || [ -n "$LINE" ]; do
      case "$LINE" in
        "jk-min = "*)
          FLOOR="${LINE#*\"}"; FLOOR="${FLOOR%%\"*}"
          break
          ;;
      esac
    done < "$SEARCH/jk-lock.toml"
    break
  fi
  case "$SEARCH" in /) break ;; esac
  SEARCH="$SEARCH/.."
  I=$((I+1))
done

# True when $1 >= $2 as dotted versions (pre-release suffixes compare by their numeric core).
ver_ge() {
  A="${1%%-*}"; B="${2%%-*}"
  HI="$(printf '%s\n%s\n' "$A" "$B" | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)"
  [ "$HI" = "$A" ]
}

BIN="$BIN_DIR/jk"
# True when the installed jk may run: it exists, and there is no floor, no VERSION record to
# compare (the binary enforces the lock itself), or a VERSION that meets the floor.
installed_ok() {
  [ -x "$BIN" ] || return 1
  INSTALLED=""
  if [ -f "$BIN_DIR/VERSION" ]; then
    INSTALLED="$(tr -d '[:space:]' < "$BIN_DIR/VERSION")"
  fi
  [ -z "$FLOOR" ] || [ -z "$INSTALLED" ] || ver_ge "$INSTALLED" "$FLOOR"
}
if installed_ok; then
  exec "$BIN" "$@"
fi
# Canonical path of $1: symlinks resolved, relative made absolute. realpath and readlink -f
# are not on every host (older macOS has neither), so the fallback resolves the directory
# with pwd -P and keeps the leaf.
real_path() {
  if command -v realpath >/dev/null 2>&1 && realpath "$1" 2>/dev/null; then
    return 0
  fi
  if readlink -f "$1" >/dev/null 2>&1; then
    readlink -f "$1"
    return 0
  fi
  case "$1" in */*) RP_DIR="${1%/*}"; RP_LEAF="${1##*/}" ;; *) RP_DIR="."; RP_LEAF="$1" ;; esac
  if RP_DIR="$(cd "$RP_DIR" 2>/dev/null && pwd -P)"; then
    printf '%s/%s\n' "$RP_DIR" "$RP_LEAF"
  else
    printf '%s\n' "$1"
  fi
}

# True when $1 is a copy of this wrapper (any generation): the first lines carry its banner.
is_wrapper() {
  head -n 3 "$1" 2>/dev/null | grep -q "JumpKick bootstrap wrapper"
}

# A jk already on PATH (a distro package, or a home this JK_HOME did not name) beats a
# bootstrap download; a current jk enforces the lock floor itself. Never re-exec the very
# binary the floor check above just rejected, and never exec this wrapper again: with `.`
# on PATH, or the committed wrapper symlinked or copied into a PATH directory, `command -v jk`
# answers with the wrapper itself, and exec-ing it is a loop that never reaches the download.
if command -v jk >/dev/null 2>&1; then
  PATH_JK="$(command -v jk)"
  case "$PATH_JK" in
    /*|./*|../*) ;;
    *) PATH_JK="" ;;
  esac
  if [ -n "$PATH_JK" ] && [ "$PATH_JK" != "$BIN" ] &&
    [ "$(real_path "$PATH_JK")" != "$(real_path "$0")" ] && ! is_wrapper "$PATH_JK"; then
    exec "$PATH_JK" "$@"
  fi
fi

# Verify the release key's RSA/SHA-256 signature in $2 over the exact bytes of $1, or exit
# naming $3. Every remote input that steers the bootstrap — the latest-release pointer and the
# version directory's SHA256SUMS — passes through here before anything it names is trusted.
verify_release_signature() {
  if ! command -v openssl >/dev/null 2>&1; then
    echo "jk wrapper: OpenSSL is required to authenticate the release." >&2
    exit 1
  fi
  [ -f "$TMP/release-public.pem" ] || {
    printf '%s\n' "-----BEGIN PUBLIC KEY-----"
    printf '%s' "$RELEASE_RSA_SPKI" | fold -w 64
    printf '\n'
    printf '%s\n' "-----END PUBLIC KEY-----"
  } >"$TMP/release-public.pem"
  VS_TEXT="$(tr -d '\r' <"$2")"
  VS_LINES="$(wc -l <"$2" | tr -d '[:space:]')"
  if { [ "$VS_LINES" != "0" ] && [ "$VS_LINES" != "1" ]; } ||
    [ "${#VS_TEXT}" -ne 512 ] ||
    ! printf '%s' "$VS_TEXT" | LC_ALL=C grep -Eq '^[A-Za-z0-9+/]+={0,2}$'; then
    echo "jk wrapper: $3 signature is malformed — refusing." >&2
    exit 1
  fi
  printf '%s' "$VS_TEXT" | openssl base64 -d -A >"$2.bin" 2>/dev/null || {
    echo "jk wrapper: $3 signature is not valid base64 — refusing." >&2
    exit 1
  }
  [ "$(wc -c <"$2.bin" | tr -d '[:space:]')" = "384" ] || {
    echo "jk wrapper: $3 signature has the wrong RSA-3072 length — refusing." >&2
    exit 1
  }
  openssl dgst -sha256 -verify "$TMP/release-public.pem" -signature "$2.bin" "$1" >/dev/null 2>&1 || {
    echo "jk wrapper: $3 signature verification failed — refusing." >&2
    exit 1
  }
}

# Split one LATEST object into the signed two lines ($2) and the signature file ($3)
# verify_release_signature already checks. Exactly three LF-terminated lines; the signature
# covers the first two and nothing else.
split_latest_pointer() {
  _sp_status=0
  _sp_l1=
  _sp_l2=
  _sp_l3=
  _sp_extra=
  {
    IFS= read -r _sp_l1 || _sp_status=1
    IFS= read -r _sp_l2 || _sp_status=1
    IFS= read -r _sp_l3 || _sp_status=1
    if IFS= read -r _sp_extra; then _sp_status=1; fi
  } < "$1" || return 1
  # A fourth line, empty or not, is not the three-line object.
  [ -z "$_sp_extra" ] || _sp_status=1
  [ "$_sp_status" -eq 0 ] || return 1
  printf '%s\n' "$_sp_l1" | grep -Eq '^version [0-9]+\.[0-9]+\.[0-9]+([-.][A-Za-z0-9]+)*$' || return 1
  printf '%s\n' "$_sp_l2" | grep -Eq '^issued [0-9]{1,18}$' || return 1
  printf '%s\n' "$_sp_l3" | grep -Eq '^signature [A-Za-z0-9+/]+={0,2}$' || return 1
  printf '%s\n%s\n' "$_sp_l1" "$_sp_l2" > "$2"
  printf '%s\n' "${_sp_l3#signature }" > "$3"
}

# Which client: JK_CLIENT as install.sh reads it; unset, the native client when the release lists
# one for this host, else the JVM client.
CLIENT="${JK_CLIENT:-}"
case "$CLIENT" in
  ""|native|jvm) ;;
  *) echo "jk wrapper: JK_CLIENT must be native or jvm, not $CLIENT — refusing." >&2; exit 1 ;;
esac

# One download per JK_HOME: mkdir is atomic, so the wrapper that creates the lock directory
# installs and every other one waits. A lock older than ten minutes, or whose owner process on
# this host is gone, is broken; losing that race costs a second download, never a broken
# install. The scratch directory lives inside the lock, so releasing it clears it.
LOCK="$BIN_DIR/.jk-wrapper.lock"
HOST="$(uname -n 2>/dev/null || echo unknown)"
break_stale_lock() {
  STALE=""
  if [ -n "$(find "$LOCK" -maxdepth 0 -mmin +10 2>/dev/null)" ]; then
    STALE=1
  elif [ -f "$LOCK/owner" ]; then
    read -r OWNER_PID OWNER_HOST < "$LOCK/owner" || true
    case "${OWNER_PID:-}" in
      ''|*[!0-9]*) ;;
      *) if [ "${OWNER_HOST:-}" = "$HOST" ] && ! kill -0 "$OWNER_PID" 2>/dev/null; then STALE=1; fi ;;
    esac
  fi
  if [ -n "$STALE" ] && mv "$LOCK" "$LOCK.stale.$$" 2>/dev/null; then
    rm -rf "$LOCK.stale.$$"
  fi
}
mkdir -p "$BIN_DIR"
WAITED=0
while ! mkdir "$LOCK" 2>/dev/null; do
  if [ "$WAITED" -eq 0 ]; then
    echo "jk wrapper: another jk wrapper is installing jk; waiting for it ..." >&2
  fi
  if [ $((WAITED % 5)) -eq 0 ]; then
    break_stale_lock
  fi
  sleep 1
  WAITED=$((WAITED + 1))
done
trap 'rm -rf "$LOCK"' EXIT
trap 'exit 1' HUP INT TERM
printf '%s %s\n' "$$" "$HOST" > "$LOCK/owner"
# The wrapper this one waited on may have installed a jk that now satisfies the floor.
if installed_ok; then
  rm -rf "$LOCK"
  exec "$BIN" "$@"
fi
TMP="$LOCK/fetch"
mkdir "$TMP"

# Nothing suitable installed — bootstrap the latest published release. The pointer is one
# signed object — `version <v>`, `issued <unix-seconds>`, and `signature` over those two
# lines — and is read literally once the signature verifies; the lock's jk-min floor below is
# what refuses a pointer rolled back to a release too old for this checkout.
if ! curl -fsSL -o "$TMP/LATEST" "$RELEASES/latest/LATEST"; then
  echo "jk wrapper: could not read $RELEASES/latest/LATEST — offline, or JK_RELEASES_URL is wrong." >&2
  exit 1
fi
if ! split_latest_pointer "$TMP/LATEST" "$TMP/LATEST.body" "$TMP/LATEST.sig"; then
  echo "jk wrapper: $RELEASES/latest/LATEST is not a release pointer — refusing." >&2
  exit 1
fi
verify_release_signature "$TMP/LATEST.body" "$TMP/LATEST.sig" "latest-release pointer"
VERSION="$(awk '
  NR == 1 && $0 ~ /^version [0-9]+\.[0-9]+\.[0-9]+([-.][A-Za-z0-9]+)*$/ { v = substr($0, 9); next }
  NR == 2 && $0 ~ /^issued [0-9]+$/ { next }
  { bad = 1 }
  END { if (bad || NR != 2 || v == "") exit 1; print v }
' "$TMP/LATEST.body")" || {
  echo "jk wrapper: $RELEASES/latest/LATEST is not a release pointer — refusing." >&2
  exit 1
}
if [ -n "$FLOOR" ] && ! ver_ge "$VERSION" "$FLOOR"; then
  echo "jk wrapper: this lock requires jk >= $FLOOR but the latest release is $VERSION — check JK_RELEASES_URL." >&2
  exit 1
fi

echo "jk wrapper: fetching jk $VERSION ..." >&2
fetch() {
  curl -fsSL -o "$TMP/$1" "$RELEASES/$VERSION/$1" || {
    echo "jk wrapper: could not read $RELEASES/$VERSION/$1 — the release host does not serve jk $VERSION, or JK_RELEASES_URL is wrong." >&2
    exit 1
  }
}
fetch SHA256SUMS
fetch SHA256SUMS.sig
verify_release_signature "$TMP/SHA256SUMS" "$TMP/SHA256SUMS.sig" "release"

# This host as a release names its native client, jk-<os>-<arch>-<version>; the signed sums say
# whether this release has one. Anywhere else, the JVM client runs on the user's JDK.
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$OS" in darwin) OS=macos ;; esac
ARCH="$(uname -m | tr '[:upper:]' '[:lower:]')"
case "$ARCH" in amd64) ARCH=x86_64 ;; arm64) ARCH=aarch64 ;; esac
TARGET="$(printf '%s' "$OS" | tr -c 'a-z0-9_' '_')-$(printf '%s' "$ARCH" | tr -c 'a-z0-9_' '_')"
if [ "$CLIENT" != "jvm" ] && awk -v wanted="jk-$TARGET-$VERSION.xz" '
  substr($0, 65, 2) == "  " && substr($0, 67) == wanted { found = 1 } END { exit !found }
' "$TMP/SHA256SUMS"; then
  CLIENT=native
  FILE="jk-$TARGET-$VERSION.xz"
elif [ "$CLIENT" = "native" ]; then
  echo "jk wrapper: jk $VERSION publishes no native $TARGET client; unset JK_CLIENT to use the JVM client." >&2
  exit 1
else
  if [ -z "$CLIENT" ]; then
    echo "jk wrapper: jk $VERSION publishes no native $TARGET client; installing the JVM client." >&2
  fi
  CLIENT=jvm
  FILE="jk-$VERSION.jar"
  # A JDK 25 or newer, with javac (the engine compiles on it): JK_JAVA_HOME, else JAVA_HOME, else
  # java on PATH — the order install.sh reads.
  if [ -n "${JK_JAVA_HOME:-}" ]; then
    JAVA="$JK_JAVA_HOME/bin/java"
  elif [ -n "${JAVA_HOME:-}" ]; then
    JAVA="$JAVA_HOME/bin/java"
  else
    JAVA="$(command -v java 2>/dev/null || true)"
  fi
  JAVA_MAJOR=""
  JAVA_AT=""
  if [ -n "$JAVA" ] && [ -x "$JAVA" ]; then
    JAVA_PROPS="$("$JAVA" -XshowSettings:properties -version 2>&1 || true)"
    JAVA_MAJOR="$(printf '%s\n' "$JAVA_PROPS" | awk -F'"' '/ version "/ { split($2, v, /[._]/); if (v[1] == "1") print v[2]; else print v[1]; exit }')"
    JAVA_AT="$(printf '%s\n' "$JAVA_PROPS" | awk -F' = ' '/^ *java\.home = / { print $2; exit }')"
  fi
  case "$JAVA_MAJOR" in ''|*[!0-9]*) JAVA_MAJOR=0 ;; esac
  if [ "$JAVA_MAJOR" -lt 25 ] || { [ -n "$JAVA_AT" ] && [ ! -x "$JAVA_AT/bin/javac" ]; }; then
    echo "jk wrapper: the jk JVM client needs a JDK 25 or newer — set JAVA_HOME or JK_JAVA_HOME to one and re-run." >&2
    exit 1
  fi
fi
fetch "$FILE"
WANT="$(awk -v wanted="$FILE" '
  {
    hash = substr($0, 1, 64)
    sep = substr($0, 65, 2)
    name = substr($0, 67)
    if (length(hash) != 64 || hash !~ /^[0-9A-Fa-f]+$/ || sep != "  " ||
        name !~ /^[A-Za-z0-9][A-Za-z0-9._-]*$/ || seen[name]++) bad = 1
    if (name == wanted) { matches++; found = tolower(hash) }
  }
  END { if (bad || matches != 1) exit 1; print found }
' "$TMP/SHA256SUMS")" || {
  echo "jk wrapper: release SHA256SUMS is malformed or lacks one exact $FILE entry — refusing." >&2
  exit 1
}
GOT="$(openssl dgst -sha256 "$TMP/$FILE" | awk '{print tolower($NF)}')"
if [ "$GOT" != "$WANT" ]; then
  echo "jk wrapper: sha256 mismatch for $FILE — refusing (expected $WANT, got $GOT)." >&2
  exit 1
fi

if [ "$CLIENT" = "jvm" ]; then
  # The jar goes under <home>/lib/jk, as JvmClientInstall lays it out; the client itself then
  # writes bin/jk over the JDK checked above. It fetches its own engine on first use, as a
  # downloaded native client does.
  LIB="$HOME_DIR/lib/jk"
  mkdir -p "$LIB"
  cp "$TMP/$FILE" "$LIB/$FILE.part" && mv -f "$LIB/$FILE.part" "$LIB/$FILE"
  for OLD in "$LIB"/jk-*.jar; do
    [ "$OLD" = "$LIB/$FILE" ] || rm -f "$OLD"
  done
  JK_HOME="$HOME_DIR" "$JAVA" --enable-native-access=ALL-UNNAMED -jar "$LIB/$FILE" self write-launcher >/dev/null || {
    echo "jk wrapper: $JAVA could not write the JVM client's launcher into $BIN_DIR." >&2
    exit 1
  }
  printf '%s\n' "$VERSION" > "$BIN_DIR/VERSION"
  rm -rf "$LOCK"
  exec "$BIN" "$@"
fi

# Stock macOS has no xz binary; /usr/bin/compression_tool decodes an .xz stream with -a lzma
# (-A reads its own block container instead).
if command -v xz >/dev/null 2>&1; then
  xz -dc "$TMP/$FILE" > "$TMP/jk"
elif [ "$(uname -s)" = "Darwin" ] && [ -x /usr/bin/compression_tool ]; then
  /usr/bin/compression_tool -decode -a lzma -i "$TMP/$FILE" -o "$TMP/jk"
else
  echo "jk wrapper: cannot decompress .xz; install xz and re-run (Linux: xz-utils; macOS: brew install xz)." >&2
  exit 1
fi
if [ -e "$BIN" ] || [ -L "$BIN" ]; then
  mv -f "$BIN" "$BIN.old" 2>/dev/null || rm -f "$BIN"
fi
cp "$TMP/jk" "$BIN.part" && chmod +x "$BIN.part" && mv "$BIN.part" "$BIN"
printf '%s\n' "$VERSION" > "$BIN_DIR/VERSION"
rm -f "$BIN.old" 2>/dev/null || true

# exec replaces this shell, so the EXIT trap never runs: the lock and its scratch go first.
rm -rf "$LOCK"
exec "$BIN" "$@"
