#!/bin/sh
# JumpKick bootstrap wrapper — generated by `jk wrapper`. Regenerate rather than editing.
#
# Bootstraps CURRENT jk, never a historical one: uses the locally installed jk that
# satisfies the lock's optional `jk-min` floor, else fetches the latest published release
# (verified against the signed release SHA256SUMS) and execs it. The lock pins inputs, not the
# operator — there is no version pin here and none in jk-lock.toml.
set -eu

# Where jk lives / gets installed — the SAME answer as install.sh and JkDirs, which is now
# one expression rather than a cascade. The wrapper must never invent its own layout: an
# earlier one cached into a directory the resolver did not name, shadowing the real install
# forever, so `jk self update` (which replaces the bin-dir binary) never reached its users.
case "${JK_HOME:-/}" in
  /*) ;;
  *) echo "jk wrapper: JK_HOME must be an absolute path: $JK_HOME" >&2; exit 1 ;;
esac
BIN_DIR="${JK_HOME:-$HOME/.jk}/bin"
RELEASES="${JK_RELEASES_URL:-https://jumpkick.build/releases}"
RELEASE_RSA_SPKI="MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAztiftv1t1l9vI1xebPHGe/MAapolNPiYE/elvRFT2OL3SyawfN19L+qxiyHGsJUF52+zGhVLU2s5RR+b5bj9Cjey2wDs+AAL4nR0FSzo8seXNoahOMZfv+gJY386YenXGAxbElwuw3LqTIlfQvPwiX+9m/RBltKk7WOQI9z35/a17P1i7sj8hC/QHtRCnhsX73wGFKP9jng1Ftk+v/U5gvzSOcGawYyQJ0iP/p2nyiBIrxTLSJDx4u+gHVdk1PUmW8p5h31GsDqBUzkTX0GUut2gVolaPpW/9rP/QyNv9vtxtnby6T1xVSAkP5rL+rIedr52mSwiUDOTl9WxJzGZdIREvSMn6H37pAFATbokYETCEQQ33MelCWFMjfQYBxSU0dVrigmiQOYIhYOR9IcuFM22w5Lkq2jick7u/TKZGy9Nq0F2/jxNF28CQj7S5nkpoQTrHIfg86/upXMtU3QK/Zfes37TGptB3wuPjXm3b09iiquOqrClJ6TN9Yz1tbu7AgMBAAE="
case "$0" in */*) DIR="${0%/*}" ;; *) DIR="." ;; esac

# The lock's optional floor: minimum jk able to run this checkout.
FLOOR=""
SEARCH="$DIR"
I=0
while [ "$I" -lt 24 ]; do
  if [ -f "$SEARCH/jk-lock.toml" ]; then
    while IFS= read -r LINE || [ -n "$LINE" ]; do
      case "$LINE" in
        "jk-min = "*)
          FLOOR="${LINE#*\"}"; FLOOR="${FLOOR%%\"*}"
          break
          ;;
      esac
    done < "$SEARCH/jk-lock.toml"
    break
  fi
  case "$SEARCH" in /) break ;; esac
  SEARCH="$SEARCH/.."
  I=$((I+1))
done

# True when $1 >= $2 as dotted versions (pre-release suffixes compare by their numeric core).
ver_ge() {
  A="${1%%-*}"; B="${2%%-*}"
  HI="$(printf '%s\n%s\n' "$A" "$B" | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)"
  [ "$HI" = "$A" ]
}

BIN="$BIN_DIR/jk"
if [ -x "$BIN" ]; then
  INSTALLED=""
  if [ -f "$BIN_DIR/VERSION" ]; then
    INSTALLED="$(tr -d '[:space:]' < "$BIN_DIR/VERSION")"
  fi
  if [ -z "$FLOOR" ] || [ -z "$INSTALLED" ] || ver_ge "$INSTALLED" "$FLOOR"; then
    exec "$BIN" "$@"
  fi
fi
# A jk already on PATH (a distro package, or a home this JK_HOME did not name) beats a
# bootstrap download; a current jk enforces the lock floor itself. Never re-exec the very
# binary the floor check above just rejected.
if command -v jk >/dev/null 2>&1; then
  PATH_JK="$(command -v jk)"
  if [ "$PATH_JK" != "$BIN" ]; then
    exec "$PATH_JK" "$@"
  fi
fi

# Nothing suitable installed — bootstrap the latest published release.
VERSION="$(curl -fsSL "$RELEASES/latest/VERSION" | tr -d '[:space:]')"
if [ -n "$FLOOR" ] && ! ver_ge "$VERSION" "$FLOOR"; then
  echo "jk wrapper: this lock requires jk >= $FLOOR but the latest release is $VERSION — check JK_RELEASES_URL." >&2
  exit 1
fi

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$OS" in darwin) OS=macos ;; esac
ARCH="$(uname -m)"
case "$ARCH" in amd64) ARCH=x86_64 ;; arm64) ARCH=aarch64 ;; esac
FILE="jk-$OS-$ARCH-$VERSION.xz"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
echo "jk wrapper: fetching jk $VERSION ..." >&2
curl -fsSL -o "$TMP/$FILE" "$RELEASES/$VERSION/$FILE"
curl -fsSL -o "$TMP/SHA256SUMS" "$RELEASES/$VERSION/SHA256SUMS"
curl -fsSL -o "$TMP/SHA256SUMS.sig" "$RELEASES/$VERSION/SHA256SUMS.sig"
if ! command -v openssl >/dev/null 2>&1; then
  echo "jk wrapper: OpenSSL is required to authenticate the release." >&2
  exit 1
fi
{
  printf '%s\n' "-----BEGIN PUBLIC KEY-----"
  printf '%s' "$RELEASE_RSA_SPKI" | fold -w 64
  printf '\n'
  printf '%s\n' "-----END PUBLIC KEY-----"
} >"$TMP/release-public.pem"
SIG_TEXT="$(tr -d '\r' <"$TMP/SHA256SUMS.sig")"
SIG_LINES="$(wc -l <"$TMP/SHA256SUMS.sig" | tr -d '[:space:]')"
if { [ "$SIG_LINES" != "0" ] && [ "$SIG_LINES" != "1" ]; } ||
  [ "${#SIG_TEXT}" -ne 512 ] ||
  ! printf '%s' "$SIG_TEXT" | LC_ALL=C grep -Eq '^[A-Za-z0-9+/]+={0,2}$'; then
  echo "jk wrapper: release signature is malformed — refusing." >&2
  exit 1
fi
printf '%s' "$SIG_TEXT" | openssl base64 -d -A >"$TMP/SHA256SUMS.sig.bin" 2>/dev/null || {
  echo "jk wrapper: release signature is not valid base64 — refusing." >&2
  exit 1
}
openssl dgst -sha256 -verify "$TMP/release-public.pem" -signature "$TMP/SHA256SUMS.sig.bin" \
  "$TMP/SHA256SUMS" >/dev/null 2>&1 || {
  echo "jk wrapper: release signature verification failed — refusing." >&2
  exit 1
}
WANT="$(awk -v wanted="$FILE" '
  {
    hash = substr($0, 1, 64)
    sep = substr($0, 65, 2)
    name = substr($0, 67)
    if (length(hash) != 64 || hash !~ /^[0-9A-Fa-f]+$/ || sep != "  " ||
        name !~ /^[A-Za-z0-9][A-Za-z0-9._-]*$/ || seen[name]++) bad = 1
    if (name == wanted) { matches++; found = tolower(hash) }
  }
  END { if (bad || matches != 1) exit 1; print found }
' "$TMP/SHA256SUMS")" || {
  echo "jk wrapper: release SHA256SUMS is malformed or lacks one exact $FILE entry — refusing." >&2
  exit 1
}
GOT="$(openssl dgst -sha256 "$TMP/$FILE" | awk '{print tolower($NF)}')"
if [ "$GOT" != "$WANT" ]; then
  echo "jk wrapper: sha256 mismatch for $FILE — refusing (expected $WANT, got $GOT)." >&2
  exit 1
fi
# Stock macOS has no xz binary; /usr/bin/compression_tool decodes the xz container.
if command -v xz >/dev/null 2>&1; then
  xz -dc "$TMP/$FILE" > "$TMP/jk"
elif [ "$(uname -s)" = "Darwin" ] && [ -x /usr/bin/compression_tool ]; then
  /usr/bin/compression_tool -decode -A lzma -i "$TMP/$FILE" -o "$TMP/jk"
else
  echo "jk wrapper: cannot decompress .xz; install xz and re-run (Linux: xz-utils; macOS: brew install xz)." >&2
  exit 1
fi
mkdir -p "$BIN_DIR"
if [ -e "$BIN" ] || [ -L "$BIN" ]; then
  mv -f "$BIN" "$BIN.old" 2>/dev/null || rm -f "$BIN"
fi
cp "$TMP/jk" "$BIN.part" && chmod +x "$BIN.part" && mv "$BIN.part" "$BIN"
printf '%s\n' "$VERSION" > "$BIN_DIR/VERSION"
rm -f "$BIN.old" 2>/dev/null || true

exec "$BIN" "$@"
