// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.util;

import cc.jumpkick.host.PathUtil;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryNotEmptyException;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.util.Locale;

/**
 * "Did jk create this?" — the question a delete has to answer before it recurses into a directory
 * jk shares with somebody else.
 *
 * <p>jk is a guest in several roots on purpose. {@code ~/.jdks} is IntelliJ's, and installing there
 * is the point — "so IDE and JumpKick share managed runtimes". {@code ~/.local/bin} is everyone's.
 * In a shared root a <em>name</em> is not a claim: {@code graalvm-25} is a name jk wants and also,
 * very often, a JDK the user installed first. Three sites decided that question for themselves and
 * two of them got it wrong, destroying four real JDK installations (JK-2624). This is the fourth
 * spelling of the rule and meant to be the last.
 *
 * <p><strong>Where a marker is and is not the answer.</strong> Most of jk's deletes are under roots
 * it owns outright — the cache, the store, the state dir, a project's {@code target/} — and there
 * containment is a <em>stronger</em> check than a marker, because it cannot be lost, forged, or
 * forgotten at write time. Requiring a marker there would add ceremony to a hundred correct call
 * sites and invent a new failure mode where jk refuses to clean its own cache. So this type is for
 * the shared roots, and for the shape of thing that can hold a marker: a directory tree. A single
 * file in a shared directory cannot carry one — the launcher jk writes into {@code ~/.local/bin}
 * proves its own origin with a generated-by header instead (JK-2626).
 *
 * <p>Compare {@link OwnerOnlyFiles}, which owns who may <em>read</em> a file. This owns who may
 * <em>delete</em> one.
 */
public final class JkOwnership {

    /** Marker file written inside a directory tree jk created. */
    public static final String MARKER = ".jk-owned";

    /**
     * Attribution jk writes into every launcher script it puts on a shared {@code PATH} directory,
     * and the thing to look for before deleting one.
     *
     * <p>A single file cannot hold a {@link #MARKER}, so the evidence has to be inside it. Three
     * writers spelled this for themselves and drifted into two spellings — {@code "Generated by jk
     * install"} and {@code "generated by jk"} — with exactly one of them ever read back, so the
     * check that existed protected only {@code jkx}. Matching is case-insensitive so both survive.
     */
    public static final String GENERATED_BY = "Generated by jk";

    /** How much of a launcher to read looking for {@link #GENERATED_BY}. */
    private static final int ATTRIBUTION_PREFIX_BYTES = 1024;

    private JkOwnership() {}

    /**
     * Write the ownership marker under {@code dir}. Best-effort and never throws: a missing marker
     * costs a later refusal to clean up, which is the safe direction to fail in.
     */
    public static void mark(Path dir) {
        if (dir == null) return;
        try {
            Files.createDirectories(dir);
            Path marker = dir.resolve(MARKER);
            if (!Files.exists(marker)) Files.writeString(marker, "jumpkick\n", StandardCharsets.UTF_8);
        } catch (IOException ignored) {
            // Attribution only; the install itself is already on disk.
        }
    }

    /** Whether jk created the tree at {@code dir}. */
    public static boolean isOwned(Path dir) {
        return dir != null && Files.isRegularFile(dir.resolve(MARKER));
    }

    /**
     * Whether jk wrote the launcher script at {@code file}.
     *
     * <p>The counterpart to {@link #isOwned} for the shape that cannot carry a marker file. {@code
     * ~/.local/bin} is the most shared directory on the system — on a real machine it holds the
     * distro's binaries, pip and npm shims, and symlinks into other tools' trees — so a file being
     * <em>named</em> after a tool jk knows is not evidence that jk put it there (JK-2626).
     *
     * <p>Only the first {@value #ATTRIBUTION_PREFIX_BYTES} bytes are read, and that bound is
     * load-bearing rather than tidy: the neighbours in that directory include multi-hundred-megabyte
     * static binaries, and a delete check is not a reason to page one into memory. Anything
     * unreadable, absent, or not a regular file answers {@code false} — the safe direction, since
     * the consequence of a wrong {@code false} is a file left on disk.
     */
    public static boolean isGeneratedLauncher(Path file) {
        if (file == null || !Files.isRegularFile(file)) return false;
        byte[] head;
        try (InputStream in = Files.newInputStream(file)) {
            head = in.readNBytes(ATTRIBUTION_PREFIX_BYTES);
        } catch (IOException unreadable) {
            return false;
        }
        return new String(head, StandardCharsets.UTF_8)
                .toLowerCase(Locale.ROOT)
                .contains(GENERATED_BY.toLowerCase(Locale.ROOT));
    }

    /**
     * Remove whatever is at {@code path} — a symlink, a Windows junction, an empty directory, a
     * regular file — and, when it is a <em>populated</em> directory, only if jk created it.
     *
     * <p>{@link Files#delete} is the load-bearing first move. It removes a link, a junction, an
     * empty directory or a file in one shot and never follows the link, so a junction's target is
     * untouched; only a genuinely populated directory reaches the ownership question. A
     * {@link Files#walk}-shaped delete would descend into a junction instead, because Java does not
     * classify junctions as symlinks, and delete the real JDK on the other side.
     *
     * <p>An unowned populated directory <strong>throws</strong> rather than returning quietly. The
     * callers here treat a failure to claim a name as non-fatal — a stable pointer is a convenience,
     * the install behind it is already complete — so the operation still finishes; the difference is
     * that the reason lands somewhere a human reads instead of a JDK going missing.
     */
    public static void removeIfOwned(Path path) throws IOException {
        if (path == null) return;
        try {
            Files.delete(path);
            return;
        } catch (NoSuchFileException alreadyGone) {
            return;
        } catch (DirectoryNotEmptyException populated) {
            // The only case that needs an answer.
        }
        if (!isOwned(path)) {
            throw new IOException("refusing to remove " + path + " — jk did not create it (no " + MARKER
                    + " marker), and this directory is shared. Remove it yourself if you meant to,"
                    + " or point jk somewhere else.");
        }
        PathUtil.deleteRecursively(path);
    }
}
