version = 1
generated-by = "jk 0.13.2"
resolution-algorithm = "pubgrub-v1"
jk-min = "0.12.0"
manifests-sha256 = "46ed0f5c939031550afd100c1c94bad3ad364e8e2d769ce598acab7bb201f6f4"
project-id = "771c1400264bf30b4e399e0b71b862a0"

[jdk]
suggested-vendor = "temurin"
suggested-version = "25.0.4.1"

[[artifact]]
name     = "com.fasterxml.jackson.core:jackson-annotations:jar:"
version  = "2.22"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:21ddb598807d3a51a876704eb979d9296e1c6a6f47ab1826ff88c6d6a127a2d0"
scopes   = ["main"]

[[artifact]]
name     = "com.fasterxml.jackson.core:jackson-core:jar:"
version  = "2.22.2"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:ff167a6317be15895706c26668f45b898efe40ab8780970658210fe1393d52a6"
scopes   = ["main"]

[[artifact]]
name     = "com.fasterxml.jackson.core:jackson-databind:jar:"
version  = "2.22.2"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:d0da14c12b16b5d54719aa172d83b542ff4abeb8b0fb7db476fde8ceece760ca"
scopes   = ["main"]
deps = [
  "com.fasterxml.jackson.core:jackson-annotations:jar:@2.22",
  "com.fasterxml.jackson.core:jackson-core:jar:@2.22.2",
]

[[artifact]]
name     = "com.google.errorprone:error_prone_annotations:jar:"
version  = "2.50.0"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:4667724877f1d37a689202da191e23efa7657c62eef93ccdac406eccfe5cdd0a"
scopes   = ["main"]

[[artifact]]
name     = "com.google.guava:failureaccess:jar:"
version  = "1.0.3"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:cbfc3906b19b8f55dd7cfd6dfe0aa4532e834250d7f080bd8d211a3e246b59cb"
scopes   = ["main"]

[[artifact]]
name     = "com.google.guava:guava:jar:"
version  = "33.7.1-jre"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:796d8e28ac64e83a47c4c5935a8fecc4682650a04bbdead738ef0f5a3a0e6c46"
scopes   = ["main"]
deps = [
  "com.google.errorprone:error_prone_annotations:jar:@2.50.0",
  "com.google.guava:failureaccess:jar:@1.0.3",
  "com.google.guava:listenablefuture:jar:@9999.0-empty-to-avoid-conflict-with-guava",
  "com.google.j2objc:j2objc-annotations:jar:@3.1",
  "org.jspecify:jspecify:jar:@1.0.1",
]

[[artifact]]
name     = "com.google.guava:listenablefuture:jar:"
version  = "9999.0-empty-to-avoid-conflict-with-guava"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:b372a037d4230aa57fbeffdef30fd6123f9c0c2db85d0aced00c91b974f33f99"
scopes   = ["main"]

[[artifact]]
name     = "com.google.j2objc:j2objc-annotations:jar:"
version  = "3.1"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:84d3a150518485f8140ea99b8a985656749629f6433c92b80c75b36aba3b099b"
scopes   = ["main"]

[[artifact]]
name     = "info.picocli:picocli:jar:"
version  = "4.7.7"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:f86e30fffd10d2b13b8caa8d4b237a7ee61f2ffccf5b1941de718b765d235bf8"
scopes   = ["main"]

[[artifact]]
name     = "org.apache.commons:commons-lang3:jar:"
version  = "3.20.0"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:69e5c9fa35da7a51a5fd2099dfe56a2d8d32cf233e2f6d770e796146440263f4"
scopes   = ["main"]

[[artifact]]
name     = "org.apache.commons:commons-text:jar:"
version  = "1.15.0"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:58d2da30f058512a1e7f914e39241deca4dff5c27a085b4ed2faa9e7208067f6"
scopes   = ["main"]
deps = [
  "org.apache.commons:commons-lang3:jar:@3.20.0",
]

[[artifact]]
name     = "org.apiguardian:apiguardian-api:jar:"
version  = "1.1.2"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:b509448ac506d607319f182537f0b35d71007582ec741832a1f111e5b5b70b38"
scopes   = ["test"]

[[artifact]]
name     = "org.jspecify:jspecify:jar:"
version  = "1.0.1"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:070d75f261fe4c5b8202508366715f7f2d4660f88c8ef7e6d3575e48c9683b66"
scopes   = ["main", "test"]

[[artifact]]
name     = "org.junit.jupiter:junit-jupiter-api:jar:"
version  = "6.1.3"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:555d6cf20fa1710884dd01b86cc5785397ba73e21ada2d4b784f5f1a14dcafc4"
scopes   = ["test"]
deps = [
  "org.apiguardian:apiguardian-api:jar:@1.1.2",
  "org.jspecify:jspecify:jar:@1.0.1",
  "org.junit.platform:junit-platform-commons:jar:@6.1.3",
  "org.opentest4j:opentest4j:jar:@1.3.0",
]

[[artifact]]
name     = "org.junit.jupiter:junit-jupiter-engine:jar:"
version  = "6.1.3"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:414559e78bbfa3bdb2eab009ac3ab1e22369ac31117c270a0bd666da115c5c6c"
scopes   = ["test"]
deps = [
  "org.apiguardian:apiguardian-api:jar:@1.1.2",
  "org.jspecify:jspecify:jar:@1.0.1",
  "org.junit.jupiter:junit-jupiter-api:jar:@6.1.3",
  "org.junit.platform:junit-platform-engine:jar:@6.1.3",
]

[[artifact]]
name     = "org.junit.jupiter:junit-jupiter-params:jar:"
version  = "6.1.3"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:05c51cedba2c06a9770707391e006cee825876937dea580b94a265ce145d4939"
scopes   = ["test"]
deps = [
  "org.apiguardian:apiguardian-api:jar:@1.1.2",
  "org.jspecify:jspecify:jar:@1.0.1",
  "org.junit.jupiter:junit-jupiter-api:jar:@6.1.3",
]

[[artifact]]
name     = "org.junit.jupiter:junit-jupiter:jar:"
version  = "6.1.3"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:6b0a14075c74221de53047e363860b7d19fce802bebc152df2c35c4089c6c379"
scopes   = ["test"]
deps = [
  "org.junit.jupiter:junit-jupiter-api:jar:@6.1.3",
  "org.junit.jupiter:junit-jupiter-engine:jar:@6.1.3",
  "org.junit.jupiter:junit-jupiter-params:jar:@6.1.3",
]

[[artifact]]
name     = "org.junit.platform:junit-platform-commons:jar:"
version  = "6.1.3"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:a4774ae923c109544034aeae7c762cf017fbcdd1342403ba90e0921984b608c3"
scopes   = ["test"]
deps = [
  "org.apiguardian:apiguardian-api:jar:@1.1.2",
  "org.jspecify:jspecify:jar:@1.0.1",
]

[[artifact]]
name     = "org.junit.platform:junit-platform-engine:jar:"
version  = "6.1.3"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:21ad7ad3a35beda16387979317be1833a72a71d812f9a66ee4b9a7bafb56334c"
scopes   = ["test"]
deps = [
  "org.apiguardian:apiguardian-api:jar:@1.1.2",
  "org.jspecify:jspecify:jar:@1.0.1",
  "org.junit.platform:junit-platform-commons:jar:@6.1.3",
  "org.opentest4j:opentest4j:jar:@1.3.0",
]

[[artifact]]
name     = "org.junit.platform:junit-platform-launcher:jar:"
version  = "6.1.3"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:1dec64b1fc0b7c47a11302aa5b4d37d8160c041b396e27067709ce775601a7b6"
scopes   = ["test"]
deps = [
  "org.apiguardian:apiguardian-api:jar:@1.1.2",
  "org.jspecify:jspecify:jar:@1.0.1",
  "org.junit.platform:junit-platform-engine:jar:@6.1.3",
]

[[artifact]]
name     = "org.opentest4j:opentest4j:jar:"
version  = "1.3.0"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:48e2df636cab6563ced64dcdff8abb2355627cb236ef0bf37598682ddf742f1b"
scopes   = ["test"]

[[artifact]]
name     = "org.slf4j:slf4j-api:jar:"
version  = "2.0.19"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:e91ff6d720609e7a194ffe758c3ed5c84e798617ae07b0a0f6a4fe229741b4bb"
scopes   = ["main"]

[[artifact]]
name     = "org.slf4j:slf4j-simple:jar:"
version  = "2.0.19"
source   = "central+https://repo.maven.apache.org/maven2/"
checksum = "sha256:1d20cbfc8f97a719112a72c6d4c2323259d179a7478d1f694b54409d412bb731"
scopes   = ["main"]
deps = [
  "org.slf4j:slf4j-api:jar:@2.0.19",
]

[[module]]
path    = "."
group   = "com.example"
name    = "plain-cli"
version = "0.1.0"
java    = 25
