// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.command.toolchain;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermission;
import java.util.EnumSet;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledOnOs;
import org.junit.jupiter.api.condition.OS;
import org.junit.jupiter.api.io.TempDir;

@DisabledOnOs(OS.WINDOWS) // POSIX link/shim shapes; the Windows branch writes jkx.cmd instead.
class JkxLinkTest {

    @TempDir
    Path tmp;

    private Path bin() {
        return tmp.resolve("bin");
    }

    private Path fakeJk() throws IOException {
        Path bin = bin();
        Files.createDirectories(bin);
        Path jk = bin.resolve("jk");
        Files.writeString(jk, "#!/bin/sh\necho jk\n");
        Files.setPosixFilePermissions(
                jk,
                EnumSet.of(
                        PosixFilePermission.OWNER_READ,
                        PosixFilePermission.OWNER_WRITE,
                        PosixFilePermission.OWNER_EXECUTE));
        return jk;
    }

    @Test
    void creates_a_hardlink_next_to_jk() throws IOException {
        Path jk = fakeJk();
        JkxLink.Result r = JkxLink.ensure(bin(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CREATED);
        Path jkx = bin().resolve("jkx");
        assertThat(jkx).exists();
        assertThat(Files.isSameFile(jkx, jk)).isTrue();
    }

    @Test
    void second_ensure_is_a_cheap_no_op() throws IOException {
        Path jk = fakeJk();
        JkxLink.ensure(bin(), jk);
        JkxLink.Result r = JkxLink.ensure(bin(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CURRENT);
    }

    @Test
    void repairs_a_stale_shim_to_a_link() throws IOException {
        Path jk = fakeJk();
        Path jkx = bin().resolve("jkx");
        Files.writeString(
                jkx, "#!/bin/sh\n# jkx launcher (generated by jk; do not edit)\nexec \"/old/jk\" tool run \"$@\"\n");
        JkxLink.Result r = JkxLink.ensure(bin(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CREATED);
        assertThat(Files.isSameFile(jkx, jk)).isTrue();
    }

    @Test
    void repairs_a_broken_symlink() throws IOException {
        Path jk = fakeJk();
        Path jkx = bin().resolve("jkx");
        Files.createSymbolicLink(jkx, tmp.resolve("gone"));
        JkxLink.Result r = JkxLink.ensure(bin(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CREATED);
        assertThat(Files.isSameFile(jkx, jk)).isTrue();
    }

    /**
     * {@code <home>/bin} is jk's own directory, so whatever holds the {@code jkx} name is jk's to
     * replace — no header sniffing, no size cap. The sniffing this replaced existed because the
     * launchers used to go onto a shared PATH directory, where a name is not a claim.
     */
    @Test
    void replaces_an_unrecognized_file_at_the_jkx_name() throws IOException {
        Path jk = fakeJk();
        Path jkx = bin().resolve("jkx");
        Files.writeString(jkx, "#!/bin/sh\necho a stale jkx from an older jk\n");
        JkxLink.Result r = JkxLink.ensure(bin(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CREATED);
        assertThat(Files.isSameFile(jkx, jk)).isTrue();
    }

    @Test
    void skips_when_jk_exe_is_unresolvable() throws IOException {
        Path jk = fakeJk();
        assertThat(JkxLink.ensure(bin(), null).status()).isEqualTo(JkxLink.Status.SKIPPED_NO_EXE);
        assertThat(JkxLink.ensure(bin(), tmp.resolve("missing")).status()).isEqualTo(JkxLink.Status.SKIPPED_NO_EXE);
        assertThat(JkxLink.ensure(bin(), Path.of("jk")).status()).isEqualTo(JkxLink.Status.SKIPPED_NO_EXE);
    }
}
