// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.test;

import cc.jumpkick.lock.LockPaths;
import cc.jumpkick.lock.LockfileReader;
import cc.jumpkick.lock.ManifestPaths;
import cc.jumpkick.model.ToolDefaults;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.jspecify.annotations.Nullable;

/**
 * Writes the minimal {@code pom.xml} a {@code @QuarkusTest} bootstrap insists on.
 *
 * <p>This is not part of the {@code ##JKT:} fork protocol and shares no state with the launcher: it
 * runs once before the fork, reads {@code jk.toml} and {@code jk-lock.toml}, and writes a file. It
 * lived in {@code JUnitLauncher} only because that is who calls it, and a Maven POM writer sitting
 * inside the protocol reader is how the launcher grew past the cap.
 *
 * <p>The rule that must not be split is inside this file: <b>only ever replace a POM jk generated
 * itself</b> — recognised by the marker comment, an uninterpolated {@code ${group}}/{@code ${name}}
 * scaffold, or a floating {@code latest}/{@code snapshot} platform version. A user's own pom.xml is
 * theirs, and the check that decides that has to sit next to the write that would clobber it.
 */
final class QuarkusToolingPom {

    private QuarkusToolingPom() {}

    /**
     * Quarkus {@code @QuarkusTest} uses {@code BootstrapAppModelFactory} which needs a Maven
     * project root. JK owns resolve via {@code jk-lock.toml}; when the module has {@code [quarkus]} but
     * no {@code pom.xml}, write a minimal tooling POM (coordinates + platform BOM import only).
     */
    static void ensure(@Nullable Path moduleDir) {
        if (moduleDir == null || !Files.isDirectory(moduleDir)) return;
        Path pom = moduleDir.resolve("pom.xml");
        Path jkToml = moduleDir.resolve(ManifestPaths.MANIFEST);
        if (!Files.isRegularFile(jkToml)) return;
        try {
            String toml = Files.readString(jkToml);
            if (!Pattern.compile("(?m)^\\s*\\[quarkus]\\s*$").matcher(toml).find()) {
                return;
            }
            // Only ever replace a pom jk itself generated (the marker comment below) or a raw
            // scaffold whose ${group}/${name} placeholders never interpolated. A user's real
            // pom — even one using a ${quarkus.version} property — is theirs.
            if (Files.isRegularFile(pom)) {
                String existing = Files.readString(pom);
                boolean jkGenerated = existing.contains("Generated by jk for Quarkus");
                boolean rawScaffold = existing.contains("${group}") && existing.contains("${name}");
                boolean floatingPlatform =
                        existing.contains("<quarkus.platform.version>latest</quarkus.platform.version>")
                                || existing.contains("<quarkus.platform.version>snapshot</quarkus.platform.version>");
                if (!jkGenerated && !rawScaffold && !floatingPlatform) {
                    return;
                }
                // jk-generated poms are rewritten every time — cheap, and it keeps the
                // tooling pom in sync when [quarkus] version or coordinates change.
            }
            String group = tomlField(toml, "group", "com.example");
            String name = tomlField(toml, "name", moduleDir.getFileName().toString());
            String version = tomlField(toml, "version", "0.1.0");
            String qv = toolingBomVersion(moduleDir, toml);
            String xml = """
                    <?xml version="1.0" encoding="UTF-8"?>
                    <!-- Generated by jk for Quarkus @QuarkusTest tooling. Resolve is owned by jk-lock.toml. -->
                    <project xmlns="http://maven.apache.org/POM/4.0.0">
                      <modelVersion>4.0.0</modelVersion>
                      <groupId>%s</groupId>
                      <artifactId>%s</artifactId>
                      <version>%s</version>
                      <properties>
                        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                        <maven.compiler.release>17</maven.compiler.release>
                        <quarkus.platform.version>%s</quarkus.platform.version>
                      </properties>
                      <dependencyManagement>
                        <dependencies>
                          <dependency>
                            <groupId>io.quarkus.platform</groupId>
                            <artifactId>quarkus-bom</artifactId>
                            <version>${quarkus.platform.version}</version>
                            <type>pom</type>
                            <scope>import</scope>
                          </dependency>
                        </dependencies>
                      </dependencyManagement>
                      <dependencies>
                        <dependency>
                          <groupId>io.quarkus</groupId>
                          <artifactId>quarkus-rest</artifactId>
                        </dependency>
                        <dependency>
                          <groupId>io.quarkus</groupId>
                          <artifactId>quarkus-arc</artifactId>
                        </dependency>
                        <dependency>
                          <groupId>io.quarkus</groupId>
                          <artifactId>quarkus-junit5</artifactId>
                          <scope>test</scope>
                        </dependency>
                      </dependencies>
                    </project>
                    """.formatted(xmlEscape(group), xmlEscape(name), xmlEscape(version), xmlEscape(qv));
            Files.writeString(pom, xml);
        } catch (IOException ignored) {
            // best-effort; @QuarkusTest will fail with a clearer bootstrap error if missing
        }
    }

    private static String tomlField(String toml, String key, String def) {
        // Match `key = "value"` or `key = value` at line start (project / quarkus tables).
        Matcher m = Pattern.compile("(?m)^\\s*" + Pattern.quote(key) + "\\s*=\\s*\"([^\"]+)\"")
                .matcher(toml);
        if (m.find()) return m.group(1).trim();
        m = Pattern.compile("(?m)^\\s*" + Pattern.quote(key) + "\\s*=\\s*(\\S+)")
                .matcher(toml);
        if (m.find()) return m.group(1).trim().replace("\"", "");
        return def;
    }

    /**
     * The concrete {@code quarkus-bom} version for the tooling POM. Maven has no caret, so the
     * {@code [quarkus] version = "3"} floor jk recommends cannot go in as written — {@code
     * quarkus-bom:3} is a literal version that does not exist.
     *
     * <p>The lock wins: this POM exists so {@code @QuarkusTest}'s bootstrap agrees with the
     * classpath jk built, and {@code jk-lock.toml} is what jk built from. A concrete {@code
     * [quarkus] version} is next, then the fallback pin.
     */
    private static String toolingBomVersion(Path moduleDir, String toml) {
        String locked = lockedQuarkusVersion(moduleDir);
        if (locked != null) return locked;
        String declared = quarkusVersion(toml, null);
        if (declared != null && isConcreteVersion(declared)) return declared;
        return ToolDefaults.QUARKUS_TOOLING_BOM_VERSION;
    }

    /**
     * The Quarkus line {@code jk-lock.toml} pinned. The platform BOM and {@code io.quarkus:*}
     * share one version, so any locked core artifact answers it.
     */
    private static @Nullable String lockedQuarkusVersion(Path moduleDir) {
        try {
            Path lockFile = LockPaths.lockFile(moduleDir);
            if (!Files.isRegularFile(lockFile)) return null;
            for (var artifact : LockfileReader.read(lockFile).artifacts()) {
                if (artifact.name().startsWith("io.quarkus:quarkus-core:")) return artifact.version();
            }
        } catch (RuntimeException | IOException ignored) {
            // A malformed/absent lock just means we fall through to the declared version.
        }
        return null;
    }

    /**
     * True when {@code spec} is a version Maven can resolve as written: no selector syntax, and
     * specific enough to name a release rather than a line ({@code 3.38.0}, not {@code 3}).
     */
    private static boolean isConcreteVersion(String spec) {
        String v = spec.trim();
        if (v.startsWith("=")) v = v.substring(1).trim();
        if (v.isEmpty() || v.startsWith("^") || v.startsWith("~") || v.startsWith(">") || v.startsWith("<")) {
            return false;
        }
        if (v.contains(",") || v.equalsIgnoreCase("latest") || v.equalsIgnoreCase("snapshot")) return false;
        return v.indexOf('.') != v.lastIndexOf('.'); // at least major.minor.patch
    }

    private static @Nullable String quarkusVersion(String toml, @Nullable String def) {
        Matcher table = Pattern.compile("(?m)^\\s*\\[quarkus]\\s*$").matcher(toml);
        if (!table.find()) return def;
        // Scan only until the next table header — a `version` in a later table (e.g.
        // project version) must not become the platform BOM version.
        String rest = toml.substring(table.end());
        Matcher nextTable = Pattern.compile("(?m)^\\s*\\[").matcher(rest);
        if (nextTable.find()) rest = rest.substring(0, nextTable.start());
        Matcher m = Pattern.compile("(?m)^\\s*version\\s*=\\s*\"([^\"]+)\"").matcher(rest);
        if (m.find()) return m.group(1).trim();
        return def;
    }

    private static String xmlEscape(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
