// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.quarkus;

import cc.jumpkick.plugin.Plugin;
import cc.jumpkick.plugin.PluginManifest;
import cc.jumpkick.plugin.build.BuildPluginHarness;
import cc.jumpkick.plugin.build.In;
import cc.jumpkick.plugin.build.PackageContext;
import cc.jumpkick.plugin.build.PackageExtension;
import cc.jumpkick.plugin.build.PackageIo;
import cc.jumpkick.plugin.protocol.ProtocolWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.jar.Attributes;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * Quarkus build plugin (JK-1159/1160 MVP): {@code quarkus-fast-jar} packager.
 *
 * <p>MVP packaging is an uber-style fat jar of application classes + runtime deps. True Quarkus
 * MutableJar / augmentation (Jandex + generated bytecode) is a follow-up — this is enough for the
 * declarative BOM + {@code jk new --quarkus} dogfood path to package something executable when the
 * app uses a plain {@code main} (e.g. {@code Quarkus.run}).
 */
public final class QuarkusPlugin implements Plugin, PackageExtension {

    @Override
    public PluginManifest manifest() {
        return new PluginManifest("jk-quarkus", "##JKQ:");
    }

    @Override
    public int run(List<String> args, ProtocolWriter out) throws Exception {
        return BuildPluginHarness.run(this, args, out);
    }

    @Override
    public void pack(PackageContext ctx) {
        ctx.inputs(In.classes(), In.runtimeEntries(), In.config())
                .produce("quarkus-fast-jar", QuarkusPlugin::produceFastJar);
    }

    private static void produceFastJar(PackageIo io) throws Exception {
        String main = io.project().mainClass();
        if (main == null || main.isBlank()) {
            throw new IOException(
                    "quarkus packaging needs [application] main (e.g. Application with Quarkus.run)");
        }
        Path outJar = io.artifactPath();
        Files.createDirectories(outJar.getParent());
        io.label("package " + outJar.getFileName() + " (quarkus MVP fat-jar)");

        Manifest man = new Manifest();
        Attributes attrs = man.getMainAttributes();
        attrs.put(Attributes.Name.MANIFEST_VERSION, "1.0");
        attrs.put(Attributes.Name.MAIN_CLASS, main);
        attrs.putValue("Created-By", "jk-quarkus");
        attrs.putValue("Implementation-Title", io.project().name());
        attrs.putValue("Implementation-Version", io.project().version());

        Set<String> seen = new HashSet<>();
        try (OutputStream fos = Files.newOutputStream(outJar);
                JarOutputStream jos = new JarOutputStream(fos, man)) {
            Path classes = io.classesDir();
            if (Files.isDirectory(classes)) {
                addTree(jos, classes, seen);
            }
            for (PackageIo.RuntimeEntry entry : io.runtimeEntries()) {
                Path jar = entry.jar();
                if (jar == null || !Files.isRegularFile(jar)) continue;
                mergeJar(jos, jar, seen);
            }
        }
    }

    private static void addTree(JarOutputStream jos, Path root, Set<String> seen) throws IOException {
        Files.walkFileTree(root, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                String name = root.relativize(file).toString().replace('\\', '/');
                if (!seen.add(name)) return FileVisitResult.CONTINUE;
                jos.putNextEntry(new JarEntry(name));
                Files.copy(file, jos);
                jos.closeEntry();
                return FileVisitResult.CONTINUE;
            }
        });
    }

    private static void mergeJar(JarOutputStream jos, Path jar, Set<String> seen) throws IOException {
        try (ZipFile zf = new ZipFile(jar.toFile())) {
            var en = zf.entries();
            while (en.hasMoreElements()) {
                ZipEntry e = en.nextElement();
                if (e.isDirectory()) continue;
                String name = e.getName();
                if (name.startsWith("META-INF/MANIFEST.MF")) continue;
                if (name.startsWith("META-INF/INDEX.LIST")) continue;
                if (name.startsWith("META-INF/")
                        && (name.endsWith(".SF") || name.endsWith(".RSA") || name.endsWith(".DSA") || name.endsWith(".EC"))) {
                    continue;
                }
                if (!seen.add(name)) continue; // first-wins; app classes already added
                jos.putNextEntry(new JarEntry(name));
                try (var in = zf.getInputStream(e)) {
                    in.transferTo(jos);
                }
                jos.closeEntry();
            }
        }
    }
}
