// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.command;

import static org.assertj.core.api.Assertions.assertThat;

import cc.jumpkick.cli.tui.Glyphs;
import cc.jumpkick.model.command.Exit;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

/**
 * {@code jk format --check} exits 1 on drift, so its closing wedge has to agree with its
 * exit code — and, since JK-2477, has to say how many files the OpenRewrite pass never ran on
 * without changing any verdict.
 */
class FormatSummaryTest {

    @Test
    void check_on_drift_reads_as_a_failure_and_names_the_fix() {
        var summary = FormatCommand.summarize(true, 14, 1445, 0, 0, "took 7.0s");

        assertThat(summary.failed()).isTrue();
        assertThat(summary.body()).contains("14 files unformatted").contains("jk format");
    }

    @Test
    void check_on_a_clean_tree_is_a_success() {
        var summary = FormatCommand.summarize(true, 0, 1459, 0, 0, "took 7.0s");

        assertThat(summary.failed()).isFalse();
        assertThat(summary.body()).startsWith("Already formatted");
    }

    @Test
    void formatting_files_is_work_done_not_a_failure() {
        var summary = FormatCommand.summarize(false, 14, 1445, 0, 0, "took 4.5s");

        assertThat(summary.failed()).isFalse();
        assertThat(summary.body()).startsWith("Formatted 14 files");
    }

    @Test
    void errors_fail_in_both_modes() {
        assertThat(FormatCommand.summarize(true, 0, 10, 2, 0, "took 1s").failed())
                .isTrue();
        assertThat(FormatCommand.summarize(false, 3, 10, 2, 0, "took 1s").failed())
                .isTrue();
        assertThat(FormatCommand.summarize(false, 3, 10, 1, 0, "took 1s").body())
                .contains("1 error ");
    }

    /**
     * The count that used to be invisible. A file OpenRewrite cannot parse is neither clean nor an
     * error: it was Spotless-formatted but never import-shortened, and nothing the author can write
     * in that file clears it — so it appears in every wedge and fails none of them.
     */
    @Test
    void files_the_rewrite_pass_skipped_are_reported_without_changing_the_verdict() {
        var clean = FormatCommand.summarize(true, 0, 1459, 0, 105, "took 7.0s");
        assertThat(clean.failed())
                .as("an OpenRewrite printer defect is not the contributor's drift; --check still passes")
                .isFalse();
        assertThat(clean.body()).startsWith("Already formatted").contains("105 not import-shortened");

        var drift = FormatCommand.summarize(true, 14, 1445, 0, 105, "took 7.0s");
        assertThat(drift.failed()).isTrue();
        assertThat(drift.body()).contains("14 files unformatted").contains("105 not import-shortened");

        var applied = FormatCommand.summarize(false, 14, 1445, 0, 105, "took 4.5s");
        assertThat(applied.failed()).isFalse();
        assertThat(applied.body()).startsWith("Formatted 14 files").contains("105 not import-shortened");
    }

    /** Nothing skipped, nothing said: the clause must not appear as ", 0 …" on a healthy tree. */
    @Test
    void a_tree_with_nothing_skipped_says_nothing_about_it() {
        assertThat(FormatCommand.summarize(true, 0, 1459, 0, 0, "took 7.0s").body())
                .isEqualTo("Already formatted took 7.0s");
    }

    /**
     * The per-file line is the machine interface behind {@code fqcn-baseline.txt}'s {@code
     * ## unreachable-by-the-formatter} section: that section is regenerated by filtering these
     * lines, so the marker and the bare repo-relative path after it are a contract, not styling.
     * Changing either silently turns a generated allowlist back into a hand-curated one.
     */
    @Test
    void the_unparseable_line_is_a_marker_and_a_repo_relative_path() {
        Path project = Path.of("/w/proj");
        String line = FormatCommand.unparseableLine("/w/proj/src/main/java/A.java", project);

        assertThat(line.replaceAll("\u001B\\[[;\\d]*m", ""))
                .isEqualTo(Glyphs.cross() + " unparseable: src/main/java/A.java");
    }

    /**
     * A plan failure and {@code --check} drift must not arrive at the shell as the same number.
     * Drift exits with the worker's own {@code 1}; a plan that did not run to completion — since
     * JK-2474 that includes a worker that died mid-format — exits {@link Exit#SOFTWARE}. When these
     * two collapse onto one value, no script can tell "your files need formatting" from "the
     * formatter died", which is exactly the eight-meanings-for-one-integer problem {@code Exit} was
     * created to end.
     */
    @Test
    void a_failed_plan_and_check_drift_do_not_share_an_exit_code() {
        assertThat(FormatCommand.PLAN_FAILED).isEqualTo(Exit.SOFTWARE).isNotEqualTo(Exit.FAILURE);
    }

    @Test
    void one_file_is_singular() {
        assertThat(FormatCommand.summarize(true, 1, 0, 0, 0, "took 1s").body()).contains("1 file unformatted");
        assertThat(FormatCommand.summarize(false, 1, 0, 0, 0, "took 1s").body()).startsWith("Formatted 1 file ");
    }
}
