// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.command;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermission;
import java.util.EnumSet;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledOnOs;
import org.junit.jupiter.api.condition.OS;
import org.junit.jupiter.api.io.TempDir;

@DisabledOnOs(OS.WINDOWS) // POSIX link/shim shapes; the Windows branch writes jkx.cmd instead.
class JkxLinkTest {

    @TempDir
    Path tmp;

    private Path fakeJk() throws IOException {
        Path bin = tmp.resolve("bin");
        Files.createDirectories(bin);
        Path jk = bin.resolve("jk");
        Files.writeString(jk, "#!/bin/sh\necho jk\n");
        Files.setPosixFilePermissions(
                jk,
                EnumSet.of(
                        PosixFilePermission.OWNER_READ,
                        PosixFilePermission.OWNER_WRITE,
                        PosixFilePermission.OWNER_EXECUTE));
        return jk;
    }

    @Test
    void creates_a_hardlink_next_to_jk() throws IOException {
        Path jk = fakeJk();
        JkxLink.Result r = JkxLink.ensure(jk.getParent(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CREATED);
        Path jkx = jk.getParent().resolve("jkx");
        assertThat(jkx).exists();
        assertThat(Files.isSameFile(jkx, jk)).isTrue();
    }

    @Test
    void second_ensure_is_a_cheap_no_op() throws IOException {
        Path jk = fakeJk();
        JkxLink.ensure(jk.getParent(), jk);
        JkxLink.Result r = JkxLink.ensure(jk.getParent(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CURRENT);
    }

    @Test
    void repairs_a_stale_shim_to_a_link() throws IOException {
        Path jk = fakeJk();
        Path jkx = jk.getParent().resolve("jkx");
        Files.writeString(
                jkx, "#!/bin/sh\n# jkx launcher (generated by jk; do not edit)\nexec \"/old/jk\" tool run \"$@\"\n");
        JkxLink.Result r = JkxLink.ensure(jk.getParent(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CREATED);
        assertThat(Files.isSameFile(jkx, jk)).isTrue();
    }

    @Test
    void repairs_a_broken_symlink() throws IOException {
        Path jk = fakeJk();
        Path jkx = jk.getParent().resolve("jkx");
        Files.createSymbolicLink(jkx, tmp.resolve("gone"));
        JkxLink.Result r = JkxLink.ensure(jk.getParent(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.CREATED);
        assertThat(Files.isSameFile(jkx, jk)).isTrue();
    }

    @Test
    void leaves_a_foreign_file_untouched() throws IOException {
        Path jk = fakeJk();
        Path jkx = jk.getParent().resolve("jkx");
        String foreign = "#!/bin/sh\necho my own jkx\n";
        Files.writeString(jkx, foreign);
        JkxLink.Result r = JkxLink.ensure(jk.getParent(), jk);
        assertThat(r.status()).isEqualTo(JkxLink.Status.SKIPPED_FOREIGN);
        assertThat(Files.readString(jkx)).isEqualTo(foreign);
    }

    @Test
    void skips_when_jk_exe_is_unresolvable() throws IOException {
        Path jk = fakeJk();
        assertThat(JkxLink.ensure(jk.getParent(), null).status()).isEqualTo(JkxLink.Status.SKIPPED_NO_EXE);
        assertThat(JkxLink.ensure(jk.getParent(), tmp.resolve("missing")).status())
                .isEqualTo(JkxLink.Status.SKIPPED_NO_EXE);
        assertThat(JkxLink.ensure(jk.getParent(), Path.of("jk")).status()).isEqualTo(JkxLink.Status.SKIPPED_NO_EXE);
    }
}
