// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.test;

import static org.assertj.core.api.Assertions.assertThat;

import cc.jumpkick.model.ToolDefaults;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * The Quarkus tooling-pom writer must never destroy a user's own pom.xml, and must read the
 * platform version from the {@code [quarkus]} table only.
 */
class JUnitLauncherToolingPomTest {

    private static Path module(Path dir, String toml) throws IOException {
        Files.writeString(dir.resolve("jk.toml"), toml);
        return dir;
    }

    @Test
    void generates_tooling_pom_when_absent(@TempDir Path dir) throws IOException {
        module(dir, "group = \"com.acme\"\nname = \"svc\"\nversion = \"2.0\"\n\n[quarkus]\nversion = \"3.38.0\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        String pom = Files.readString(dir.resolve("pom.xml"));
        assertThat(pom).contains("Generated by jk for Quarkus");
        assertThat(pom).contains("<artifactId>svc</artifactId>");
        assertThat(pom).contains("<quarkus.platform.version>3.38.0</quarkus.platform.version>");
    }

    @Test
    void user_pom_with_quarkus_version_property_is_untouched(@TempDir Path dir) throws IOException {
        module(dir, "[quarkus]\nversion = \"3.38.0\"\n");
        String userPom = """
                <project>
                  <properties><quarkus.version>3.20.0</quarkus.version></properties>
                  <dependencyManagement><dependencies><dependency>
                    <groupId>io.quarkus</groupId><artifactId>quarkus-bom</artifactId>
                    <version>${quarkus.version}</version>
                  </dependency></dependencies></dependencyManagement>
                </project>
                """;
        Files.writeString(dir.resolve("pom.xml"), userPom);
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        assertThat(Files.readString(dir.resolve("pom.xml"))).isEqualTo(userPom);
    }

    @Test
    void raw_scaffold_and_jk_generated_poms_are_rewritten(@TempDir Path dir) throws IOException {
        module(dir, "name = \"svc\"\n\n[quarkus]\nversion = \"3.38.0\"\n");
        Files.writeString(
                dir.resolve("pom.xml"),
                "<project><groupId>${group}</groupId><artifactId>${name}</artifactId></project>");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        String rewritten = Files.readString(dir.resolve("pom.xml"));
        assertThat(rewritten).contains("Generated by jk for Quarkus").doesNotContain("${group}");

        // A jk-generated pom refreshes when [quarkus] version changes.
        module(dir, "name = \"svc\"\n\n[quarkus]\nversion = \"3.29.0\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        assertThat(Files.readString(dir.resolve("pom.xml"))).contains("3.29.0");
    }

    @Test
    void version_scan_stops_at_the_next_table(@TempDir Path dir) throws IOException {
        // [quarkus] has no version; a later table's version must not become the platform BOM
        // (e.g. io.quarkus.platform:quarkus-bom:0.1.0).
        module(dir, "name = \"svc\"\n\n[quarkus]\n\n[spring-boot]\nversion = \"0.1.0\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        String pom = Files.readString(dir.resolve("pom.xml"));
        assertThat(pom).doesNotContain("<quarkus.platform.version>0.1.0</quarkus.platform.version>");
        assertThat(pom)
                .contains("<quarkus.platform.version>" + ToolDefaults.QUARKUS_TOOLING_BOM_VERSION
                        + "</quarkus.platform.version>");
    }

    @Test
    void a_major_line_floor_never_reaches_the_pom_as_a_literal_version(@TempDir Path dir) throws IOException {
        // JK-1669: `version = "3"` is a caret floor in jk.toml. Maven has no caret, so writing it
        // through would import io.quarkus.platform:quarkus-bom:3 — a version that does not exist.
        module(dir, "name = \"svc\"\n\n[quarkus]\nversion = \"3\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        String pom = Files.readString(dir.resolve("pom.xml"));
        assertThat(pom).doesNotContain("<quarkus.platform.version>3</quarkus.platform.version>");
        assertThat(pom)
                .contains("<quarkus.platform.version>" + ToolDefaults.QUARKUS_TOOLING_BOM_VERSION
                        + "</quarkus.platform.version>");
    }

    @Test
    void the_lock_wins_over_the_declared_floor(@TempDir Path dir) throws IOException {
        // The pom exists so @QuarkusTest's bootstrap agrees with the classpath jk built, and
        // jk-lock.toml is what jk built from — so it outranks whatever jk.toml declares.
        module(dir, "name = \"svc\"\n\n[quarkus]\nversion = \"3\"\n");
        Files.writeString(dir.resolve("jk-lock.toml"), """
                version = 1
                generated-by = "jk test"
                resolution-algorithm = "pubgrub-v1"

                [[artifact]]
                name     = "io.quarkus:quarkus-core:jar:"
                version  = "3.41.2"
                source   = "central+https://repo.maven.apache.org/maven2/"
                checksum = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
                scopes   = ["main"]
                """);
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        assertThat(Files.readString(dir.resolve("pom.xml")))
                .contains("<quarkus.platform.version>3.41.2</quarkus.platform.version>");
    }

    @Test
    void commented_quarkus_table_does_not_trigger_pom_generation(@TempDir Path dir) throws IOException {
        module(dir, "#[quarkus]\nname = \"svc\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        assertThat(dir.resolve("pom.xml")).doesNotExist();
    }
}
