// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.test;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * The Quarkus tooling-pom writer must never destroy a user's own pom.xml, and must read the
 * platform version from the {@code [quarkus]} table only (JK-1211).
 */
class JUnitLauncherToolingPomTest {

    private static Path module(Path dir, String toml) throws IOException {
        Files.writeString(dir.resolve("jk.toml"), toml);
        return dir;
    }

    @Test
    void generates_tooling_pom_when_absent(@TempDir Path dir) throws IOException {
        module(dir, "[project]\ngroup = \"com.acme\"\nname = \"svc\"\nversion = \"2.0\"\n\n[quarkus]\nversion = \"3.28.5\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        String pom = Files.readString(dir.resolve("pom.xml"));
        assertThat(pom).contains("Generated by jk for Quarkus");
        assertThat(pom).contains("<artifactId>svc</artifactId>");
        assertThat(pom).contains("<quarkus.platform.version>3.28.5</quarkus.platform.version>");
    }

    @Test
    void user_pom_with_quarkus_version_property_is_untouched(@TempDir Path dir) throws IOException {
        module(dir, "[quarkus]\nversion = \"3.28.5\"\n");
        String userPom = """
                <project>
                  <properties><quarkus.version>3.20.0</quarkus.version></properties>
                  <dependencyManagement><dependencies><dependency>
                    <groupId>io.quarkus</groupId><artifactId>quarkus-bom</artifactId>
                    <version>${quarkus.version}</version>
                  </dependency></dependencies></dependencyManagement>
                </project>
                """;
        Files.writeString(dir.resolve("pom.xml"), userPom);
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        assertThat(Files.readString(dir.resolve("pom.xml"))).isEqualTo(userPom);
    }

    @Test
    void raw_scaffold_and_jk_generated_poms_are_rewritten(@TempDir Path dir) throws IOException {
        module(dir, "[project]\nname = \"svc\"\n\n[quarkus]\nversion = \"3.28.5\"\n");
        Files.writeString(dir.resolve("pom.xml"), "<project><groupId>${group}</groupId><artifactId>${name}</artifactId></project>");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        String rewritten = Files.readString(dir.resolve("pom.xml"));
        assertThat(rewritten).contains("Generated by jk for Quarkus").doesNotContain("${group}");

        // A jk-generated pom refreshes when [quarkus] version changes.
        module(dir, "[project]\nname = \"svc\"\n\n[quarkus]\nversion = \"3.29.0\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        assertThat(Files.readString(dir.resolve("pom.xml"))).contains("3.29.0");
    }

    @Test
    void version_scan_stops_at_the_next_table(@TempDir Path dir) throws IOException {
        // [quarkus] has no version; [project] below it does — the platform BOM must NOT
        // become io.quarkus.platform:quarkus-bom:0.1.0.
        module(dir, "[quarkus]\n\n[project]\nname = \"svc\"\nversion = \"0.1.0\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        String pom = Files.readString(dir.resolve("pom.xml"));
        assertThat(pom).contains("<quarkus.platform.version>3.28.5</quarkus.platform.version>");
    }

    @Test
    void commented_quarkus_table_does_not_trigger_pom_generation(@TempDir Path dir) throws IOException {
        module(dir, "#[quarkus]\n[project]\nname = \"svc\"\n");
        JUnitLauncher.ensureQuarkusToolingPom(dir);
        assertThat(dir.resolve("pom.xml")).doesNotExist();
    }
}
