// SPDX-License-Identifier: Apache-2.0

/**
 * Typed catalog of every structural guard: letters, task names, published table rows, and gate wiring.
 *
 * [tableMarkdown] is the source of the generated block in `docs/contributors/code-as-art.md`. Coverage, registry, and
 * parity checks read this object instead of grepping comment spellings.
 */
object Guards {

    val all: List<GuardSpec> =
        listOf(
            spec(
                0,
                "checkCorpus",
                "a scan reporting green over a corpus that has shrunk below the population it was measured against — module dirs, `src/main/java`, `src/test/java`, `plugins/*`. Not a rule about the code: a floor under the *other* guards",
                "subsumed: every rule reports the population it examined, so the floor is each rule's own",
                GuardHome.FOLDED,
                tableTask = "*(subsumed: each rule states its population)*",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                jkSide = "subsumed: each rule states its population",
            ),
            spec(
                1,
                "checkNoHandBuiltJavaBinary",
                "a hand-built `<javaHome>/bin/java` (use `JdkFingerprint`)",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a hand-built <javaHome>/bin/java (use JdkFingerprint.java)",
                guardTestId = "hand-built-java-binary",
            ),
            spec(
                2,
                "checkNoBareExitCode",
                "`System.exit` / `halt` with an integer literal (use `Exit`)",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on System.exit/halt with an integer literal (use Exit)",
                ruleId = "named-exit-codes",
            ),
            spec(
                3,
                "checkSingleXmlParserOwner",
                "an XML parser outside `cc.jumpkick.host.DomXml`, plus the six flags required inside it by name",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on an XML parser outside DomXml",
                ruleId = "xml-parser-owner",
            ),
            spec(
                4,
                "checkCliNoParseTypes",
                "the planned `org.tomlj` / `TomlValues` ban in `clients/cli/src/main/java` landed as two entries on the existing CLI guard rather than a new letter — one rule, one owner, no new task",
                "ban",
                GuardHome.FOLDED,
                tableTask = "*(folded into the `cli-no-parse-types` guard test)*",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                guardTestId = "cli-no-parse-types",
            ),
            spec(
                5,
                "checkWireProtocolPrefixPairs",
                "a `##JK*:` protocol prefix not named exactly twice",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a ##JK*: protocol prefix not named exactly twice",
                ruleId = "wire-prefix-pairs",
            ),
            spec(
                6,
                "checkOneDigestSurface",
                "a `MessageDigest` lookup outside `cc.jumpkick.host.Hashing`",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a MessageDigest lookup outside Hashing",
                ruleId = "one-digest-surface",
            ),
            spec(
                7,
                "checkSingleTruthSet",
                "a hand-rolled boolean truth set, true **or** false side (use `EnvValues.parseBool`)",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a hand-rolled boolean truth set (use EnvValues.parseBool)",
                guardTestId = "single-truth-set",
            ),
            spec(
                8,
                "checkSingleArchiveInstant",
                "an archive entry stamped outside `DeterministicZip`",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on an archive entry stamped outside DeterministicZip",
                ruleId = "archive-instant-owner",
            ),
            spec(
                9,
                "checkNoHandRolledHex",
                "a per-byte hex loop, or `java.util.HexFormat` outside `cc.jumpkick.host.Hashing` (use `Hashing.hex`)",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a per-byte hex loop or HexFormat outside Hashing",
                ruleId = "one-hex-spelling",
            ),
            spec(
                10,
                "checkFileSizeCaps",
                "growth past `size-baseline.txt` or over a language's hard cap",
                "ratchet",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when a file grows past size-baseline.txt or over its hard cap",
                ruleId = "file-size",
            ),
            spec(
                11,
                "checkNoFqcn",
                "a file gaining a fully-qualified class name (`fqcn-baseline.txt`)",
                "ratchet",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when a file gains a fully-qualified class name (fqcn-baseline.txt)",
                ruleId = "no-fqcn",
            ),
            spec(
                12,
                "checkNoBareTaskName",
                "a step name typed as a literal (use `TaskNames`)",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a step name typed as a literal (use TaskNames)",
                ruleId = "task-names",
            ),
            spec(
                13,
                "checkNoBareManifestName",
                "a jk file name typed as a literal (use `ManifestPaths`)",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a jk file name typed as a literal (use ManifestPaths)",
                ruleId = "manifest-names",
            ),
            spec(
                14,
                "ForecastKeyParityTest",
                "a forecast key hashing a different fact set than the build key",
                "ban",
                GuardHome.TEST,
                ownerPath = ":engine",
                tableTask = "*(guard test, `server/engine/src/guard`)*",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                guardTestId = "forecast-key-parity",
            ),
            spec(
                15,
                "checkNoBareTierName",
                "a cache-tier directory typed as a literal (use `CacheTree`)",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a cache-tier directory typed as a literal (use CacheTree)",
                ruleId = "cache-tiers",
            ),
            spec(
                16,
                "checkSingleCentralAddress",
                "a Central URL, its `repo1.maven.org` alias, or the repo name `central` typed as a literal (use `RepositorySpec`)",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a Central URL or repo name typed as a literal",
                ruleId = "repository-names",
            ),
            spec(
                17,
                "checkNoBareWireType",
                "a hyphenated wire message type typed as a literal (use `EngineProtocol`)",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a hyphenated wire message type typed as a literal",
                ruleId = "wire-types",
            ),
            spec(
                18,
                "checkNoBareTargetDir",
                "jk's build output directory typed as a literal (use `BuildLayout.TARGET`)",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on jk's build output directory typed as a literal",
                ruleId = "target-dir",
            ),
            spec(
                19,
                "checkPublishedPomCoordinates",
                "a generated POM naming a coordinate this build does not publish (`unspecified`, the `jk` fallback group, or an unpublished artifact in a group we do publish)",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a generated POM naming a coordinate this build does not publish",
                ruleId = "published-poms",
            ),
            spec(
                20,
                "checkSingleHostSurface",
                "an `os.name` read outside `cc.jumpkick.host.Os`, or a path separator outside `Classpaths` (`-cp`) and `SearchPath` (`PATH`)",
                "ban",
                GuardHome.SELF_HOSTED,
                description =
                    "Fail the build on an os.name read outside Os, or a classpath separator outside Classpaths",
                ruleId = "one-host-surface",
            ),
            spec(
                21,
                "checkOneJsonCodec",
                "a JSON escaper or an escape-decoding parser outside `cc.jumpkick.jsonl` — exempt by spec, so `MinimalToml.quote` beside `Jsonl.quote` passes",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a JSON escaper or parser outside cc.jumpkick.jsonl",
                guardTestId = "one-json-codec",
            ),
            spec(
                22,
                "IdeClientWiringTest",
                "an IDE client naming a command, verb, class or wire field that does not exist, or pinning `untilBuild` — five arms, each self-failing on an empty scan",
                "ban, no allowlist",
                GuardHome.TEST,
                ownerPath = ":cli",
                tableTask = "*(guard test, `clients/cli/src/guard`)*",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                guardTestId = "ide-client-wiring",
            ),
            spec(
                23,
                "checkNoOrphanTestTags",
                "a `@Tag` no test task runs, a tag no tier owns, or a `TestTiers` table that does not partition its own vocabulary — three arms, exhaustive over the 2⁴ tag subsets, plus an import-vs-literal blindness balance",
                "ban, two named fixture exceptions",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when a @Tag is run by no test task, or by more than one",
                engineCode = "tiers",
            ),
            spec(
                24,
                "checkSingleAotMarkerSpelling",
                "the `.noaot` refusal-marker suffix typed outside `cc.jumpkick.host.AotCacheFiles` — banned outright in `src/main/java`, and in `src/test/java` as a bare suffix (a whole fixture file name is allowed)",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when the .noaot refusal-marker suffix is typed outside AotCacheFiles",
                ruleId = "aot-marker",
            ),
            spec(
                25,
                "checkPluginFamily",
                "a plugin module whose family (SPI plugin vs forked worker, decided by the presence of `jk-plugin.toml`) disagrees with its wire-prefix wiring, or an SPI plugin reading a config key its `[schema]` does not declare — four arms, per module, each self-failing on an empty scan",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description =
                    "Fail the build when this module's family (SPI plugin vs forked worker) disagrees with its wiring",
                guardTestId = "plugin-family",
            ),
            spec(
                26,
                "checkPluginForkOwner",
                "a plugin forking a process outside `TaskExec.ToolRun.start()`",
                "ban, one commented file exemption (a container runtime named on `PATH`, which `ToolRun` cannot express yet)",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when a plugin hand-rolls a process fork instead of TaskExec.ToolRun",
                ruleId = "plugin-fork-owner",
            ),
            spec(
                27,
                "CliSourceRulesTest",
                "a `clients/cli` command inheriting stdio outside `CliOutput.handOffTerminal` — comment-blind, plus a self-fail arm on the owner still calling `inheritIO()`",
                "ban, no allowlist",
                GuardHome.TEST,
                ownerPath = ":cli",
                tableTask = "*(guard test, `clients/cli/src/guard`)*",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                guardTestId = "cli-stdio-handoff-owner",
            ),
            spec(
                28,
                "checkNoRetiredWireSpelling",
                "a retired wire-key spelling typed as a field key in production source",
                "ban, declared inputs + self-fail floors",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a retired wire-key spelling in production source",
                ruleId = "retired-wire-keys",
            ),
            spec(
                29,
                "checkWorkerOfflineFromSpec",
                "a `JK_OFFLINE` / offline-property read in worker sources (use `TaskExec.offline()`)",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a JK_OFFLINE read in worker sources (use TaskExec.offline())",
                ruleId = "worker-offline-from-spec",
            ),
            spec(
                30,
                "checkPropertiesStoreOwner",
                "a `Properties.store()` call in main sources (use `DeterministicProperties.render`)",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description =
                    "Fail the build on a Properties.store() call in main sources (use DeterministicProperties.render)",
                ruleId = "properties-render-owner",
            ),
            spec(
                31,
                "CliSourceRulesTest",
                "a `:cli` test reading the ambient state root without `@IsolatedState`",
                "ratchet",
                GuardHome.TEST,
                ownerPath = ":cli",
                tableTask = "*(guard test, `clients/cli/src/guard`)*",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                guardTestId = "cli-test-isolated-state",
            ),
            spec(
                32,
                "SpikeCacheTempDirTest",
                "a spike-cache test that does not root its project in a `@TempDir`",
                "ban, one env-gated exception",
                GuardHome.TEST,
                ownerPath = ":engine",
                tableTask = "*(guard test, `server/engine/src/guard`)*",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                guardTestId = "spike-cache-temp-dir",
            ),
            spec(
                33,
                "checkCatalogLockParity",
                "`gradle/libs.versions.toml` and `jk-lock.toml` disagreeing on a shared module version",
                "ban",
                GuardHome.SELF_HOSTED,
                description =
                    "Fail when gradle/libs.versions.toml and jk-lock.toml disagree on a shared module version",
                engineCode = "catalog-lock",
            ),
            spec(
                34,
                "checkTestFixturesStayOutOfProduction",
                "a `testFixtures(...)` dependency on a non-test configuration, or a test-fixtures/JUnit/AssertJ jar on the CLI's runtime classpath — scans every build script, plus a self-fail arm",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                attach = setOf(GuardAttach.CHECK),
                description =
                    "Fail when a testFixtures variant reaches a publication, a POM or a production configuration",
                ruleId = "test-fixtures-stay-out-of-production",
            ),
            spec(
                35,
                "checkTestPathsFromCheckoutRoot",
                "a test locating a checkout file from the working directory — `getProtectionDomain` outside `cc.jumpkick.testing.RepoRoot`, or a `user.dir` line escaping with `..`; comment-blind, plus a self-fail arm on the fixture's signatures",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when a test locates a checkout file from the working directory",
                ruleId = "test-paths-from-checkout-root",
            ),
            spec(
                36,
                "checkManifestDepParity",
                "a module whose `build.gradle.kts` and `jk.toml` declare different workspace dependencies, in either direction, including a Gradle `testFixtures(...)` edge with no `fixtures = true` twin — plus a self-fail arm on the project-path-to-artifact-name map",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when a module's Gradle and jk.toml workspace dependencies disagree",
                guardTestId = "manifest-dep-parity",
            ),
            spec(
                37,
                "checkOneRecursiveDelete",
                "a hand-rolled children-first delete outside `cc.jumpkick.host.PathUtil`, or `FOLLOW_LINKS` in any file that deletes — comment-blind, plus a self-fail arm on the owner still using `walkFileTree` and `NOFOLLOW_LINKS`",
                "ban; four commented exemptions, each a *selective* delete rather than a tree delete",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a hand-rolled recursive delete outside PathUtil",
                ruleId = "one-recursive-delete",
            ),
            spec(
                38,
                "checkToolchainEnvFromRequest",
                "a toolchain env var read straight from the daemon's own environment instead of the request (use `BuildEnv.forModule` / `ambient`) — `JK_JDK=temurin-21 jk build` was silently ignored, so which JDK you compiled against depended on how the resident engine happened to be started",
                "ban; `server/` + `shared/` main sources only (`clients/` is exempt by shape — there `System.getenv` **is** the request), one narrow in-scope exemption",
                GuardHome.SELF_HOSTED,
                description =
                    "Fail the build on a toolchain env var read from the daemon environment instead of the request",
                ruleId = "toolchain-env-from-request",
            ),
            spec(
                39,
                "checkCheapestRejectionFirst",
                "an `isRegularFile` filter placed before a free name-only predicate — the walk already read the attributes, and re-resolving the path costs 10.3 µs on NTFS against 1.0 on ext4",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when an isRegularFile filter is placed before a free name-only predicate",
                guardTestId = "cheapest-rejection-first",
            ),
            spec(
                40,
                "checkRunnableOwner",
                "a `Files.isExecutable` outside `PathUtil.isRunnable` — 33.4 µs on Windows against 0.52 on Linux, for a question Windows does not answer that way (there the extension decides)",
                "ban, one exemption (`ActionCache.executableBit`, which wants the bit itself)",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on Files.isExecutable outside PathUtil.isRunnable",
                ruleId = "runnable-owner",
            ),
            spec(
                41,
                "",
                "never allocated. Letters are issued when a guard lands; this one never was, and is not reusable. G44 briefly carried the same claim and was wrong: it is live in the self-hosted build.",
                "—",
                GuardHome.NEVER,
                tableTask = "—",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
            ),
            spec(
                42,
                "checkTreeCopyOwner",
                "a hand-rolled recursive copy outside `PathUtil.copyTree` — the mirror of G37 for the write direction; all twelve callers shared the same three defects (`createDirectories` per *file*, no byte-identity check, walk attributes discarded)",
                "ban, commented exemptions, each a copy deliberately not the owner's shape",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a hand-rolled recursive copy outside PathUtil.copyTree",
                ruleId = "tree-copy-owner",
            ),
            spec(
                43,
                "checkArchiveStreamOwner",
                "an archive byte sink that bypasses `DeterministicZip.archiveStream` / `newArchive` — `ZipOutputStream` inherits a 512-byte buffer, turning a 9 MB jar into ~18,000 `write(2)` calls where 64 KB gives ~143",
                "ban + self-fail on the owner still offering the sink",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on an archive byte sink that bypasses DeterministicZip",
                ruleId = "archive-stream-owner",
            ),
            spec(
                44,
                "checkBothBuildsSeeEveryModule",
                "a module `settings.gradle.kts` and the root `jk.toml` `[workspace]` do not both see — Gradle never builds it, or `jk build` never compiles it and `jk test` never runs its suite; plus a stale `singleBuildModules` exception that one of the builds has since picked up",
                "ban, one declared single-build exception (`clients/intellij`)",
                GuardHome.SELF_HOSTED,
                tableTask = "`both-builds-see-modules` (jk-guards.toml, `parity`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "both-builds-see-modules",
            ),
            spec(
                45,
                "checkBlindWalkRatchet",
                "a module gaining a blind `Files.walk` / `walkFileTree` / `newDirectoryStream` / `list` in `src/main/java` (prefer `PathUtil.forEachRegularFile`, which hands the walk's attributes to the visitor)",
                "ratchet against `walk-baseline.txt`; a module may only shrink",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when a module gains a blind tree walk in src/main/java",
                ruleId = "blind-tree-walks",
            ),
            spec(
                46,
                "checkJdkRemovalConfined",
                "JDK removal reachable from anything but an explicit `jk jdk` verb — an ordinary build deleted the JDK it was running on, twice in one afternoon, taking four installs including both GraalVMs",
                "ban + self-fail on `JdkGarbage` still carrying the members it reads",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when JDK removal is reachable from anything but an explicit jk jdk verb",
                ruleId = "jdk-removal-confined",
            ),
            spec(
                47,
                "checkCaseConversionLocale",
                "a `toLowerCase()` / `toUpperCase()` in `src/main` without `Locale.ROOT` — under tr_TR/az `'i' ⇄ 'I'` do not round-trip, so an identifier parser is wrong for an entire locale family; one silently rewrote an MCP client's `runtime` scope into `main`",
                "ban + a self-fail arm on scanning zero files",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a locale-less toLowerCase()/toUpperCase() in src/main",
                ruleId = "case-conversion-locale",
            ),
            spec(
                48,
                "checkNoGluedInlineTag",
                "an inline Javadoc tag glued to its payload (`{@code.asc}`) — renders as literal garbage, and blocks FQCN shortening for the whole file",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a glued Javadoc inline tag",
                ruleId = "no-glued-inline-tag",
            ),
            spec(
                49,
                "checkSingleHomeRoot",
                "a path spelling from the pre-`~/.jk` layout, or a retired per-role `JK_*_DIR`, anywhere a reader can see it — sources, tests, docs and installers, deliberately **not** comment-blind, since comments are the surface being protected; extension-blind like G50; self-fail arms: stale allowlist entry, fixture set no longer caught, marker isolation, empty candidate set",
                "ban; nine-file allowlist, each entry carrying the reason it reads another program's layout",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on an old-layout path or a retired JK_*_DIR spelling",
                ruleId = "single-home-root",
            ),
            spec(
                50,
                "checkNoTicketIds",
                "a KanArtist ticket id anywhere in the tree — extension-blind, because every scope this rule was given by extension is where it was missed next: `*.kts` held 153 after the first sweep reported clean, the web client's CSS/JS held ~50 after the second, and a Giter8 template wrote one into a user's own new project",
                "ban, two exemptions (`AGENTS.md`'s board protocol, this page's ban examples) + a self-fail on an empty candidate set",
                GuardHome.SELF_HOSTED,
                description = "Fail the build on a KanArtist ticket id anywhere in the tree",
                ruleId = "no-ticket-ids",
            ),
            spec(
                51,
                "checkGuardParity",
                "a guard letter enforced by one build and not the other — G46 through G50 lived on the Gradle side only, so `jk build` printed \"house rules clean\" while enforcing 36 of the 41 it claimed, and neither gate's count was wrong about itself. Deliberately implemented twice: a parity check only one build runs has the shape of the problem it prevents. The exception list is single-owner (`guard-parity.txt`), so a letter cannot be excused on one side and demanded on the other",
                "ban; exceptions carry the reason parity is impossible, and \"not ported yet\" is not one",
                GuardHome.ROOT,
                tableTask = "`checkGuardParity` (root project)",
                attach = emptySet(),
                description = "Fail when a guard letter is enforced by one build and not the other",
                ruleId = "guard-rules-registered",
                guardTestId = "guard-parity",
            ),
            spec(
                52,
                "checkTestTierDocs",
                "the contributor tier table differs from `TestTiers` task names, include/exclude tags, order, or `checkAll` membership",
                "exact generated-block comparison in both builds",
                GuardHome.SELF_HOSTED,
                description = "Fail when the documented test tiers differ from TestTiers",
                guardTestId = "test-tier-docs",
            ),
            spec(
                53,
                "checkNullMarkedApiPackages",
                "a production package in an enforced null-marked root (`shared/jk-api`, `shared/wire`, `shared/plugin-sdk`, `shared/core`) lacks package-level `@NullMarked` without a `NullMarking.excludedPackages` entry, an exclusion goes stale, or the measured 30-package corpus drifts",
                "ban, no allowlist",
                GuardHome.SELF_HOSTED,
                description = "Fail when an enforced null-marked package lacks package-level @NullMarked",
                ruleId = "null-marked-packages",
            ),
            spec(
                54,
                "checkPluginSdkBoundary",
                "a first-party plugin adds an unclassified project dependency, or an exception disappears without removing its allowlist row",
                "SDK/host baseline plus the current invariant table in `docs/contributors/plugins.md`; server dependencies are banned",
                GuardHome.SELF_HOSTED,
                description = "Reject unclassified plugin project dependencies and server runtime leaks",
                ruleId = "plugin-sdk-boundary",
            ),
            spec(
                55,
                "checkEngineConfigDocs",
                "the published engine-config tables differ from `EngineControls` keys, env names, defaults, or meaning",
                "exact generated-block comparison in both builds",
                GuardHome.SELF_HOSTED,
                description = "Fail when docs/user/engine.md differs from EngineControls",
                guardTestId = "engine-config-docs",
            ),
            spec(
                56,
                "checkBootstrapVersions",
                "the wrapper task version disagrees with `gradle-wrapper.properties`, or a `setup-node` step does not read `.nvmrc`",
                "exact version comparison in both builds",
                GuardHome.SELF_HOSTED,
                description = "Fail when Gradle wrapper versions or the Node pin disagree",
                ruleId = "wrapper-version-parity",
                guardTestId = "node-pin-parity",
            ),
            spec(
                57,
                "checkCiCadence",
                "nightly CI no longer runs `benchTest`, `coverageReport`, or the macOS/Windows product smoke; the branch gate loses the self-host job or its isolated `JK_HOME`; or the scheduled Gradle-vs-jk wall measurement stops running or stops keeping a machine-readable result",
                "workflow text scan in both builds",
                GuardHome.SELF_HOSTED,
                description =
                    "Fail when CI drops coverage, benches, OS smoke, the self-host job, or the wall measurement",
                guardTestId = "ci-cadence",
            ),
            spec(
                58,
                "checkSecurityDocs",
                "the security-reporting page, the GitHub `SECURITY.md` pointer, or the advisory URL is missing",
                "file and pointer scan in both builds",
                GuardHome.SELF_HOSTED,
                description = "Fail when security-reporting docs or the advisory URL drop",
                guardTestId = "security-docs",
            ),
            spec(
                59,
                "checkNoHistoricalNarration",
                "a comment or doc narrates a previous design instead of the current invariant",
                "phrase scan in both builds; AGENTS.md and comments.md exempt because they name the ban",
                GuardHome.SELF_HOSTED,
                description = "Fail when comments or docs narrate a previous design",
                ruleId = "no-historical-narration",
            ),
            spec(
                60,
                "checkOneJsonSplicer",
                "a JSON object spliced by hand in `src/main/java` — a closing brace chopped and appended to, or a literal `{` opened onto another object's tail — outside `Jsonl.append`",
                "ban in both builds; self-fail when the owner stops splicing or the scan sees too few sources",
                GuardHome.SELF_HOSTED,
                description = "Fail when a JSON object is spliced by hand outside Jsonl.append",
                ruleId = "one-json-splicer",
            ),
            spec(
                62,
                "checkShipLayoutAgrees",
                "the two builds and `install.sh` disagree on the ship layout's engine directory",
                "compare the directory name in both builds and the installer; self-fail when an anchor stops matching",
                GuardHome.SELF_HOSTED,
                description = "Fail when the two builds and install.sh disagree on the ship layout",
                ruleId = "ship-layout-installer-gradle",
            ),
            spec(
                63,
                "checkCuratedIntegration",
                "a curated integration entry that is missing, renamed, untagged, tagged into a nightly tier, or claims a failure path the class does not show — plus a surface with only happy paths, a branch gate that stopped running the lane, and a nightly that stopped running the full tier",
                "registry scan in both builds, floored on the integration population it is carved out of",
                GuardHome.SELF_HOSTED,
                description = "Fail when the curated integration registry, its coverage, or its CI job drifts",
                guardTestId = "curated-integration",
            ),
            spec(
                64,
                "checkNoDisabledCompile",
                "a disabled `JavaCompile` task, which takes its source set out of every gate while the build stays green — the tests it would compile report `NO-SOURCE` and the tier prints \"did not run\"",
                "ban; self-fail when the module has no compile tasks to scan",
                GuardHome.MODULE,
                attach = setOf(GuardAttach.CHECK),
                description = "Fail when a JavaCompile task in this module is disabled",
                jkSide = "Gradle-only: task-graph state",
            ),
            spec(
                65,
                "checkNoLinkFollowingDelete",
                "build logic deleting or sizing a tree with a walk that follows symbolic links — Kotlin's `File.deleteRecursively`, `walkTopDown`, `walkBottomUp` and `File.walk`, or `FOLLOW_LINKS` — anywhere but `buildSrc/src/main/kotlin/Trees.kt`",
                "ban in both builds, comment- and string-blind; self-fail when the owner stops using `walkFileTree` or the scan sees too few build files",
                GuardHome.SELF_HOSTED,
                description = "Fail when build logic deletes or sizes a tree through symbolic links",
                ruleId = "no-link-following-delete",
            ),
            spec(
                66,
                "checkPackageModuleOwnership",
                "a production package declared by two or more modules without a `package-owners.txt` row naming the pair and why it is legal — package-private reach works across a jar boundary on a flat classpath and stops working under JPMS, so a split package is latent breakage that grows quietly",
                "ratchet, single-owner allowlist (`package-owners.txt`)",
                GuardHome.SELF_HOSTED,
                description =
                    "Fail when a production package is declared by more than one module without an allowlist row",
                ruleId = "one-module-per-package",
            ),
            spec(
                67,
                "checkPackageCycleBand",
                "a module's production packages sitting in a package-import cycle growing past its `cycle-baseline.txt` band — and a module that improves without tightening its line, because a number nobody banks stops meaning anything. Reports component membership, never cycle paths: a 15-package component has thousands of elementary cycles and none of them says which edge to cut",
                "ratchet, both directions (`cycle-baseline.txt`)",
                GuardHome.SELF_HOSTED,
                description = "Fail when a module's package-cycle count leaves its cycle-baseline.txt band",
                ruleId = "package-cycles",
            ),
            spec(
                68,
                "checkXmlParserHardening",
                "the six XXE flags inside `DomXml.hardened`, each by name — the only XXE posture jk has",
                "count, exactly six",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when one of DomXml's six XXE hardening flags is gone",
                ruleId = "xml-parser-hardening",
            ),
            spec(
                69,
                "checkOwnAlgorithmByName",
                "jk's own digest algorithm spelled at a `Hashing` door (`newDigest` / `fileHex` / `hashHex`) instead of `newSha256` / `sha256Hex`",
                "ban, owner exempt",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when jk's own algorithm name is passed to a Hashing algorithm door",
                ruleId = "own-algorithm-by-name",
            ),
            spec(
                70,
                "checkCentralAddress",
                "Maven Central addressed by its alias host or by a hand-typed URL outside `RepositorySpec.MAVEN_CENTRAL`",
                "ban, foreign-build readers allowed",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when Maven Central is addressed outside RepositorySpec",
                ruleId = "central-address",
            ),
            spec(
                71,
                "checkSpaNoClassKey",
                "`class` read as a field key in the dashboard SPA (the wire says `testClass`)",
                "ban, SPA assets only",
                GuardHome.SELF_HOSTED,
                description = "Fail the build when the SPA reads a `class` field key",
                ruleId = "spa-no-class-key",
            ),
            spec(
                72,
                "checkCharterTableParity",
                "the size caps code-as-art.md states and the caps `[guards.file-size]` enforces disagreeing, or the charter's Contents list drifting from its headings",
                "parity, self-hosted build only",
                GuardHome.SELF_HOSTED,
                tableTask = "*(guard test, `server/guard/src/guard`)*",
                description =
                    "Fail the build when the charter's size table or Contents list drifts from what the rules enforce",
                guardTestId = "charter-parity",
            ),
            spec(
                61,
                "checkInstallTestsRedirectM2",
                "a test that runs the install verb without `--m2-dir`, which publishes the fixture into the developer's real `~/.m2`",
                "ban in both builds; self-fail when the scan stops finding install invocations",
                GuardHome.SELF_HOSTED,
                description = "Fail when a test runs the install verb without --m2-dir",
                ruleId = "install-tests-redirect-m2",
            ),
            spec(
                81,
                "checkPublishedInstallers",
                "`hosting/public/install.sh` differing from the repo-root copy — served to `curl | bash` users, so a stale copy installs jk where the CLI does not look",
                "parity, line sets of the two copies (Gradle: byte identity)",
                GuardHome.SELF_HOSTED,
                description = "Fail when hosting/public installers have drifted from the repo-root copies",
                ruleId = "published-installer-sh",
            ),
            spec(
                82,
                "published-installer-ps1",
                "`hosting/public/install.ps1` differing from the repo-root copy — the PowerShell half of G81",
                "parity, line sets of the two copies",
                GuardHome.SELF_HOSTED,
                tableTask = "`published-installer-ps1` (jk-guards.toml, `parity`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "published-installer-ps1",
            ),
            spec(
                73,
                "checkCliRuntimeClasspath",
                "maven-artifact, plexus-utils, jline, test-fixtures or a test/analysis framework on the CLI runtime classpath",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail when the CLI runtime classpath contains plugin-sdk, test-fixtures or JUnit",
                ruleId = "cli-runtime-classpath",
            ),
            spec(
                74,
                "checkCliRuntimeModules",
                "a CLI workspace edge to an engine-side module (plugin-sdk, guard, resolver) — the same `checkCliRuntimeClasspath` task on the Gradle side, a `layers` rule here",
                "ban",
                GuardHome.FOLDED,
                tableTask = "*(folded into `cli-runtime-modules`)*",
                inFastGate = false,
                attach = emptySet(),
                ruleId = "cli-runtime-modules",
            ),
            spec(
                75,
                "ship-layout-installer-jk",
                "`install.sh` and jk's dist script (`.jk/after-build-dist.kts`) disagreeing on the ship layout's engine directory — G62's third anchor, one `parity` rule per pair",
                "parity, two extractions must agree",
                GuardHome.SELF_HOSTED,
                tableTask = "`ship-layout-installer-jk` (jk-guards.toml, `parity`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "ship-layout-installer-jk",
            ),
            spec(
                76,
                "guard-registry-doc",
                "the declarative rules' registry block in `docs/contributors/code-as-art.md` not being what `jk-guards.toml` renders (id, kind, why)",
                "generated, rendered from `guard-ids`",
                GuardHome.SELF_HOSTED,
                tableTask = "`guard-registry-doc` (jk-guards.toml, `generated`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "guard-registry-doc",
            ),
            spec(
                77,
                "checkStageDocs",
                "a doc publishing a stage list that is not `BuildStage`'s wire values in pipeline order — `machine-output.md` is a contract consumers integrate against",
                "generated list, read off the enum",
                GuardHome.SELF_HOSTED,
                description = "Fail when a doc's stage list differs from BuildStage",
                guardTestId = "stage-docs",
            ),
            spec(
                78,
                "checkDocLinks",
                "a relative link under `docs/` that resolves to nothing — code spans and fenced blocks are prose, not navigation",
                "ban",
                GuardHome.SELF_HOSTED,
                description = "Fail when a docs/ link points at nothing",
                guardTestId = "doc-links-resolve",
            ),
            spec(
                79,
                "checkGuardRegistry",
                "the guard registry table in `code-as-art.md` not listing exactly the letters `Guards.kt` declares, or a `ruleId` / `guardTestId` naming a rule that does not exist",
                "generated table (Gradle renders the cells; jk checks the letters and the ids)",
                GuardHome.ROOT,
                tableTask = "`checkGuardRegistry` (root project) + guard test `guard-letters-registry`",
                attach = emptySet(),
                description = "Fail when code-as-art.md's guard table differs from Guards",
                guardTestId = "guard-letters-registry",
            ),
            spec(
                80,
                "no-agent-trailers",
                "a commit message carrying a tool's co-author, generator or assistant trailer — refused at the commit boundary by the `commit-msg` hook `jk guard hooks install` writes",
                "commit rule, forbid-trailers globs; CI's history scan is the other half",
                GuardHome.SELF_HOSTED,
                tableTask =
                    "`no-agent-trailers` (jk-guards.toml, `commit`) + `scripts/check-no-agent-attribution.sh` (CI)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "no-agent-trailers",
            ),
            spec(
                83,
                "guard-kinds-doc",
                "the kinds table in `docs/user/guards.md` not being what the loader's kind list renders",
                "generated, rendered from `guard-kinds`",
                GuardHome.SELF_HOSTED,
                tableTask = "`guard-kinds-doc` (jk-guards.toml, `generated`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "guard-kinds-doc",
            ),
            spec(
                task = "checkGateCoverage",
                rule = "a structural guard is not reachable from checkFast",
                form = "scheduled-graph comparison",
                home = GuardHome.ROOT,
                attach = emptySet(),
                description = "Fail when a structural guard is not reachable from checkFast",
            ),
            spec(
                84,
                "guard-schemas-doc",
                "the key tables in `docs/user/guards.md` not being what the loader's `KeySpec` tables render",
                "generated, rendered from `guard-schemas`",
                GuardHome.SELF_HOSTED,
                tableTask = "`guard-schemas-doc` (jk-guards.toml, `generated`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "guard-schemas-doc",
            ),
            spec(
                85,
                "schema-freeze",
                "an external format constant (`Lockfile.CURRENT_VERSION`, `EngineProtocol.PROTOCOL`, MCP / JSONL / transcript `SCHEMA`) not equal to 1 before 1.0",
                "text, exactly five `= 1` constants across the named owners",
                GuardHome.SELF_HOSTED,
                tableTask = "`schema-freeze` (jk-guards.toml, `text`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "schema-freeze",
            ),
            spec(
                86,
                "lock-version-is-one",
                "a committed `jk-lock.toml` whose `version` is not 1",
                "text, max 0 matches over every lock in the tree",
                GuardHome.SELF_HOSTED,
                tableTask = "`lock-version-is-one` (jk-guards.toml, `text`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "lock-version-is-one",
            ),
            spec(
                87,
                "no-retired-code-markers",
                "`@Deprecated` or `@SuppressWarnings(\"unused\")` in main code — a dual path or a parked helper the charter says to delete on touch",
                "text, max 0 matches over `**/src/main/**/*.java`",
                GuardHome.SELF_HOSTED,
                tableTask = "`no-retired-code-markers` (jk-guards.toml, `text`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "no-retired-code-markers",
            ),
            spec(
                88,
                "method-size",
                "a method or constructor body over 120 code lines in main, test or fixture Java — the file cap alone let 34 members pass 150 inside files parked under 800",
                "metric, `lines` per method, baselined and tightened on every build",
                GuardHome.SELF_HOSTED,
                tableTask = "`method-size` (jk-guards.toml, `metric`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "method-size",
            ),
            spec(
                89,
                "catalog-is-the-version-source",
                "a literal `group:artifact:version` coordinate in a Gradle script — every pin lives in gradle/libs.versions.toml, which the lockfiles and verification metadata are written from",
                "text, `**/*.gradle.kts`, code only",
                GuardHome.SELF_HOSTED,
                tableTask = "`catalog-is-the-version-source` (jk-guards.toml, `text`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "catalog-is-the-version-source",
            ),
            spec(
                90,
                "clock-owner",
                "a wall-clock or monotonic read (System.currentTimeMillis, System.nanoTime, Instant.now) outside cc.jumpkick.host.time — a time the caller cannot move is a test that has to sleep",
                "forbid, baselined at the swept count and tightened on every build",
                GuardHome.SELF_HOSTED,
                tableTask = "`clock-owner` (jk-guards.toml, `forbid`)",
                inFastGate = false,
                gradleLetter = false,
                attach = emptySet(),
                ruleId = "clock-owner",
            ),
            spec(
                91,
                "checkCoverageBand",
                "a module's unit-test line coverage falling below its `coverage-baseline.txt` line — and an improvement that is not banked, because a number nobody tightens stops meaning anything",
                "ratchet, one line per module (`coverage-baseline.txt`); nightly, with the JaCoCo agent",
                GuardHome.ROOT,
                inFastGate = false,
                description =
                    "Fail when a module's unit-test line coverage falls below its coverage-baseline.txt line; bank an improvement",
            ),
        )

    val tableRows: List<GuardSpec>
        get() = all.filter { it.inTable }.sortedBy { it.letter }

    val gradleLetters: Set<Int>
        get() = all.mapNotNull { spec -> spec.letter.takeIf { spec.gradleLetter } }.toSortedSet()

    /** Letter → the `jk-guards.toml` rule id that enforces it on the self-hosted side. */
    val tomlLetters: Map<Int, String>
        get() = all.filter { it.letter != null && it.ruleId != null }.associate { it.letter!! to it.ruleId!! }

    /** Letter → the engine validation code that enforces it on the self-hosted side. */
    val engineLetters: Map<Int, String>
        get() = all.filter { it.letter != null && it.engineCode != null }.associate { it.letter!! to it.engineCode!! }

    /** Letter → the `@Guard` id that enforces it on the self-hosted side. */
    val guardTestLetters: Map<Int, String>
        get() = all.filter { it.letter != null && it.guardTestId != null }.associate { it.letter!! to it.guardTestId!! }

    fun named(task: String): GuardSpec =
        all.singleOrNull { it.task == task && it.registers } ?: error("No Gradle guard task named '$task' in Guards")

    fun letter(n: Int): GuardSpec =
        tableRows.singleOrNull { it.letter == n } ?: error("No published guard letter G$n in Guards")

    /**
     * The published table. [kinds] is rule id → `kind` from `jk-guards.toml`, so a letter's jk side reads as the TOML
     * kind that enforces it; a letter with no jk side says why in [GuardSpec.jkSide].
     */
    fun tableMarkdown(kinds: Map<String, String> = emptyMap()): String = buildString {
        appendLine("<!-- guards:start -->")
        appendLine("| id | task | rule | form | jk side |")
        appendLine("|---|---|---|---|---|")
        tableRows.forEach { spec ->
            val jkRule =
                spec.ruleId?.let { id -> kinds[id]?.let { "`$id` ($it)" } ?: "`$id`" }
                    ?: spec.engineCode?.let { "engine validation `$it`" }
                    ?: spec.guardTestId?.let { "guard test `$it`" }
                    ?: spec.jkSide
                    ?: "—"
            appendLine("| G${spec.letter} | ${spec.tableTaskCell} | ${spec.rule} | ${spec.form} | $jkRule |")
        }
        append("<!-- guards:end -->")
    }

    private fun spec(
        letter: Int? = null,
        task: String,
        rule: String,
        form: String,
        home: GuardHome,
        ownerPath: String? = null,
        attach: Set<GuardAttach> = defaultAttach(home),
        inFastGate: Boolean = defaultInFastGate(home),
        gradleLetter: Boolean = defaultGradleLetter(letter, home),
        inTable: Boolean = letter != null,
        tableTask: String? = null,
        mavenPublishOnly: Boolean = false,
        description: String = "",
        ruleId: String? = null,
        engineCode: String? = null,
        guardTestId: String? = null,
        jkSide: String? = null,
    ): GuardSpec =
        GuardSpec(
            letter = letter,
            task = task,
            rule = rule,
            form = form,
            home = home,
            ownerPath = ownerPath,
            attach = attach,
            inFastGate = inFastGate,
            gradleLetter = gradleLetter,
            inTable = inTable,
            tableTask = tableTask,
            mavenPublishOnly = mavenPublishOnly,
            description = description,
            ruleId = ruleId,
            engineCode = engineCode,
            guardTestId = guardTestId,
            jkSide = jkSide,
        )

    private fun defaultAttach(home: GuardHome): Set<GuardAttach> =
        when (home) {
            GuardHome.MODULE,
            GuardHome.PLUGIN_MODULE,
            GuardHome.MODULE_OWNED -> setOf(GuardAttach.CHECK, GuardAttach.JAR)
            else -> emptySet()
        }

    private fun defaultInFastGate(home: GuardHome): Boolean =
        home == GuardHome.MODULE ||
            home == GuardHome.PLUGIN_MODULE ||
            home == GuardHome.ROOT ||
            home == GuardHome.MODULE_OWNED

    private fun defaultGradleLetter(letter: Int?, home: GuardHome): Boolean =
        letter != null && home != GuardHome.SELF_HOSTED && home != GuardHome.FOLDED && home != GuardHome.NEVER
}
