// SPDX-License-Identifier: Apache-2.0

// Shared conventions for jk's child-JVM worker modules (the "runner" plugins).
// Each worker jar is published to the local Maven repo so `jk sync` can pull it
// into the CAS, is launchable as thin jar + classpath sidecar (JK-1347), and ships
// an `installLocal` task that side-loads the freshly-built jar into ~/.jk/store.
// What stays in each worker's build.gradle.kts: its `description`, its
// `dependencies`, and optional codec-vendoring. The artifactId is always `jk-<projectName>`.

import java.io.File
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.security.MessageDigest

plugins {
    id("jk.java-conventions")
    `maven-publish`
}

// Coordinates + version must match cc.jumpkick.util.JkVersion.VERSION and the
// cc.jumpkick.engine.plugin.PluginJar registry (artifactId = jk-<projectName>).
group = "cc.jumpkick"
version = "0.10.1"

val workerArtifact = "jk-${project.name}"

publishing {
    publications {
        create<MavenPublication>("worker") {
            artifactId = workerArtifact
            from(components["java"])
        }
    }
}

tasks.jar {
    manifest {
        attributes(
                "Main-Class" to "cc.jumpkick.plugin.process.PluginMain",
                "Implementation-Title" to workerArtifact,
                "Implementation-Version" to project.version)
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude("META-INF/*.SF", "META-INF/*.RSA", "META-INF/*.DSA", "META-INF/*.EC")
}

/**
 * Collect jars for the thin-worker classpath sidecar: runtimeClasspath plus optional
 * `bundledCodec` (plugin-sdk is compileOnly+vendored on several workers — still list it so
 * a jar that lost PluginMain can fall back to -cp).
 */
fun workerClasspathJars(): List<File> {
    val seen = linkedSetOf<File>()
    configurations.findByName("runtimeClasspath")?.files?.forEach { f ->
        if (f.isFile && f.name.endsWith(".jar")) seen.add(f)
    }
    configurations.findByName("bundledCodec")?.files?.forEach { f ->
        if (f.isFile && f.name.endsWith(".jar")) seen.add(f)
    }
    return seen.toList()
}

/**
 * Write `<jar>.classpath` next to the worker jar listing runtimeClasspath (+ bundledCodec)
 * entries so PluginLaunch can `java -cp worker:deps… PluginMain` without fat-jarring (JK-1347).
 */
tasks.register("writeWorkerClasspath") {
    description = "Write .classpath sidecar for thin worker launch"
    group = "jk"
    dependsOn(tasks.jar)
    val jarProvider = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    val runtimeCp = configurations.named("runtimeClasspath")
    inputs.file(jarProvider)
    inputs.files(runtimeCp)
    configurations.findByName("bundledCodec")?.let { inputs.files(it) }
    doLast {
        val jar = jarProvider.get().asFile
        val side = File(jar.path + ".classpath")
        val lines = mutableListOf("# jk worker classpath — generated by writeWorkerClasspath")
        workerClasspathJars().forEach { f -> lines.add(f.absolutePath) }
        side.writeText(lines.joinToString("\n", postfix = "\n"))
    }
}

tasks.named("jar") { finalizedBy("writeWorkerClasspath") }

// Side-load the freshly-built worker jar into the developer's local Maven repo at
// ~/.jk/store/repos/local/cc/jumpkick/<artifact>/<version>/<artifact>-<version>.jar
// so PluginJar.locate finds the worker without requiring -Djk.<x>.plugin.jar.
// Also writes a .sha256 sidecar and the .classpath sidecar for thin launch.
tasks.register("installLocal") {
    description = "Side-load the freshly-built $workerArtifact jar into ~/.jk/store/repos/local/ (m2 layout)"
    group = "jk"
    dependsOn(tasks.jar, "writeWorkerClasspath")
    val jarProvider = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    val runtimeCp = configurations.named("runtimeClasspath")
    inputs.file(jarProvider)
    inputs.files(runtimeCp)
    configurations.findByName("bundledCodec")?.let { inputs.files(it) }
    val artifact = workerArtifact
    val ver = project.version.toString()
    doLast {
        val jar = jarProvider.get().asFile
        val digest = MessageDigest.getInstance("SHA-256").digest(jar.readBytes())
        val hex = digest.joinToString("") { "%02x".format(it.toInt() and 0xff) }
        val storeRoot: File = System.getenv("JK_STORE_DIR")?.let { File(it) }
                ?: System.getenv("JK_HOME")?.let { File(it).resolve("store") }
                ?: File(System.getProperty("user.home"), ".jk/store")
        // Engine also probes cache/repos/local — write both when store != cache layouts differ.
        // Primary: store/repos/local (see JkDirs / RepoArtifactStore).
        val repoDir = storeRoot.resolve("repos/local/cc/jumpkick/$artifact/$ver")
        repoDir.mkdirs()
        val target = repoDir.resolve("$artifact-$ver.jar")
        val sidecar = repoDir.resolve("$artifact-$ver.jar.sha256")
        jar.copyTo(target, overwrite = true)
        sidecar.writeText(hex)
        // Classpath sidecar: absolute paths (runtimeClasspath + bundledCodec).
        val depJars = workerClasspathJars()
        val cpLines = mutableListOf("# jk worker classpath — generated by installLocal")
        depJars.forEach { f -> cpLines.add(f.absolutePath) }
        File(target.path + ".classpath").writeText(cpLines.joinToString("\n", postfix = "\n"))
        // Mirror next to build jar for -Djk.*.plugin.jar test overrides.
        File(jar.path + ".classpath").writeText(cpLines.joinToString("\n", postfix = "\n"))
        // JK-1351: publishable flat coordinate closure (`<jar>.deps`) so a cold store can
        // provision the thin worker: external deps keep their Maven coordinates (fetched from
        // Central); project-built jars are staged into repos/local under cc.jumpkick:<base>:<ver>
        // so publish-maven-repo.sh ships them to the official repo.
        val externalByFile = runCatching {
            configurations.getByName("runtimeClasspath").resolvedConfiguration.resolvedArtifacts
                    .filter { it.id.componentIdentifier !is org.gradle.api.artifacts.component.ProjectComponentIdentifier }
                    .associateBy({ it.file }, { "${it.moduleVersion.id.group}:${it.moduleVersion.id.name}:${it.moduleVersion.id.version}" })
        }.getOrDefault(emptyMap())
        val depsLines = mutableListOf("# jk worker deps — flat runtime closure, group:artifact:version")
        depJars.forEach { f ->
            val external = externalByFile[f]
            if (external != null) {
                depsLines.add(external)
            } else {
                val noExt = f.name.removeSuffix(".jar")
                val tail = noExt.substringAfterLast('-')
                val base = if (tail.firstOrNull()?.isDigit() == true) noExt.substringBeforeLast('-') else noExt
                val d = storeRoot.resolve("repos/local/cc/jumpkick/$base/$ver")
                d.mkdirs()
                f.copyTo(d.resolve("$base-$ver.jar"), overwrite = true)
                val h = MessageDigest.getInstance("SHA-256").digest(f.readBytes())
                        .joinToString("") { "%02x".format(it.toInt() and 0xff) }
                d.resolve("$base-$ver.jar.sha256").writeText(h)
                depsLines.add("cc.jumpkick:$base:$ver")
            }
        }
        File(target.path + ".deps").writeText(depsLines.joinToString("\n", postfix = "\n"))
        // JK-1348: hard-link worker + deps into JK_LIB_DIR/<artifact>/ (default store/lib/).
        val libRoot: File = System.getenv("JK_LIB_DIR")?.let { File(it) }
                ?: storeRoot.resolve("lib")
        val libDir = libRoot.resolve(artifact)
        try {
            // Temp-dir + rename (JK-1353): concurrent launchers never observe a partial lib dir.
            libRoot.mkdirs()
            val tmpDir = Files.createTempDirectory(libRoot.toPath(), ".$artifact-tmp-").toFile()
            val order = mutableListOf<String>()
            fun linkOne(src: File) {
                if (!src.isFile) return
                var name = src.name
                var dest = tmpDir.resolve(name)
                var n = 2
                while (dest.exists()) {
                    val stem = src.nameWithoutExtension
                    val ext = src.extension.let { if (it.isEmpty()) "" else ".$it" }
                    name = "$stem-$n$ext"
                    dest = tmpDir.resolve(name)
                    n++
                }
                try {
                    Files.createLink(dest.toPath(), src.toPath())
                } catch (_: Exception) {
                    src.copyTo(dest, overwrite = true)
                }
                order.add(name)
            }
            linkOne(target)
            depJars.forEach { linkOne(it) }
            tmpDir.resolve(".classpath").writeText(
                    (listOf("# jk worker lib classpath — generated by installLocal") + order)
                            .joinToString("\n", postfix = "\n"))
            val oldDir = libRoot.resolve(".$artifact-old-${System.nanoTime()}")
            if (libDir.exists()) Files.move(libDir.toPath(), oldDir.toPath())
            try {
                Files.move(tmpDir.toPath(), libDir.toPath(), StandardCopyOption.ATOMIC_MOVE)
            } catch (_: AtomicMoveNotSupportedException) {
                Files.move(tmpDir.toPath(), libDir.toPath())
            }
            if (oldDir.exists()) oldDir.deleteRecursively()
            // Prefer lib-dir paths in the store sidecar when materialize succeeded.
            if (order.size > 1) {
                val libCp =
                        order.drop(1).map { libDir.resolve(it).absolutePath }
                val libLines = mutableListOf("# jk worker classpath — lib/<id> (JK-1348)")
                libLines.addAll(libCp)
                File(target.path + ".classpath").writeText(libLines.joinToString("\n", postfix = "\n"))
            }
            println("Installed $artifact $ver ${jar.length()} bytes (+ ${order.size - 1} classpath jars)")
            println("  sha256: $hex")
            println("  path:   $target")
            println("  lib:    $libDir")
        } catch (e: Exception) {
            println("Installed $artifact $ver ${jar.length()} bytes (+ ${cpLines.size - 1} classpath jars)")
            println("  sha256: $hex")
            println("  path:   $target")
            println("  lib:    (skipped: ${e.message})")
        }
    }
}
