// SPDX-License-Identifier: Apache-2.0

// Shared conventions for jk's child-JVM worker modules (the "runner" plugins).
// Each worker jar is published to the local Maven repo so `jk sync` can pull it
// into the CAS, is launchable as thin jar + classpath sidecar (JK-1347), and ships
// an `installLocal` task that side-loads the freshly-built jar into ~/.jk/store.
// What stays in each worker's build.gradle.kts: its `description`, its
// `dependencies`, and optional codec-vendoring. The artifactId is always `jk-<projectName>`.

import java.io.File
import java.security.MessageDigest

plugins {
    id("jk.java-conventions")
    `maven-publish`
}

// Coordinates + version must match cc.jumpkick.util.JkVersion.VERSION and the
// cc.jumpkick.engine.plugin.PluginJar registry (artifactId = jk-<projectName>).
group = "cc.jumpkick"
version = "0.10.1"

val workerArtifact = "jk-${project.name}"

publishing {
    publications {
        create<MavenPublication>("worker") {
            artifactId = workerArtifact
            from(components["java"])
        }
    }
}

tasks.jar {
    manifest {
        attributes(
                "Main-Class" to "cc.jumpkick.plugin.process.PluginMain",
                "Implementation-Title" to workerArtifact,
                "Implementation-Version" to project.version)
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude("META-INF/*.SF", "META-INF/*.RSA", "META-INF/*.DSA", "META-INF/*.EC")
}

/**
 * Write `<jar>.classpath` next to the worker jar listing runtimeClasspath entries so
 * PluginLaunch can `java -cp worker:deps… PluginMain` without fat-jarring (JK-1347).
 */
tasks.register("writeWorkerClasspath") {
    description = "Write .classpath sidecar for thin worker launch"
    group = "jk"
    dependsOn(tasks.jar)
    val jarProvider = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    val runtimeCp = configurations.named("runtimeClasspath")
    inputs.file(jarProvider)
    inputs.files(runtimeCp)
    doLast {
        val jar = jarProvider.get().asFile
        val side = File(jar.path + ".classpath")
        val lines = mutableListOf("# jk worker classpath — generated by writeWorkerClasspath")
        runtimeCp.get().files.filter { it.isFile && it.name.endsWith(".jar") }.forEach { f ->
            lines.add(f.absolutePath)
        }
        side.writeText(lines.joinToString("\n", postfix = "\n"))
    }
}

tasks.named("jar") { finalizedBy("writeWorkerClasspath") }

// Side-load the freshly-built worker jar into the developer's local Maven repo at
// ~/.jk/store/repos/local/cc/jumpkick/<artifact>/<version>/<artifact>-<version>.jar
// so PluginJar.locate finds the worker without requiring -Djk.<x>.plugin.jar.
// Also writes a .sha256 sidecar and the .classpath sidecar for thin launch.
tasks.register("installLocal") {
    description = "Side-load the freshly-built $workerArtifact jar into ~/.jk/store/repos/local/ (m2 layout)"
    group = "jk"
    dependsOn(tasks.jar, "writeWorkerClasspath")
    val jarProvider = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    val runtimeCp = configurations.named("runtimeClasspath")
    inputs.file(jarProvider)
    inputs.files(runtimeCp)
    val artifact = workerArtifact
    val ver = project.version.toString()
    doLast {
        val jar = jarProvider.get().asFile
        val digest = MessageDigest.getInstance("SHA-256").digest(jar.readBytes())
        val hex = digest.joinToString("") { "%02x".format(it.toInt() and 0xff) }
        val storeRoot: File = System.getenv("JK_STORE_DIR")?.let { File(it) }
                ?: System.getenv("JK_HOME")?.let { File(it).resolve("store") }
                ?: File(System.getProperty("user.home"), ".jk/store")
        // Engine also probes cache/repos/local — write both when store != cache layouts differ.
        // Primary: store/repos/local (see JkDirs / RepoArtifactStore).
        val repoDir = storeRoot.resolve("repos/local/cc/jumpkick/$artifact/$ver")
        repoDir.mkdirs()
        val target = repoDir.resolve("$artifact-$ver.jar")
        val sidecar = repoDir.resolve("$artifact-$ver.jar.sha256")
        jar.copyTo(target, overwrite = true)
        sidecar.writeText(hex)
        // Classpath sidecar: absolute paths from Gradle runtimeClasspath (dev-local).
        val cpLines = mutableListOf("# jk worker classpath — generated by installLocal")
        runtimeCp.get().files.filter { it.isFile && it.name.endsWith(".jar") }.forEach { f ->
            cpLines.add(f.absolutePath)
        }
        File(target.path + ".classpath").writeText(cpLines.joinToString("\n", postfix = "\n"))
        // Mirror next to build jar for -Djk.*.plugin.jar test overrides.
        File(jar.path + ".classpath").writeText(cpLines.joinToString("\n", postfix = "\n"))
        println("Installed $artifact $ver ${jar.length()} bytes (+ ${cpLines.size - 1} classpath jars)")
        println("  sha256: $hex")
        println("  path:   $target")
    }
}
