// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.tool;

import cc.jumpkick.jdk.HostPlatform;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.PosixFilePermission;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;

/**
 * Writes a launcher script for an application installed by {@code jk install} (the {@code make
 * install} step). Unlike {@link ToolLauncher} — which embeds CAS paths and writes {@code env.json}
 * — this launcher points at an explicit set of jars under {@code ~/.jk/lib} (the app jar plus
 * its hard-linked runtime dependencies, or a single fat jar).
 *
 * <p>The classpath is written out as an explicit jar list (not a {@code lib/*} glob) so
 * multiple installed apps sharing the flat lib directory never cross-contaminate each other's
 * classpath.
 */
public final class AppLauncher {

    private AppLauncher() {}

    /**
     * Write {@code ~/.jk/bin/<binName>} (POSIX) or {@code <binName>.cmd} (Windows) launching {@code
     * mainClass} with {@code classpathJars} on the classpath. Returns the launcher path.
     */
    public static Path install(Path binDir, Path javaHome, String binName, String mainClass, List<Path> classpathJars)
            throws IOException {
        Files.createDirectories(binDir);
        Path launcher = binDir.resolve(launcherFileName(binName));
        String script = renderScript(javaHome, mainClass, classpathJars);
        Files.writeString(
                launcher,
                script,
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING);
        markExecutable(launcher);
        return launcher;
    }

    /**
     * As {@link #install}, but launching a self-contained executable jar with {@code java -jar}
     * (shadow jars, Spring Boot jars — anything whose manifest carries its own entry point).
     */
    public static Path installJar(Path binDir, Path javaHome, String binName, Path jar) throws IOException {
        Files.createDirectories(binDir);
        Path launcher = binDir.resolve(launcherFileName(binName));
        String script = renderJarScript(javaHome, jar);
        Files.writeString(
                launcher,
                script,
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING);
        markExecutable(launcher);
        return launcher;
    }

    /** The launcher file name for {@code binName} on this platform. */
    public static String launcherFileName(String binName) {
        return binName + (HostPlatform.isWindows() ? ".cmd" : "");
    }

    /** Script content for a classpath launcher — what {@link #install} writes. */
    public static String renderScript(Path javaHome, String mainClass, List<Path> classpathJars) {
        return HostPlatform.isWindows()
                ? renderWindows(javaHome, mainClass, classpathJars)
                : renderPosix(javaHome, mainClass, classpathJars);
    }

    /** Script content for a self-contained-jar launcher — what {@link #installJar} writes. */
    public static String renderJarScript(Path javaHome, Path jar) {
        String java = javaBinary(javaHome).toString();
        return HostPlatform.isWindows()
                ? "@echo off\r\nREM Generated by jk install -- do not edit.\r\n\"" + java + "\" -jar \""
                        + jar.toAbsolutePath() + "\" %*\r\n"
                : "#!/usr/bin/env bash\n# Generated by jk install — do not edit. Re-run `jk install` to refresh.\n"
                        + "exec " + shellQuote(java) + " -jar "
                        + shellQuote(jar.toAbsolutePath().toString())
                        + " \"$@\"\n";
    }

    private static String renderPosix(Path javaHome, String mainClass, List<Path> cp) {
        StringBuilder sb = new StringBuilder();
        sb.append("#!/usr/bin/env bash\n");
        sb.append("# Generated by jk install — do not edit. Re-run `jk install` to refresh.\n");
        sb.append("exec ").append(shellQuote(javaBinary(javaHome).toString())).append(" \\\n");
        sb.append("  -cp ").append(shellQuote(joinClasspath(cp))).append(" \\\n");
        sb.append("  ").append(mainClass).append(" \"$@\"\n");
        return sb.toString();
    }

    private static String renderWindows(Path javaHome, String mainClass, List<Path> cp) {
        StringBuilder sb = new StringBuilder();
        sb.append("@echo off\r\n");
        sb.append("REM Generated by jk install -- do not edit.\r\n");
        sb.append('"').append(javaBinary(javaHome)).append('"');
        sb.append(" -cp \"").append(joinClasspath(cp)).append("\" ");
        sb.append(mainClass).append(" %*\r\n");
        return sb.toString();
    }

    private static Path javaBinary(Path javaHome) {
        return javaHome.resolve("bin").resolve(HostPlatform.isWindows() ? "java.exe" : "java");
    }

    private static String joinClasspath(List<Path> classpath) {
        String sep = HostPlatform.isWindows() ? ";" : ":";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < classpath.size(); i++) {
            if (i > 0) sb.append(sep);
            sb.append(classpath.get(i).toAbsolutePath());
        }
        return sb.toString();
    }

    private static String shellQuote(String value) {
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (!(Character.isLetterOrDigit(c) || c == '_' || c == '-' || c == '.' || c == '/' || c == ':')) {
                return "'" + value.replace("'", "'\\''") + "'";
            }
        }
        return value;
    }

    private static void markExecutable(Path file) {
        if (HostPlatform.isWindows()) return;
        try {
            Set<PosixFilePermission> perms = EnumSet.copyOf(Files.getPosixFilePermissions(file));
            perms.add(PosixFilePermission.OWNER_EXECUTE);
            perms.add(PosixFilePermission.GROUP_EXECUTE);
            perms.add(PosixFilePermission.OTHERS_EXECUTE);
            Files.setPosixFilePermissions(file, perms);
        } catch (UnsupportedOperationException | IOException ignored) {
            // Non-POSIX filesystem.
        }
    }
}
