// SPDX-License-Identifier: Apache-2.0
package cc.jumpkick.tool;

import cc.jumpkick.jdk.HostPlatform;
import cc.jumpkick.plugin.protocol.Jsonl;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.PosixFilePermission;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;

/**
 * Persistent launcher for {@code jk install} and ephemeral exec for {@code jk exec}. Layout:
 * {@code $JK_STATE_DIR/tools/envs/<bin>/env.json} + {@code $JK_BIN_DIR/<bin>} with absolute CAS
 * classpath.
 */
public final class ToolLauncher {

    private ToolLauncher() {}

    /**
     * Materialise {@code env} as an installed tool. Writes the launcher script under {@code binDir}
     * and the env metadata under {@code envsRoot/<binName>/env.json}. Idempotent.
     *
     * @return the launcher path the user should add to PATH.
     */
    public static Path install(Path envsRoot, Path binDir, Path javaHome, ToolEnv env) throws IOException {
        return install(envsRoot, binDir, javaHome, env, null, List.of());
    }

    /**
     * As {@link #install(Path, Path, Path, ToolEnv)}, additionally stamping {@code provenance}
     * into {@code env.json} and baking {@code jvmArgs} (e.g. a JBang alias's {@code java-options})
     * into the launcher's exec line.
     */
    public static Path install(
            Path envsRoot, Path binDir, Path javaHome, ToolEnv env, ToolProvenance provenance, List<String> jvmArgs)
            throws IOException {
        Path envDir = envsRoot.resolve(env.binName());
        Files.createDirectories(envDir);
        Files.createDirectories(binDir);

        Files.writeString(
                envDir.resolve("env.json"),
                renderEnvJson(env, javaHome, provenance, jvmArgs),
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING);

        Path launcher = binDir.resolve(env.binName() + (HostPlatform.isWindows() ? ".cmd" : ""));
        String script = HostPlatform.isWindows()
                ? renderWindowsLauncher(env, javaHome, jvmArgs)
                : renderPosixLauncher(env, javaHome, jvmArgs);
        Files.writeString(
                launcher,
                script,
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING);
        markExecutable(launcher);
        return launcher;
    }

    /**
     * Materialise a Kotlin-script tool ({@code jk tool install foo.kts}): same {@code env.json} +
     * launcher layout, but the launcher execs {@code kotlinc -script} over the env's snapshot copy
     * of the script instead of {@code java -cp}. {@code env.classpath()} carries the script's
     * resolved deps (and keeps them GC-reachable via env.json); {@code env.mainClass()} is the
     * {@code "kotlin-script"} sentinel.
     */
    public static Path installKotlinScript(
            Path envsRoot,
            Path binDir,
            Path javaHome,
            Path kotlincBin,
            Path script,
            ToolEnv env,
            ToolProvenance provenance)
            throws IOException {
        Path envDir = envsRoot.resolve(env.binName());
        Files.createDirectories(envDir);
        Files.createDirectories(binDir);
        Files.writeString(
                envDir.resolve("env.json"),
                renderEnvJson(env, javaHome, provenance, List.of()),
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING);

        Path launcher = binDir.resolve(env.binName() + (HostPlatform.isWindows() ? ".cmd" : ""));
        String cp = env.classpath().isEmpty() ? null : joinClasspath(env.classpath());
        String scriptBody;
        if (HostPlatform.isWindows()) {
            scriptBody = "@echo off\r\nREM Generated by jk install -- do not edit.\r\n\""
                    + kotlincBin + "\" -script \"" + script
                    + (cp != null ? "\" -classpath \"" + cp : "")
                    + "\" -- %*\r\n";
        } else {
            scriptBody = "#!/usr/bin/env bash\n# Generated by jk install — do not edit.\nexec "
                    + shellQuote(kotlincBin.toString()) + " -script " + shellQuote(script.toString())
                    + (cp != null ? " -classpath " + shellQuote(cp) : "")
                    + " -- \"$@\"\n";
        }
        Files.writeString(
                launcher,
                scriptBody,
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING);
        markExecutable(launcher);
        return launcher;
    }

    /**
     * Exec the env's main class in-process via {@link ProcessBuilder} (the {@code jk exec} path).
     * Returns the child's exit code.
     */
    public static int execEphemeral(Path javaHome, ToolEnv env, List<String> args)
            throws IOException, InterruptedException {
        return execEphemeral(javaHome, env, List.of(), args);
    }

    /** As above with explicit JVM args (a JBang alias's {@code java-options}). */
    public static int execEphemeral(Path javaHome, ToolEnv env, List<String> jvmArgs, List<String> args)
            throws IOException, InterruptedException {
        if (env.isNativeBinary()) {
            List<String> nativeCmd = new ArrayList<>();
            nativeCmd.add(env.classpath().getFirst().toAbsolutePath().toString());
            nativeCmd.addAll(args);
            return new ProcessBuilder(nativeCmd).inheritIO().start().waitFor();
        }
        List<String> cmd = new ArrayList<>();
        cmd.add(javaBinary(javaHome).toString());
        cmd.addAll(jvmArgs);
        cmd.add("-cp");
        cmd.add(joinClasspath(env.classpath()));
        cmd.add(env.mainClass());
        cmd.addAll(args);
        return new ProcessBuilder(cmd).inheritIO().start().waitFor();
    }

    private static Path javaBinary(Path javaHome) {
        String exe = HostPlatform.isWindows() ? "java.exe" : "java";
        return javaHome.resolve("bin").resolve(exe);
    }

    private static String joinClasspath(List<Path> classpath) {
        String sep = HostPlatform.isWindows() ? ";" : ":";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < classpath.size(); i++) {
            if (i > 0) sb.append(sep);
            sb.append(classpath.get(i).toAbsolutePath());
        }
        return sb.toString();
    }

    private static String renderPosixLauncher(ToolEnv env, Path javaHome, List<String> jvmArgs) {
        StringBuilder sb = new StringBuilder();
        sb.append("#!/usr/bin/env bash\n");
        sb.append("# Generated by jk install — do not edit.\n");
        sb.append("# Re-run `jk install ").append(env.primary().toGav()).append("` to refresh.\n");
        if (env.isNativeBinary()) {
            sb.append("exec ")
                    .append(shellQuote(
                            env.classpath().getFirst().toAbsolutePath().toString()))
                    .append(" \"$@\"\n");
            return sb.toString();
        }
        sb.append("exec ").append(shellQuote(javaBinary(javaHome).toString())).append(" \\\n");
        for (String a : jvmArgs) {
            sb.append("  ").append(shellQuote(a)).append(" \\\n");
        }
        sb.append("  -cp ").append(shellQuote(joinClasspath(env.classpath()))).append(" \\\n");
        sb.append("  ").append(env.mainClass()).append(" \"$@\"\n");
        return sb.toString();
    }

    private static String renderWindowsLauncher(ToolEnv env, Path javaHome, List<String> jvmArgs) {
        StringBuilder sb = new StringBuilder();
        sb.append("@echo off\r\n");
        sb.append("REM Generated by jk install -- do not edit.\r\n");
        if (env.isNativeBinary()) {
            sb.append('\"').append(env.classpath().getFirst().toAbsolutePath()).append("\" %*\r\n");
            return sb.toString();
        }
        sb.append('"').append(javaBinary(javaHome)).append('"');
        for (String a : jvmArgs) {
            sb.append(" \"").append(a).append('"');
        }
        sb.append(" -cp \"").append(joinClasspath(env.classpath())).append("\" ");
        sb.append(env.mainClass()).append(" %*\r\n");
        return sb.toString();
    }

    private static String renderEnvJson(ToolEnv env, Path javaHome, ToolProvenance provenance, List<String> jvmArgs) {
        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"binName\": ").append(jsonString(env.binName())).append(",\n");
        sb.append("  \"primary\": ").append(jsonString(env.primary().toGav())).append(",\n");
        sb.append("  \"mainClass\": ").append(jsonString(env.mainClass())).append(",\n");
        sb.append("  \"javaHome\": ")
                .append(jsonString(javaHome.toAbsolutePath().toString()))
                .append(",\n");
        sb.append("  \"classpath\": [\n");
        List<Path> cp = env.classpath();
        for (int i = 0; i < cp.size(); i++) {
            sb.append("    ").append(jsonString(cp.get(i).toAbsolutePath().toString()));
            if (i + 1 < cp.size()) sb.append(",");
            sb.append("\n");
        }
        sb.append("  ]");
        if (!jvmArgs.isEmpty()) {
            sb.append(",\n  \"jvmArgs\": [");
            for (int i = 0; i < jvmArgs.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(jsonString(jvmArgs.get(i)));
            }
            sb.append("]");
        }
        if (provenance != null) {
            sb.append(",\n  \"provenance\": {\n");
            sb.append("    \"kind\": ").append(jsonString(provenance.kind())).append(",\n");
            sb.append("    \"spec\": ").append(jsonString(provenance.spec())).append(",\n");
            sb.append("    \"resolved\": ")
                    .append(jsonString(provenance.resolved()))
                    .append("\n");
            sb.append("  }");
        }
        sb.append("\n}\n");
        return sb.toString();
    }

    private static String jsonString(String s) {
        return Jsonl.quote(s);
    }

    private static String shellQuote(String value) {
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (!(Character.isLetterOrDigit(c) || c == '_' || c == '-' || c == '.' || c == '/' || c == ':')) {
                return "'" + value.replace("'", "'\\''") + "'";
            }
        }
        return value;
    }

    private static void markExecutable(Path file) {
        if (HostPlatform.isWindows()) return;
        try {
            Set<PosixFilePermission> perms = EnumSet.copyOf(Files.getPosixFilePermissions(file));
            perms.add(PosixFilePermission.OWNER_EXECUTE);
            perms.add(PosixFilePermission.GROUP_EXECUTE);
            perms.add(PosixFilePermission.OTHERS_EXECUTE);
            Files.setPosixFilePermissions(file, perms);
        } catch (UnsupportedOperationException | IOException ignored) {
            // Non-POSIX filesystem — caller is on Windows or an exotic FS.
        }
    }
}
