#!/usr/bin/env bash
# Record the top-level jk-lock.toml keys that the jk CI builds this tree with reads, into
# .jk/bootstrap-reads.txt, which the bootstrap-reads-lock guard holds the lock to.
#
# Usage: scripts/bootstrap-reads.sh <commit>
#   <commit>  the bridge .jk/ci-bootstrap-reader names, or, with no bridge, the commit the pinned
#             release was cut from (its tag v<version>)
# The keys are LockfileReader's TOP_LEVEL_KEYS at that commit: a key outside them is refused by
# that jk. Regenerate whenever the pin or the bridge moves.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ref="${1:?usage: scripts/bootstrap-reads.sh <commit>}"
sha="$(git -C "$ROOT" rev-parse --verify "$ref^{commit}")"
source_file="shared/core/src/main/java/cc/jumpkick/lock/LockfileReader.java"
keys="$(git -C "$ROOT" show "$sha:$source_file" \
  | awk '/TOP_LEVEL_KEYS = Set\.of\(/ { inside = 1; next } inside { print } inside && /\);/ { exit }' \
  | grep -oE '"[a-z0-9-]+"' | tr -d '"' | sort)"
if [[ -z "$keys" ]]; then
  echo "bootstrap-reads: no TOP_LEVEL_KEYS in $source_file at $sha" >&2
  exit 1
fi
{
  echo "# The top-level jk-lock.toml keys the jk CI builds this tree with reads: LockfileReader at the"
  echo "# source commit. Generated by scripts/bootstrap-reads.sh; regenerate when the pin or the bridge moves."
  echo "source = $sha"
  printf '%s\n' "$keys"
} > "$ROOT/.jk/bootstrap-reads.txt"
echo "wrote .jk/bootstrap-reads.txt from $sha"
