#!/usr/bin/env bash
# Generate a synthetic multi-module jk workspace for ETA / heap dogfood.
# Usage:
#   ./scripts/generate-synthetic-monorepo.sh <out-dir> [module-count]
# Env:
#   WITH_TESTS=1   add one JUnit test per module (slower lock/build)
#   WITH_DEPS=1    pin junit on each module (requires network for first lock)
set -euo pipefail

OUT="${1:?out-dir required}"
MODULES="${2:-40}"
WITH_TESTS="${WITH_TESTS:-0}"
WITH_DEPS="${WITH_DEPS:-0}"

rm -rf "$OUT"
mkdir -p "$OUT"

mod_list=()
for i in $(seq 1 "$MODULES"); do
  name=$(printf 'm%03d' "$i")
  mod_list+=("\"$name\"")
  dir="$OUT/$name"
  mkdir -p "$dir/src"
  cat >"$dir/jk.toml" <<EOF
[project]
group = "bench"
name = "$name"
version = "0.0.1"
jdk = 25
java = 25
layout = "simple"
EOF
  cat >"$dir/src/Lib.java" <<EOF
package bench;
/** Synthetic module $name for monorepo ETA / heap dogfood. */
public final class Lib {
  public static int id() { return $i; }
  public static String name() { return "$name"; }
}
EOF
  if [[ "$WITH_TESTS" == "1" ]]; then
    mkdir -p "$dir/test"
    cat >"$dir/test/LibTest.java" <<EOF
package bench;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class LibTest {
  @Test void id_is_$i() { assertEquals($i, Lib.id()); }
  @Test void name_matches() { assertEquals("$name", Lib.name()); }
}
EOF
  fi
  if [[ "$WITH_DEPS" == "1" ]]; then
    cat >>"$dir/jk.toml" <<'EOF'

[test-dependencies]
junit-jupiter = "5.11.0"
EOF
  else
    # Minimal lock so offline builds work without resolve.
    cat >"$dir/jk.lock" <<'EOF'
version = 1
generated-by = "generate-synthetic-monorepo"
resolution-algorithm = "pubgrub-v1"
EOF
  fi
done

# Join modules list
mods_joined=$(IFS=,; echo "${mod_list[*]}")
cat >"$OUT/jk.toml" <<EOF
[project]
group = "bench"
name = "synthetic-monorepo"
version = "0.0.1"
jdk = 25
java = 25

[workspace]
modules = [$mods_joined]
EOF

cat >"$OUT/README.md" <<EOF
# Synthetic monorepo ($MODULES modules)

Generated by \`scripts/generate-synthetic-monorepo.sh\`.

## Build

\`\`\`bash
# Fast path (no tests) — preferred for ETA / heap measurement
jk build --skip-tests

# Full rebuild (still skip tests unless WITH_TESTS=1 when generated)
jk build --rebuild --skip-tests

# With tests (only if generated with WITH_TESTS=1 WITH_DEPS=1 + jk lock)
jk build --rebuild
\`\`\`

## Notes

- Modules are independent (no inter-deps) so scheduling width is high.
- Prefer \`--skip-tests\` for 100+ modules; test deps make first lock very slow.
- From a **module subdirectory**, \`jk build\` still runs the **workspace** path for that
  selection — prefer building from the workspace root.
EOF

echo "Generated $MODULES modules under $OUT"
