[project]
name = "app"

[application]
main = "com.example.app.Main"

[dependencies]
lib = { workspace = true }

[test-dependencies]
junit-jupiter           = "6.1.0"
junit-platform-launcher = "6.1.0"
