[project]
name     = "jk-io"
description = "jk I/O foundations: HTTP client, CAS, repo/Maven access, forge credentials."

[dependencies]
jk-core.workspace = true
jk-client-io.workspace = true

[test-dependencies]
assertj-core            = "latest"
junit-jupiter           = "latest"
junit-platform-launcher = "latest"
