@echo off
rem jk bootstrap wrapper - generated by `jk wrapper`; do not edit (regenerate instead).
rem Bootstraps CURRENT jk, never a historical one: newest installed jk satisfying the lock's
rem optional jk-min floor, else the latest published release verified against the release's
rem SHA256SUMS. The lock pins inputs, not the operator.
setlocal enabledelayedexpansion

if "%JK_HOME%"=="" set "JK_HOME=%USERPROFILE%\.jk"
if "%JK_RELEASES_URL%"=="" set "JK_RELEASES_URL=https://jumpkick.build/releases"
set "DIR=%~dp0"

set "FLOOR="
if exist "%DIR%jk-lock.toml" (
  for /f "usebackq delims=" %%L in (`findstr /b "jk-min = " "%DIR%jk-lock.toml"`) do set "LINE=%%L"
  if defined LINE for /f tokens^=2^ delims^=^" %%V in ("!LINE!") do set "FLOOR=%%V"
)

rem Newest installed version satisfying the floor (PowerShell [version] sort).
set "BIN="
if exist "%JK_HOME%\versions" (
  for /f "usebackq delims=" %%V in (`powershell -NoProfile -Command ^
    "$f='%FLOOR%'; Get-ChildItem -Directory '%JK_HOME%\versions' | ForEach-Object Name | Where-Object { $_ -match '^\d' } | Sort-Object { [version]($_ -replace '-.*','') } -Descending | Where-Object { $f -eq '' -or [version]($_ -replace '-.*','') -ge [version]($f -replace '-.*','') } | Select-Object -First 1"`) do set "PICK=%%V"
  if defined PICK if exist "%JK_HOME%\versions\!PICK!\bin\jk.exe" set "BIN=%JK_HOME%\versions\!PICK!\bin\jk.exe"
)
if defined BIN goto run

rem Bootstrap the latest published release.
for /f "usebackq delims=" %%V in (`powershell -NoProfile -Command "(Invoke-WebRequest -UseBasicParsing '%JK_RELEASES_URL%/latest/VERSION').Content.Trim()"`) do set "VERSION=%%V"
if not "%FLOOR%"=="" (
  powershell -NoProfile -Command "exit ([version]('%VERSION%' -replace '-.*','') -ge [version]('%FLOOR%' -replace '-.*','')) ? 0 : 1" || (
    echo jk wrapper: this lock requires jk ^>= %FLOOR% but the latest release is %VERSION% - check JK_RELEASES_URL. 1>&2
    exit /b 1
  )
)
set "BIN=%JK_HOME%\versions\%VERSION%\bin\jk.exe"
if exist "%BIN%" goto run

echo jk wrapper: fetching jk %VERSION% ... 1>&2
set "FILE=jk-windows-x86_64.zip"
set "TMP=%TEMP%\jk-wrapper-%RANDOM%"
mkdir "!TMP!"
powershell -NoProfile -Command "Invoke-WebRequest -UseBasicParsing '%JK_RELEASES_URL%/%VERSION%/%FILE%' -OutFile '!TMP!\%FILE%'; Invoke-WebRequest -UseBasicParsing '%JK_RELEASES_URL%/%VERSION%/SHA256SUMS' -OutFile '!TMP!\SHA256SUMS'" || exit /b 1
rem Verify the zip against the release's SHA256SUMS before expanding.
for /f "usebackq" %%H in (`powershell -NoProfile -Command "$want=(Get-Content '!TMP!\SHA256SUMS' | Where-Object { $_ -match ' %FILE%$' }) -split ' +' | Select-Object -First 1; $got=(Get-FileHash -Algorithm SHA256 '!TMP!\%FILE%').Hash.ToLower(); if ($want -and $got -eq $want) { 'ok' } else { 'bad' }"`) do set "SUMCHECK=%%H"
if not "%SUMCHECK%"=="ok" (
  echo jk wrapper: SHA256SUMS verification failed for %FILE% - refusing. 1>&2
  exit /b 1
)
powershell -NoProfile -Command "Expand-Archive '!TMP!\%FILE%' '!TMP!'" || exit /b 1
for /f "delims=" %%F in ('dir /b /s "!TMP!\*.exe"') do set "CLIENT=%%F"
mkdir "%JK_HOME%\versions\%VERSION%\bin" 2>nul
copy /y "!CLIENT!" "%BIN%" >nul
rmdir /s /q "!TMP!"

:run
"%BIN%" %*
exit /b %ERRORLEVEL%
