@echo off
rem jk bootstrap wrapper - generated by `jk wrapper`; do not edit (regenerate instead).
rem Bootstraps CURRENT jk, never a historical one: installed jk satisfying the lock's
rem optional jk-min floor, else the latest published release verified against the signed
rem SHA256SUMS. The lock pins inputs, not the operator.
setlocal enabledelayedexpansion

rem Bin dir resolution mirrors install.ps1 / JkDirs, which is now one answer rather than a
rem cascade - the wrapper must not invent its own layout.
set "JK_HOME_DIR=%JK_HOME%"
if "%JK_HOME_DIR%"=="" set "JK_HOME_DIR=%USERPROFILE%\.jk"
set "BIN_DIR=%JK_HOME_DIR%\bin"
if "%JK_RELEASES_URL%"=="" set "JK_RELEASES_URL=https://jumpkick.build/releases"
set "RELEASE_RSA_MODULUS=62bXAMmyIpPgiFzT9lcuIPWvvXHmWfGDPbMJAG1lRlbSJ9EFRahqkie0LQaFtXn8W3l2BP/9D0DwdXztS/eVo8WqSNMOZo/srBKrViVJGEOFm0fDmhqrlA3bCZz43+DgFjj7SacI2nJVB4PRjV5jvRwBnZrIUwcvynIQmx2SoWoKgudoje7vNM7UkYmEnZExfmiPQaPmSYCKzXA4pP5KPWD+49bo7o3cLeiO5/Shc27OC0IvK+Vj8CUe4URSt5zHjHUpiE+h4SVTMrGoJg9rgWmRgMHdshsq3aoAkA3jC/YB5SzLwUJeObWGP8I9w7yj8uiSTNIt3KslbRfVtb4vbNoZ4zKPMkCaYhy5ar0sGOqxW97wobIWBiX5pT+knluZErrsJFWpx2dQtRtb2wPovihL7Z9Q18vZb371Gx+rzkNi7jdFvWaGYgsraf01l63Gg2bfy1bleSLhDKmh94yGMoHfszEcE1785xteYOdVSwawUPwWgx8iZ7a4lqOL0Mrr"
set "RELEASE_RSA_EXPONENT=AQAB"
set "DIR=%~dp0"

set "FLOOR="
if exist "%DIR%jk-lock.toml" (
  for /f "usebackq delims=" %%L in (`findstr /b "jk-min = " "%DIR%jk-lock.toml"`) do set "LINE=%%L"
  if defined LINE for /f tokens^=2^ delims^=^" %%V in ("!LINE!") do set "FLOOR=%%V"
)

set "BIN=%BIN_DIR%\jk.exe"
set "USEINSTALLED="
if exist "%BIN%" (
  set "INSTALLED="
  if exist "%BIN_DIR%\VERSION" (
    for /f "usebackq delims=" %%V in (`type "%BIN_DIR%\VERSION"`) do set "INSTALLED=%%V"
  )
  if "%FLOOR%"=="" set "USEINSTALLED=1"
  if not defined INSTALLED set "USEINSTALLED=1"
  if not defined USEINSTALLED (
    powershell -NoProfile -Command "exit ([version]('%INSTALLED%' -replace '-.*','') -ge [version]('%FLOOR%' -replace '-.*','')) ? 0 : 1" && set "USEINSTALLED=1"
  )
)
if defined USEINSTALLED goto run

rem Bootstrap the latest published release.
for /f "usebackq delims=" %%V in (`powershell -NoProfile -Command "(Invoke-WebRequest -UseBasicParsing '%JK_RELEASES_URL%/latest/VERSION').Content.Trim()"`) do set "VERSION=%%V"
if not "%FLOOR%"=="" (
  powershell -NoProfile -Command "exit ([version]('%VERSION%' -replace '-.*','') -ge [version]('%FLOOR%' -replace '-.*','')) ? 0 : 1" || (
    echo jk wrapper: this lock requires jk ^>= %FLOOR% but the latest release is %VERSION% - check JK_RELEASES_URL. 1>&2
    exit /b 1
  )
)

echo jk wrapper: fetching jk %VERSION% ... 1>&2
set "FILE=jk-windows-x86_64-%VERSION%.zip"
set "TMP=%TEMP%\jk-wrapper-%RANDOM%"
mkdir "!TMP!"
powershell -NoProfile -Command "Invoke-WebRequest -UseBasicParsing '%JK_RELEASES_URL%/%VERSION%/%FILE%' -OutFile '!TMP!\%FILE%'; Invoke-WebRequest -UseBasicParsing '%JK_RELEASES_URL%/%VERSION%/SHA256SUMS' -OutFile '!TMP!\SHA256SUMS'; Invoke-WebRequest -UseBasicParsing '%JK_RELEASES_URL%/%VERSION%/SHA256SUMS.sig' -OutFile '!TMP!\SHA256SUMS.sig'" || exit /b 1
set "JK_WRAPPER_TMP=!TMP!"
set "JK_WRAPPER_FILE=%FILE%"
powershell -NoProfile -Command "$d=$env:JK_WRAPPER_TMP; $f=$env:JK_WRAPPER_FILE; $m=[IO.File]::ReadAllBytes((Join-Path $d 'SHA256SUMS')); $st=[Text.Encoding]::ASCII.GetString([IO.File]::ReadAllBytes((Join-Path $d 'SHA256SUMS.sig'))); if($st -notmatch '^[A-Za-z0-9+/]+={0,2}\r?\n?$'){exit 1}; try{$sig=[Convert]::FromBase64String($st.TrimEnd([char[]]\"`r`n\"))}catch{exit 1}; $p=New-Object Security.Cryptography.RSAParameters; $p.Modulus=[Convert]::FromBase64String($env:RELEASE_RSA_MODULUS); $p.Exponent=[Convert]::FromBase64String($env:RELEASE_RSA_EXPONENT); $r=[Security.Cryptography.RSA]::Create(); $r.ImportParameters($p); if(-not $r.VerifyData($m,$sig,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)){exit 1}; try{$text=(New-Object -TypeName Text.UTF8Encoding -ArgumentList @($false,$true)).GetString($m)}catch{exit 1}; $seen=@{}; $want=$null; $count=0; $lines=$text.Split([char]10); for($i=0;$i -lt $lines.Length;$i++){$line=$lines[$i]; if($line.EndsWith(\"`r\")){$line=$line.Substring(0,$line.Length-1)}; if($line.Length -eq 0 -and $i -eq $lines.Length-1){continue}; if($line -notmatch '^([0-9A-Fa-f]{64})  ([A-Za-z0-9][A-Za-z0-9._-]*)$'){exit 1}; $n=$Matches[2]; if($seen.ContainsKey($n)){exit 1}; $seen[$n]=$true; if($n -ceq $f){$count++;$want=$Matches[1].ToLowerInvariant()}}; if($count -ne 1){exit 1}; $got=(Get-FileHash -Algorithm SHA256 (Join-Path $d $f)).Hash.ToLowerInvariant(); if($got -cne $want){exit 1}" || (
  echo jk wrapper: signed release verification failed for %FILE% - refusing. 1>&2
  exit /b 1
)
powershell -NoProfile -Command "Expand-Archive '!TMP!\%FILE%' '!TMP!'" || exit /b 1
for /f "delims=" %%F in ('dir /b /s "!TMP!\*.exe"') do set "CLIENT=%%F"
mkdir "%BIN_DIR%" 2>nul
if exist "%BIN%" move /y "%BIN%" "%BIN%.old" >nul 2>&1
copy /y "!CLIENT!" "%BIN%" >nul
echo %VERSION%> "%BIN_DIR%\VERSION"
del /f /q "%BIN%.old" >nul 2>&1
rmdir /s /q "!TMP!"

:run
"%BIN%" %*
exit /b %ERRORLEVEL%
