@echo off
rem jk wrapper - generated by `jk wrapper`; do not edit (regenerate instead).
rem Dumb and frozen by design (docs/engine-versioning-plan.md section 7): read the exact
rem pin from jk.lock, materialize that client under %%USERPROFILE%%\.jk\versions\<v>\ if
rem missing (sha-verified against the pin), exec it.
setlocal enabledelayedexpansion

if "%JK_HOME%"=="" set "JK_HOME=%USERPROFILE%\.jk"
if "%JK_RELEASES_URL%"=="" set "JK_RELEASES_URL=https://jumpkick.build/releases"
set "DIR=%~dp0"

set "VERSION="
set "SHA="
if exist "%DIR%jk.lock" (
  for /f "usebackq delims=" %%L in (`findstr /b "jk = " "%DIR%jk.lock"`) do (
    set "LINE=%%L"
  )
  if defined LINE (
    for /f tokens^=2^ delims^=^" %%V in ("!LINE!") do set "VERSION=%%V"
    for /f tokens^=4^ delims^=^" %%S in ("!LINE!") do set "SHA=%%S"
  )
)
if "%VERSION%"=="" (
  for /f "usebackq delims=" %%V in (`powershell -NoProfile -Command "(Invoke-WebRequest -UseBasicParsing '%JK_RELEASES_URL%/latest/VERSION').Content.Trim()"`) do set "VERSION=%%V"
)

set "BIN=%JK_HOME%\versions\%VERSION%\bin\jk.exe"
if not exist "%BIN%" (
  echo jk wrapper: fetching jk %VERSION% ... 1>&2
  set "URL=%JK_RELEASES_URL%/%VERSION%/jk-windows-x86_64.exe.zip"
  set "TMP=%TEMP%\jk-wrapper-%RANDOM%"
  mkdir "!TMP!"
  powershell -NoProfile -Command "Invoke-WebRequest -UseBasicParsing '!URL!' -OutFile '!TMP!\jk.zip'; Expand-Archive '!TMP!\jk.zip' '!TMP!'" || exit /b 1
  for /f "delims=" %%F in ('dir /b /s "!TMP!\*.exe"') do set "CLIENT=%%F"
  if not "%SHA%"=="" (
    for /f "usebackq" %%H in (`powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 '!CLIENT!').Hash.ToLower()"`) do set "GOT=%%H"
    if /i not "!GOT!"=="%SHA%" (
      echo jk wrapper: sha256 mismatch for jk %VERSION% - refusing 1>&2
      exit /b 1
    )
  )
  mkdir "%JK_HOME%\versions\%VERSION%\bin" 2>nul
  copy /y "!CLIENT!" "%BIN%" >nul
  rmdir /s /q "!TMP!"
)

"%BIN%" %*
exit /b %ERRORLEVEL%
