#!/bin/sh
# JumpKick bootstrap wrapper — generated by `jk wrapper`. Regenerate rather than editing.
#
# Bootstraps CURRENT jk, never a historical one: uses the newest locally installed jk that
# satisfies the lock's optional `jk-min` floor, else fetches the latest published release
# (verified against the release's SHA256SUMS) and execs it. The lock pins inputs, not the
# operator — there is no version pin here and none in jk-lock.toml.
set -eu

JK_HOME="${JK_HOME:-$HOME/.jk}"
RELEASES="${JK_RELEASES_URL:-https://jumpkick.build/releases}"
case "$0" in */*) DIR="${0%/*}" ;; *) DIR="." ;; esac

# The lock's optional floor: minimum jk able to run this checkout.
FLOOR=""
SEARCH="$DIR"
I=0
while [ "$I" -lt 24 ]; do
  if [ -f "$SEARCH/jk-lock.toml" ]; then
    while IFS= read -r LINE || [ -n "$LINE" ]; do
      case "$LINE" in
        "jk-min = "*)
          FLOOR="${LINE#*\"}"; FLOOR="${FLOOR%%\"*}"
          break
          ;;
      esac
    done < "$SEARCH/jk-lock.toml"
    break
  fi
  case "$SEARCH" in /) break ;; esac
  SEARCH="$SEARCH/.."
  I=$((I+1))
done

# True when $1 >= $2 as dotted versions (pre-release suffixes compare by their numeric core).
ver_ge() {
  A="${1%%-*}"; B="${2%%-*}"
  HI="$(printf '%s\n%s\n' "$A" "$B" | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)"
  [ "$HI" = "$A" ]
}

# Newest installed jk that satisfies the floor.
BIN=""
if [ -d "$JK_HOME/versions" ]; then
  for V in $(ls "$JK_HOME/versions" 2>/dev/null | sort -t. -k1,1n -k2,2n -k3,3n -r); do
    CAND="$JK_HOME/versions/$V/bin/jk"
    if [ -x "$CAND" ]; then
      if [ -z "$FLOOR" ] || ver_ge "$V" "$FLOOR"; then
        BIN="$CAND"
        break
      fi
    fi
  done
fi
if [ -n "$BIN" ]; then
  exec "$BIN" "$@"
fi

# Nothing suitable installed — bootstrap the latest published release.
VERSION="$(curl -fsSL "$RELEASES/latest/VERSION" | tr -d '[:space:]')"
if [ -n "$FLOOR" ] && ! ver_ge "$VERSION" "$FLOOR"; then
  echo "jk wrapper: this lock requires jk >= $FLOOR but the latest release is $VERSION — check JK_RELEASES_URL." >&2
  exit 1
fi
BIN="$JK_HOME/versions/$VERSION/bin/jk"

if [ ! -x "$BIN" ]; then
  OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
  case "$OS" in darwin) OS=macos ;; esac
  ARCH="$(uname -m)"
  case "$ARCH" in amd64) ARCH=x86_64 ;; arm64) ARCH=aarch64 ;; esac
  FILE="jk-$OS-$ARCH.xz"
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  echo "jk wrapper: fetching jk $VERSION ..." >&2
  curl -fsSL -o "$TMP/$FILE" "$RELEASES/$VERSION/$FILE"
  # Verify against the release's own checksum manifest (coreutils format).
  curl -fsSL -o "$TMP/SHA256SUMS" "$RELEASES/$VERSION/SHA256SUMS"
  WANT="$(awk -v f="$FILE" '$2 == f { print $1 }' "$TMP/SHA256SUMS")"
  if [ -z "$WANT" ]; then
    echo "jk wrapper: release SHA256SUMS has no entry for $FILE — refusing." >&2
    exit 1
  fi
  GOT="$( (sha256sum "$TMP/$FILE" 2>/dev/null || shasum -a 256 "$TMP/$FILE") | awk '{print $1}')"
  if [ "$GOT" != "$WANT" ]; then
    echo "jk wrapper: sha256 mismatch for $FILE — refusing (expected $WANT, got $GOT)." >&2
    exit 1
  fi
  # Stock macOS has no xz binary; /usr/bin/compression_tool decodes the xz container.
  if command -v xz >/dev/null 2>&1; then
    xz -dc "$TMP/$FILE" > "$TMP/jk"
  elif [ "$(uname -s)" = "Darwin" ] && [ -x /usr/bin/compression_tool ]; then
    /usr/bin/compression_tool -decode -A lzma -i "$TMP/$FILE" -o "$TMP/jk"
  else
    echo "jk wrapper: cannot decompress .xz; install xz and re-run (Linux: xz-utils; macOS: brew install xz)." >&2
    exit 1
  fi
  mkdir -p "$JK_HOME/versions/$VERSION/bin"
  cp "$TMP/jk" "$BIN.part" && chmod +x "$BIN.part" && mv "$BIN.part" "$BIN"
fi

exec "$BIN" "$@"
