#!/bin/sh
# JumpKick client wrapper — generated by `jk wrapper`. Regenerate rather than editing.
#
# Resolves the pinned client version from jk-lock.toml (see docs/architecture.md),
# materializes ~/.local/share/jk/versions/<v>/ when needed (sha256-verified against the lock),
# and execs that binary. Version selectors and self-updates are handled by the client
# (`jk wrapper <version|latest>`), not this script.
set -eu

JK_HOME="${JK_HOME:-$HOME/.jk}"
case "$0" in */*) DIR="${0%/*}" ;; *) DIR="." ;; esac

VERSION=""
SHA=""
# Walk up from this script’s directory to the workspace-root lockfile.
LOCK=""
SEARCH="$DIR"
I=0
while [ "$I" -lt 24 ]; do
  if [ -f "$SEARCH/jk-lock.toml" ]; then LOCK="$SEARCH/jk-lock.toml"; break; fi
  case "$SEARCH" in
    /) break ;;
  esac
  SEARCH="$SEARCH/.."
  I=$((I+1))
done
if [ -n "$LOCK" ]; then
  while IFS= read -r LINE || [ -n "$LINE" ]; do
    case "$LINE" in
      "jk = "*)
        VERSION="${LINE#*version = \"}"; VERSION="${VERSION%%\"*}"
        SHA="${LINE#*sha256 = \"}"; SHA="${SHA%%\"*}"
        break
        ;;
    esac
  done < "$LOCK"
fi

BIN="$JK_HOME/versions/$VERSION/bin/jk"
if [ -n "$VERSION" ] && [ -x "$BIN" ]; then
  exec "$BIN" "$@"
fi

# Install or bootstrap a client binary when the pinned version is not present.
RELEASES="${JK_RELEASES_URL:-https://jumpkick.build/releases}"
if [ -z "$VERSION" ]; then
  # No lockfile yet — install the latest published release.
  VERSION="$(curl -fsSL "$RELEASES/latest/VERSION" | tr -d '[:space:]')"
  BIN="$JK_HOME/versions/$VERSION/bin/jk"
fi

if [ ! -x "$BIN" ]; then
  OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
  case "$OS" in darwin) OS=macos ;; esac
  ARCH="$(uname -m)"
  case "$ARCH" in amd64) ARCH=x86_64 ;; arm64) ARCH=aarch64 ;; esac
  URL="$RELEASES/$VERSION/jk-$OS-$ARCH.xz"
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  echo "jk wrapper: fetching jk $VERSION ..." >&2
  # Stock macOS has no xz binary; /usr/bin/compression_tool decodes the xz container.
  if command -v xz >/dev/null 2>&1; then
    UNXZ="xz"
  elif [ "$(uname -s)" = "Darwin" ] && [ -x /usr/bin/compression_tool ]; then
    UNXZ="compression_tool"
  else
    echo "jk wrapper: cannot decompress .xz; install xz and re-run (Linux: xz-utils; macOS: brew install xz)." >&2
    exit 1
  fi
  curl -fsSL -o "$TMP/jk.xz" "$URL"
  if [ "$UNXZ" = xz ]; then
    xz -dc "$TMP/jk.xz" > "$TMP/jk"
  else
    /usr/bin/compression_tool -decode -A lzma -i "$TMP/jk.xz" -o "$TMP/jk"
  fi
  CLIENT="$TMP/jk"
  if [ -n "$SHA" ]; then
    GOT="$( (sha256sum "$CLIENT" 2>/dev/null || shasum -a 256 "$CLIENT") | awk '{print $1}')"
    if [ "$GOT" != "$SHA" ]; then
      echo "jk wrapper: sha256 mismatch for jk $VERSION — refusing (expected $SHA, got $GOT)" >&2
      exit 1
    fi
  else
    echo "jk wrapper: WARNING — no jk-lock.toml pin found; installed jk $VERSION without sha256 verification. Run \`jk lock\` to pin it." >&2
  fi
  mkdir -p "$JK_HOME/versions/$VERSION/bin"
  cp "$CLIENT" "$BIN.part" && chmod +x "$BIN.part" && mv "$BIN.part" "$BIN"
fi

exec "$BIN" "$@"
